### ISSUE TITLE
Skybox too clearly visible

### ISSUE THREAD

**Issue by Yuccaa** [loiste-interactive/infra-issues#1]
Jumping on top of that railing will provide too clear view over the wall to the skybox.
![infra_c4_m2_furnace0003](https://cloud.githubusercontent.com/assets/5402153/10866338/7731624c-8032-11e5-9f4a-854061bfc04a.jpg)

**Comment by N-G-Neer** [comment]
Wait. There are dialogs and no-one told me ?!

**Comment by Oskutin** [comment]
Fixed,
