### ISSUE TITLE
Logic errors

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#100]
Those are little things in the world of INFRA that don't make sense from a logical standpoint, little incoherences that I found. (Note that I might be completely wrong for some :P)

in the reserve1 level, the switches and their generators are inverted : 
![inverted generators](https://cloud.githubusercontent.com/assets/15633807/10915654/f84ee9ea-8257-11e5-8535-d3142f780605.jpg)

(Unless intentional) In the reserve2 sluice gates puzzle, the player can go up to 4000 RPM per generator and still be able to activate the main switch.

Still in the reserve2 level, the wood log chute is at the wrong place.
![log chute](https://cloud.githubusercontent.com/assets/15633807/10915916/2fc2ec54-8259-11e5-8668-2cd5a4067515.jpg)

In the tunnel1 level, they key labels in the break-room are inverted. Key D4 open the door to the pump A2 and key A2 open the door to the automated flood door D4. 
![2015-11-02_00031](https://cloud.githubusercontent.com/assets/15633807/10916039/d3a08bf6-8259-11e5-8d6a-5cd510b96bc4.jpg)

In the tunnel2 level, the red lines/blue lines layout in the pumping station doesn't make sense. The water basins are inverted. Here is the physical layout of the station :
![station_physical_layout](https://cloud.githubusercontent.com/assets/15633807/10916364/70f6ae5c-825b-11e5-80f2-767ce35a1dc1.png)

**Comment by Yuccaa** [comment]
Note to devs: first problem fixed now.

**Comment by Oskutin** [comment]
Added some remains of the rest of the log chute.
Added old log barrier.

**Comment by Zuntti** [comment]
Fixed tunnel1 keys and tunnel2 water basins.
