### ISSUE TITLE
Missing texture on newspaper(?) on top of the tower

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#101]
Am I right?
![2015-11-03_00027](https://cloud.githubusercontent.com/assets/15571788/10916448/c700a956-825b-11e5-8b6c-75066b19485c.jpg)

**Comment by Yuccaa** [comment]
Yes, indeed it's a missing texture.

**Comment by N-G-Neer** [comment]
Issue is fixed in December 19th update.
