### ISSUE TITLE
tenements: can't buy passport from passmore

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#1014]
[BrokenSavePassmore.zip](https://github.com/loiste-interactive/infra-issues/files/1345553/BrokenSavePassmore.zip)

**Comment by aradapilot** [comment]
happening to me too
[76561197998115486.zip](https://github.com/loiste-interactive/infra-issues/files/1347457/76561197998115486.zip)

**Comment by aleksijuvani** [comment]
Fixed in the October 3rd patch, but doesn't fix existing saved games. Please let me know if you need me to manually fix the save for you.
