### ISSUE TITLE
isle1: The player should be able to use boxes to climb over the planks and railing on the train track

### ISSUE THREAD

**Issue by Sidewinder53** [loiste-interactive/infra-issues#1018]
While this is certainly no bug, it is slightly confusing to find your way back on the train tracks. The game tells the player that the railing is electrocuted and therefor not a way to pass the on the other side of the track, but if yo use boxes to gain height, you just encounter an invisible wall which prevents the player from climbing over the railing or pile of planks. In my opinion this should be reworked. One option would be to place a rail car on the other side of the train tracks that prevents the player from climbing over the railing. For the stack of planks I would suggest, to either raise the height of the stack or simply allow the player to pass the obstacle. It is not so much different than the intended route.

**Comment by Oskutin** [comment]
Possible now

**Comment by Yuccaa** [comment]
Yeah and that was a bad idea.  Added a fence next to the power rail and made the planks higher.
