### ISSUE TITLE
furnace: bugged door in control room 4

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#102]
Whe interacted, this door closes rotating through the wall,
after that becames a normal door which rotates only 0°↔90°
![2015-11-03_00030](https://cloud.githubusercontent.com/assets/15571788/10918736/96a04792-8267-11e5-8349-aec726a713b2.jpg)
the door is here, in control room 4
![2015-11-03_00029](https://cloud.githubusercontent.com/assets/15571788/10918752/aafa8eaa-8267-11e5-816f-8b44d3dd7b2a.jpg)

**Comment by Oskutin** [comment]
Fixed
