### ISSUE TITLE
Crash when loading villa from river

### ISSUE THREAD

**Issue by NielsGade** [loiste-interactive/infra-issues#1022]
[infra_6900_crash_2017_9_30T15_14_53C0.zip](https://github.com/loiste-interactive/infra-issues/files/1346515/infra_6900_crash_2017_9_30T15_14_53C0.zip)

**Comment by aleksijuvani** [comment]
Thanks for the report. Same issue as #1011. Was this with the latest patch that came out today (3.0.4)?

**Comment by NielsGade** [comment]
I'm afraid so.

**Comment by aleksijuvani** [comment]
I've pushed out another patch that adds a couple of things that make it easier for me to debug this. If you still get this crash after downloading that patch, please send me the crash dumps again.

**Comment by aleksijuvani** [comment]
Should be fixed in the next patch.
