### ISSUE TITLE
business1: Player can access the flooded courtyard

### ISSUE THREAD

**Issue by Sidewinder53** [loiste-interactive/infra-issues#1024]
![20170930180036_1](https://user-images.githubusercontent.com/19623985/31048502-7fc1e242-a61e-11e7-8fce-878d804e786c.jpg)
I suppose the player should not wander around in this area, but it's accessible, and this looks odd.

**Comment by Yuccaa** [comment]
Wait a moment, the water level here ought to be deep enough to deny player access.

**Comment by Yuccaa** [comment]
Fixed.
