### ISSUE TITLE
business1: particles disappear sometimes

### ISSUE THREAD

**Issue by Sidewinder53** [loiste-interactive/infra-issues#1025]
I'm not sure if this is business1 or business2, however one of these levels has some major level streaming issues. Take a look:

https://streamable.com/vwkwd
https://streamable.com/fibho

**Comment by aleksijuvani** [comment]
Looks like your game is missing all particles. There's supposed to be smoke there. Do you have any mods installed? They're known to cause issues like this.

It's also possible that something went wrong while downloading the game. Try right-clicking INFRA on Steam, selecting "Properties", "Local Files" and "Verify Integrity of Game Files...".

**Comment by Sidewinder53** [comment]
The smoke + particles showed up earlier and when I loaded a different save, so it's not an issue with my game files (also, no mods installed).
