### ISSUE TITLE
business1: Greenwar alarm code hard to re-enter after inputting wrong code

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#1026]
If you input the wrong number, it's difficult to type the correct code afterwards. Should only read the latest 4 numbers instead of resetting after 4 presses. Or it should show the numbers on the screen.

![20171001140933_1](https://user-images.githubusercontent.com/3168386/31054027-3fcd5d4e-a6b2-11e7-9b37-cd98f3dc0825.jpg)

**Comment by sebastiannielsen** [comment]
Or have the # key to "validate number", so you press a 3 digit number and then #, if you press a wrong number, press # to start over.

**Comment by N-G-Neer** [comment]
Also, in some cases, even if you enter the right code, the correct beep will play but the screen will still say "armed" : https://youtu.be/7RH3xBSVX2I?t=715

**Comment by Zuntti** [comment]
Fixed.
