### ISSUE TITLE
Bulletin board inside wall [turnip hill market]

### ISSUE THREAD

**Issue by aradapilot** [loiste-interactive/infra-issues#1027]
noticed this with flashlight in the OS market in turnip hill.  looks like a bulletin board is back inside the wall.  rumor has it that the key to the blue duck is on there, so it has gameplay relevance.

![steamuserimages-a akamaihd net](https://user-images.githubusercontent.com/5720437/31058449-a939f0a8-a6c1-11e7-8821-e8c93814bd3c.jpg)
![steamuserimages-a akamaihd1 net](https://user-images.githubusercontent.com/5720437/31058450-a93ae738-a6c1-11e7-8dee-6635f17912e4.jpg)

**Comment by aleksijuvani** [comment]
This is actually an issue on lower end graphics. The bulletin board is in the right place, but it's just not getting rendered. Will have look into it.

**Comment by Zuntti** [comment]
Fixed.
