### ISSUE TITLE
Graphical errors

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#103]
You know your city is in bad shape when even the graphics need maintenance :P Visual glitches and other graphical oddities that I encountered : 

On reserve1, the water that goes into the first building disappears if viewed from a certain angle
![2015-11-01_00006](https://cloud.githubusercontent.com/assets/15633807/10917516/7bb97558-8261-11e5-9f0d-1bf27503103b.jpg)
![2015-11-01_00007](https://cloud.githubusercontent.com/assets/15633807/10917520/7e5639c2-8261-11e5-99e2-999e7175d4d1.jpg)

Some objects appear way brighter than they should, given their surroundings. Here are some examples

![2015-11-01_00012](https://cloud.githubusercontent.com/assets/15633807/10917571/d075fe7c-8261-11e5-9709-6832701a635f.jpg)
![2015-11-01_00013](https://cloud.githubusercontent.com/assets/15633807/10917572/d078634c-8261-11e5-8219-69444f7ecc76.jpg)
![2015-11-01_00014](https://cloud.githubusercontent.com/assets/15633807/10917573/d07b2f6e-8261-11e5-95c1-adff52b905a0.jpg)

In reserve2, the sparks effects from the flooded turbine room can be seen through walls and objects, several rooms before
![sparks_thru_walls](https://cloud.githubusercontent.com/assets/15633807/10917973/9c76c334-8263-11e5-82fd-01a02cd22a2b.jpg)

In tunnel2, at the very start, when the player tries to open the door he just came from, the handle wiggles while another one stays in place.
![2015-11-02_00037](https://cloud.githubusercontent.com/assets/15633807/10918971/99277412-8268-11e5-9ec9-111285cb5f98.jpg)

In tunnel2, the portable light in the collapsed staircase has missing textures.
![2015-11-02_00013](https://cloud.githubusercontent.com/assets/15633807/10919150/78789d12-8269-11e5-9dfd-6cab5b3b5be0.jpg)

In tunnel4, some "portals" didn't load after a while. This is the staircase to the generator bay (with faulty G2) As soon as I went through the door, whatever was not loaded would load instantly but what was just behind me would dissapear.

![2015-11-02_00043](https://cloud.githubusercontent.com/assets/15633807/10919244/040b5072-826a-11e5-82b8-ccedd8266256.jpg)
![2015-11-02_00044](https://cloud.githubusercontent.com/assets/15633807/10919243/040805e8-826a-11e5-8f22-20de3c2c7d5a.jpg)

In tunnel4, part of the rocks that can be blown off with dynamite are missing (on the scaffolding side, not the cavern one)
![2015-11-02_00047](https://cloud.githubusercontent.com/assets/15633807/10919346/9cf63162-826a-11e5-9138-18b570d88dea.jpg)

Some weird shadow effects on some objects like the red fuses when shining the flashlight on it.
![2015-11-02_00049](https://cloud.githubusercontent.com/assets/15633807/10919373/c6f0b546-826a-11e5-94b4-78928efb9384.jpg)

(furnace) Now don't panic, but I think the entire roof of Stalburg Steel had somewhere else to be...
![2015-11-02_00053](https://cloud.githubusercontent.com/assets/15633807/10919714/9eb5df64-826c-11e5-8cad-d974bb222e39.jpg)

Oh and the floor as well...(Another one of these half-and-half portal issues)
![2015-11-02_00054](https://cloud.githubusercontent.com/assets/15633807/10919733/b4b34f40-826c-11e5-8610-a666dcd58ea2.jpg)

**Comment by N-G-Neer** [comment]
Also found this graffiti on the ground right before the end of tower. It's on your right when exiting the big office building.
![2015-11-05_00002](https://cloud.githubusercontent.com/assets/15633807/10959231/77c5e7cc-8376-11e5-9e43-32028bb07a80.jpg)

And this sheet of paper isn't quite legible I'm afraid :P (inside said office building after coming down from the tower. It's in the room behind the phone booths) 
![2015-11-05_00001](https://cloud.githubusercontent.com/assets/15633807/10959238/978f6c86-8376-11e5-8784-941544618d10.jpg)

**Comment by N-G-Neer** [comment]
Found some more buggy portals in furnace : 
![2015-11-09_00001](https://cloud.githubusercontent.com/assets/15633807/11045480/0d82fe3a-8728-11e5-9df9-ebe2ea47530b.jpg)
![2015-11-09_00002](https://cloud.githubusercontent.com/assets/15633807/11045481/0d85f6bc-8728-11e5-82ab-ac26ca6a7b06.jpg)

**Comment by Oskutin** [comment]
Opened #167 for those shadows. Everything else should be more or less fixed in next update.
