### ISSUE TITLE
tunnel4 : mushroom cave ambiance too loud

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#1034]
I play the game with a 2.1 speaker setting and the sound in this particular spot in the game makes my whole desk vibrate with the powerful shroomy bass :P Maybe dial it back down a bit ?
![20170929015827_1](https://user-images.githubusercontent.com/15633807/31076693-bcf6baee-a77b-11e7-94a9-eb7d4d32a018.jpg)

**Comment by Zuntti** [comment]
Fixed?
