### ISSUE TITLE
powerplant2 : Geocache logic

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#1035]
Aren't geocaches supposed to be in publicly accessible areas ? Hence why there are none in the Bergman Tunnels, Stalburg Steel, etc...

Because this one is surrounded by four walls of private property (to a certain extend, so is the one in office, but eh...)

Maybe move it to the abandoned part right before the elevator drop ?
![20171001032203_1](https://user-images.githubusercontent.com/15633807/31078469-9982c1aa-a782-11e7-9ba9-a24d75330b82.jpg)

**Comment by Zuntti** [comment]
Changed location.
