### ISSUE TITLE
business2 : water draining puzzle issue

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#1036]
If you rotate the valve before proceeding to turn the power back on, the water will drain when you activate the pump, but the gate on top of the stairs won't open.
![20171001173822_1](https://user-images.githubusercontent.com/15633807/31078720-7840c22a-a783-11e7-8ae0-27120132561a.jpg)
![20171001173823_1](https://user-images.githubusercontent.com/15633807/31078722-790312d0-a783-11e7-964b-0365858cc8aa.jpg)

**Comment by sebastiannielsen** [comment]
The delay was increased. Have you waited enough? It was like 4-5 minutes before the gate open.

**Comment by N-G-Neer** [comment]
Guess I didn't wait long enough. It works.
