### ISSUE TITLE
roof : weird camera-locked reflections

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#1038]
When looking at the "lake" outside the plant, the sky reflection follows the camera movement
![20171002045557_1](https://user-images.githubusercontent.com/15633807/31078882-2579e386-a784-11e7-9db6-a997ee3654ae.jpg)
![20171002045558_1](https://user-images.githubusercontent.com/15633807/31078881-25795f4c-a784-11e7-99cb-26d97fbd4144.jpg)
![20171002045558_2](https://user-images.githubusercontent.com/15633807/31078883-25839732-a784-11e7-8d24-b7f6a1a5c7c4.jpg)

**Comment by Zuntti** [comment]
Fixed.
