### ISSUE TITLE
Out Of Bounds/Stuck issues

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#104]
When your hard hat gets stuck in the ceiling or you end up where you aren't supposed to.

reserve3 : Now I'm not a structural analyst, but I'm 80% sure I was NOT supposed to be here...(I managed to climb over the railing, with the animation and all.)
![2015-11-02_00002](https://cloud.githubusercontent.com/assets/15633807/10919483/7856ecba-826b-11e5-92e2-ce5cde72fe24.jpg)

reserve2 : At the very entrance of the dam building. Managed to nudge myself between those barrels and the railing. Died from falling/crushing damage...Don't ask.

![2015-11-02_00021](https://cloud.githubusercontent.com/assets/15633807/10919550/e7b91358-826b-11e5-9070-3b2e44fb8c93.jpg)

Stuck. Now, I don't remember where this is...I think it's the old tunnel after that scaffolding part in tunnel4. Does anyone have a pickaxe ?

![2015-11-02_00048](https://cloud.githubusercontent.com/assets/15633807/10919659/562c10ec-826c-11e5-84e4-55fbca75dbc6.jpg)

Was running in circles in furnace, didn't realize the red button of the crane wouldn't zap me, got desperate, climbed over the railing of the catwalk between two machines, got stuck forever.
![2015-11-02_00052](https://cloud.githubusercontent.com/assets/15633807/10919860/5f5febb0-826d-11e5-9aec-592fcdab66a6.jpg)

Tried to do some alpinism, climbed on the right slope, slipped and ended up stuck against the now broken funicular in reserve2.
![2015-11-04_00001](https://cloud.githubusercontent.com/assets/15633807/10925453/9d39c8d6-828e-11e5-90c0-f17dc4df5de7.jpg)

**Comment by Yuccaa** [comment]
That first image is an allowed location. Not something the player is supposed to go though. But incase you manage to fall there, you can walk back on the edge of the rock on your right.

**Comment by N-G-Neer** [comment]
Oh, you can ? My bad then... ^^'

**Comment by Yuccaa** [comment]
Image 2: couldn't replicate that bug, but I moved the barrels a bit so now the player can just walk between them and the railing.

**Comment by Oskutin** [comment]
Fixed from furnace.

**Comment by Zuntti** [comment]
Fixed from tunnel4.

**Comment by N-G-Neer** [comment]
Welp, found another spot in tunnel4...Sorry xD
![2015-11-04_00010](https://cloud.githubusercontent.com/assets/15633807/10946834/b83258ba-8324-11e5-8028-7cd75e6d5a61.jpg)

**Comment by Zuntti** [comment]
Fixed tunnel4 generator room spot.

**Comment by Oskutin** [comment]
Fixed from reserve2
