### ISSUE TITLE
tunnel4 : waterfall particles clipping inside

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#1044]
![20170929022248_1](https://user-images.githubusercontent.com/15633807/31079501-2a2ba1ba-a786-11e7-98db-dfd3e5a5c10a.jpg)
If you go through the left door in the generator bay so the water particles can spawn on the other side, then stand in the doorway, you'll see the water particles clipping inside the generator room.

**Comment by aleksijuvani** [comment]
Fixed.
