### ISSUE TITLE
tunnel4 : clipping through the ceiling in collapsed tunnel

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#1045]
In the old tunnel, the player can crouch to scale the debris then stand up through the ceiling in this particular spot

![20170929022620_1](https://user-images.githubusercontent.com/15633807/31079619-86a93eca-a786-11e7-996e-df7692c4e88c.jpg)
![20170929022617_1](https://user-images.githubusercontent.com/15633807/31079618-869c75aa-a786-11e7-9e71-8b938ee6920d.jpg)

**Comment by Zuntti** [comment]
Fixed.
