### ISSUE TITLE
central : weird collisions in this room

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#1051]
The players climbs invisible cables and is blocked in random places in the crate room beneath the central station.
![20170930231950_1](https://user-images.githubusercontent.com/15633807/31080487-18865740-a789-11e7-90a1-599b1ce87af2.jpg)
![20170930232014_1](https://user-images.githubusercontent.com/15633807/31080488-18885d74-a789-11e7-91ef-9b6d22253667.jpg)
![20170930231949_1](https://user-images.githubusercontent.com/15633807/31080489-188b7298-a789-11e7-99e6-b1a74e686b69.jpg)

**Comment by Zuntti** [comment]
Fixed.
