### ISSUE TITLE
stormdrain: mushroom pipe incorrectly initialized

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#1052]
When arriving in this room, the pipe was open visually and made Mark cough, but I couldn't take a picture, even when standing on the shrooms. Turning the valve didn't move the pipe cover until the valve was fully turned. The cover then slowly closed back without me touching the valve.

![20171001014219_1](https://user-images.githubusercontent.com/15633807/31080932-81a58c68-a78a-11e7-99e7-90a1cf5bb1c9.jpg)
![20171001013927_1](https://user-images.githubusercontent.com/15633807/31080933-81bc7202-a78a-11e7-87f7-e322a68eed2a.jpg)

**Comment by N-G-Neer** [comment]
Video proof : https://youtu.be/laSSvknVdAE?t=1141

**Comment by Yuccaa** [comment]
Fixed.
