### ISSUE TITLE
isle1: stuck in bushes

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#1057]
http://steamcommunity.com/app/251110/discussions/1/1520386297703834530/

> After leaving the plant in start of part 3, there is a harbour building where you can climb some stairs to get to the secound floor. There is a box in front of an broken/missing window.
>
> When you jump down you will land in some bushes, a tree and a wooden box. I was not able to leave that bushes. I had to reload.

**Comment by Oskutin** [comment]
Fixed
