### ISSUE TITLE
rails: stuck in hacker container

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#1059]
http://steamcommunity.com/app/251110/discussions/1/1520386297703834530/

> Same area: there are some containers with a computer in it. If you enter the upper container, unlock the door with a key you will find a room with computers and a shower curtain.
I jumped upwards in front of the server in the back part of that small room and got caught within a cable which goes from left to right in that room at the ceiling. It took me quite a wile (hitting the D button) to move pixel by pixel. Finally I could leave the room.

**Comment by Zuntti** [comment]
Fixed?
