### ISSUE TITLE
isle2 : rename "unused" switch to something less error-inducing

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#1066]
In the fusebox puzzle to power the courtyard gates and turnstile, I think the "unused" lever should be renamed something like "Input" or anything to indicate the current is coming through this switch.

**Comment by Oskutin** [comment]
It now has big red text telling to keep it on.

**Comment by aleksijuvani** [comment]
Looks like this was already added in the last patch.
