### ISSUE TITLE
isle3: Minor graphical glitch

### ISSUE THREAD

**Issue by Sidewinder53** [loiste-interactive/infra-issues#1068]
In the right-most hallway (of 4), at the beginning of the level, there is a minor graphical glitch where two wall textures are missaligned by a few pixels. It's located near the middle of the tunnel on the right side. In this dark environment it is easy to see the void trough that crack.

**Comment by N-G-Neer** [comment]
https://youtu.be/bAxEIZeRsVk?t=1383

**Comment by Yuccaa** [comment]
Fixed.
