### ISSUE TITLE
Forseen Consequences : Weird Mark line

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#1070]
I feel this line was meant to be used somewhere else. Didn't Mark used to go "Shit, shit, shit !" ? (and rightfully so)
![20171006040754_1](https://user-images.githubusercontent.com/15633807/31260233-c038f360-aa4c-11e7-9579-fe41edaeb7ee.jpg)

**Comment by Oskutin** [comment]
Fixed

**Comment by sebastiannielsen** [comment]
The line isn't weird. Before, the line was just "Shit!" and was used both in the crack scenario, but also in the fire alarm scenario in, I think it was tunnel3 or tunnel4. Then the line was changed, but not really noticing it was also used in the crack scenario.
