### ISSUE TITLE
Burgular alarm in business1 should use the tunnel4 alarm sound

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#1071]
The burgular alarm in business1 should, IMHO use the tunnel4 fire alarm sound. Its more realistic alarm sound.
Same with the watertreatment, there the burgular alarm for breaking the window, could use the tunnel4 alarm sound aswell. (But in watertreatment it makes more sense to have it at a lower volume)

**Comment by Zuntti** [comment]
Changed.
