### ISSUE TITLE
tenements: Breaking level by accessing out-of-bound area

### ISSUE THREAD

**Issue by KohGeek** [loiste-interactive/infra-issues#1082]
Sorry for the lack of photos.

After entering turnip hill and exiting through the only door, turn left, and then turn left again to see the library/bookstore-esque shop. 

Climbing up the staircase railings, and then onto the lights mounted on the wall will allow the user to crawl onto the roof of the container, and then exiting on the other side, breaking the map and warranting a reload.

**Comment by Zuntti** [comment]
Fixed.
