### ISSUE TITLE
reserve3 : Door to Control Room and newly added gate won't close once open.

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#110]
Why bother fixing these doors ? Let the player collect cans of Stalburg brand WD-40 and let him fix those damn things himself :P 

![2015-11-04_00003](https://cloud.githubusercontent.com/assets/15633807/10925783/829cf964-8291-11e5-9f35-b26c92ac551d.jpg)

![2015-11-04_00002](https://cloud.githubusercontent.com/assets/15633807/10925669/786586f6-8290-11e5-8858-4194ef37312a.jpg)

**Comment by Oskutin** [comment]
This should be fixed now too
