### ISSUE TITLE
isle2: Player can climb onto a backyard with no way out

### ISSUE THREAD

**Issue by paavohuhtala** [loiste-interactive/infra-issues#1103]
![20171025233419_1](https://user-images.githubusercontent.com/803180/32023690-b729f0c6-b9e2-11e7-8917-08a9e6772b71.jpg)
![20171025233424_1](https://user-images.githubusercontent.com/803180/32023692-ba1daca0-b9e2-11e7-960f-da0a1335a79a.jpg)
![20171025233439_1](https://user-images.githubusercontent.com/803180/32023696-bd020cc2-b9e2-11e7-8a98-e12574f359af.jpg)

You can climb on the small dumpster and then on the hedge, where you can jump to the small fenced back yard where you can't escape.

**Comment by Yuccaa** [comment]
Fixed.
