### ISSUE TITLE
reserve3 : Control Room puzzle bug

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#111]
If you spin the color-path knobs too fast (the bottom-right one in my case. I turned it one step too far and then spammed the interact button to get it back into the correct orientation), even if they are set in the correct position, the gate won't open, despite the green light next to it and in the control room.

![2015-11-04_00004](https://cloud.githubusercontent.com/assets/15633807/10926087/31875440-8294-11e5-8ff7-0f88e021dc01.jpg)

![2015-11-04_00005](https://cloud.githubusercontent.com/assets/15633807/10926093/3c52da34-8294-11e5-9657-980964f3c443.jpg)

**Comment by Oskutin** [comment]
Fixed

**Comment by N-G-Neer** [comment]
Thank you !
I'm curious. Judging by the sheer number of fixed issues already in the WIP update, we shouldn't be too far from said update release, right ? Do you have any date scheduled already ?

**Comment by Oskutin** [comment]
Getting closer.

We still need to add 3 more levels into beta.

**Comment by N-G-Neer** [comment]
New content ? Oh, goody ^^
