### ISSUE TITLE
isle1: workshop lights need to be sometimes turned off and on for the gate to work

### ISSUE THREAD

**Issue by Yuccaa** [loiste-interactive/infra-issues#1117]

**Comment by GotLag** [comment]
I think I may have found where it's going wrong, and can reliably reproduce it. In [this save](https://github.com/loiste-interactive/infra-issues/files/1618337/isle1quick.zip) I had forgotten to pick up the keycard and the workshop lights are on again after using the elevator.

If you load that save, run back to the workshop and grab the card, the reader is inactive.
If you switch the workshop lights off and on again, *then* grab the card, the reader is still inactive.

if you pick up the keycard *first* and then toggle the lights, the reader works.

**Comment by GotLag** [comment]
Addendum: pressing the generator starter (green button) works in the same way as the lights, it only activates the reader if the player has picked up the card by the time the "engine start" noise is finished.

As a secondary issue, shouldn't the generator starter be disabled when the generator is already running?

**Comment by Zuntti** [comment]
Fixed.
