### ISSUE TITLE
reserve1: Stuck between stairs and rock

### ISSUE THREAD

**Issue by Starscre4M** [loiste-interactive/infra-issues#112]
While I was walking on the rocks, I got stuck in here, it was easy to reproduce.

![2015-11-03_00003](https://cloud.githubusercontent.com/assets/5266547/10927177/c45eafda-8284-11e5-8c69-97b34b9ebe37.jpg)
![2015-11-03_00004](https://cloud.githubusercontent.com/assets/5266547/10927178/c56a8548-8284-11e5-8f1a-0772782f833c.jpg)

**Comment by Yuccaa** [comment]
Fixed in the next update.
