### ISSUE TITLE
Graphical problems

### ISSUE THREAD

**Issue by DevinShadowV** [loiste-interactive/infra-issues#113]
I have mutiple graphical problem with some before and after shots as well...
![2015-11-03_00001](https://cloud.githubusercontent.com/assets/15645339/10930742/f6a944be-8275-11e5-92c4-8f4d1c5d3613.jpg)
![2015-11-03_00002](https://cloud.githubusercontent.com/assets/15645339/10930746/f6ae2c54-8275-11e5-90c1-d32db292608e.jpg)
![2015-11-03_00003](https://cloud.githubusercontent.com/assets/15645339/10930743/f6aaf19c-8275-11e5-8ab9-bdfdfd9a088a.jpg)
![2015-11-03_00004](https://cloud.githubusercontent.com/assets/15645339/10930745/f6ac3566-8275-11e5-982f-958dcbdbfd9b.jpg)
![2015-11-03_00005](https://cloud.githubusercontent.com/assets/15645339/10930741/f6a868a0-8275-11e5-802e-8ee155e4c299.jpg)
![2015-11-03_00006](https://cloud.githubusercontent.com/assets/15645339/10930744/f6ac11ee-8275-11e5-9c6e-30754640ef9b.jpg)
![2015-11-03_00007](https://cloud.githubusercontent.com/assets/15645339/10930748/f6c028f0-8275-11e5-801f-33531e0f2ecc.jpg)
![2015-11-03_00008](https://cloud.githubusercontent.com/assets/15645339/10930747/f6bfd594-8275-11e5-961b-e722e4ce8779.jpg)

**Comment by Suhov** [comment]
There is also problematic water texture on reserve1 - under certain angles it might not render at all: 
![2015-11-04_00003](https://cloud.githubusercontent.com/assets/15650861/10938160/07d6cce6-8309-11e5-8418-27d3018fe16b.jpg)
![2015-11-04_00004](https://cloud.githubusercontent.com/assets/15650861/10938161/07d742c0-8309-11e5-90c7-b8328eca154e.jpg)
Settings are: High textures, 4x MSAA, 16xAA. Randomly under some view angles water won't be rendered.

**Comment by Oskutin** [comment]
That door is now fixed.
