### ISSUE TITLE
Sign for Insufficient Frequency at the castle power box too high

### ISSUE THREAD

**Issue by Sichelgaita** [loiste-interactive/infra-issues#1130]
The sign saying "Insufficient Hz" seems to be floating above the power box somehow. I don't think it was positioned like that before.

Front view:
![20171106220352_1](https://user-images.githubusercontent.com/33286609/32569506-994589d2-c4c1-11e7-8a59-2e86d9f69292.jpg)

Back view:
![20171106220400_1](https://user-images.githubusercontent.com/33286609/32569527-a265be4c-c4c1-11e7-9f94-b3bcd5cd8430.jpg)

Sorry for the dark images, I hope it's still visible.

**Comment by Yuccaa** [comment]
Fixed.
