### ISSUE TITLE
business2: minitrain hard to turn on

### ISSUE THREAD

**Issue by pablotheflapmaster** [loiste-interactive/infra-issues#1158]
I had a very difficult time selecting the "ON/OFF" button instead of the forward/reverse lever. The button had an extremely small area it allowed me to select.
![20171121212518_1](https://user-images.githubusercontent.com/17535239/33221443-7002c7a2-d104-11e7-9611-26a2d88ac5b6.jpg)

**Comment by Zuntti** [comment]
Fixed.
