### ISSUE TITLE
Bunker - dam connected to grid but no second breaker light.

### ISSUE THREAD

**Issue by davehnz** [loiste-interactive/infra-issues#1168]
Even though the dam was connected to the grid, early in the game. The second breaker cannot be activated. This is from the same play-though in a newly purchased copy.

**Comment by Zuntti** [comment]
Hi,
Could you send me the save files? You can find your saved games by right-clicking INFRA on Steam and selecting "Properties", "Local Files" and "Browse Local Files...". The saves are stored in the "infra/SAVE" folder. I only need the ".sav" files. Also did you get the "Power of the Future" achievement?

**Comment by davehnz** [comment]
Hello. Yes I have the lighting bolt achievement for connecting the dam
which made this very frustrating. Note: I saw other people had used noclip
to enter the locked bunker area so I did that. Have now left the bunker
area.

*Also, github rejected my message because it was too big, the .sav files
are 15MB zipped.*



Thanks!

**Comment by Zuntti** [comment]
Hey,
Can you send those save files to contact@loisteinteractive.com

**Comment by Zuntti** [comment]
Fixed. Also added autosave when you connect damn to grid.
