### ISSUE TITLE
metro: a typo

### ISSUE THREAD

**Issue by deseven** [loiste-interactive/infra-issues#1190]
"transist" in `props_clutter/metro_ticket`  
![image](http://eri.deseven.info/scr/UngownedYodelerWhimsic.png)

**Comment by deseven** [comment]
![](https://d7.wtf/UnfreelyPlasmoptysisFibroangioma.png)

https://d7.wtf/s/metro_ticket.vtf

**Comment by Oskutin** [comment]
"Fixed"
