### ISSUE TITLE
Linux port

### ISSUE THREAD

**Issue by Severse** [loiste-interactive/infra-issues#1192]
If you read my previous issue I was naively trying to port INFRA to linux. I am opening this issue as I am wondering what branch of the source engine INFRA uses. By the looks of it INFRA is using bsp verison 22 (dota 2). Is this correct?

**Comment by TeamSpen210** [comment]
It's based off the Portal 2 branch, at least partially but with lots of changes. All the tools you use and whatnot, the photo and corruption system, climbing, it's all custom. So I don't think you'd get very far, beyond just porting environments to a different branch. Even then, the various BSP limits have been increased, so existing games probably won't handle it without you doing the same.

**Comment by Severse** [comment]
By any chance do you know how to get portal 2 to accept bsp version 22?

**Comment by Severse** [comment]
I have already checked their and that is how I found out version 22 is for dota 2. What I am wondering is, Why was this bsp version chosen for making INFRA, what are the benefits of using bsp version 22 and how do I get portal 2 to accept version 22 bsp files? Thank you and I apologise for the lack of clarity.

**Comment by TeamSpen210** [comment]
The version number is simply a method to inform the game that the map was compiled with a different compiler version. It's mostly arbitrary. In this case, likely Loiste simply incremented it by one once they made incompatible changes to the Portal 2 map format, and didn't notice DOTA 2 also had that number. It's a warning; you **cannot** make Portal 2 accept it, without having the game's source code in order to reimplement the missing features. By that point you'd just have a copy of INFRA. Your best bet is to compile the maps in the P2AT compiler, although it's likely you'll hit various limits that were changed in order to handle the INFRA maps. In any case there's lots of additional map objects and other items that will utterly fail in Portal 2.

**Comment by Severse** [comment]
Thank you very much for the reply. I have tested compiling the map using vbsp in the portal 2 folder (not portal 2 authoring tools but I doubt this would make a difference) and it now says:
`Unknown version 2 for vpk /home/james/documents/infra/infra/pak01`
I will try unpacking then repacking the vpks and then I will get back to you when I try compiling it after fixing the vpks. All that I am trying to do is get the map to work, then after that that I will implement the missing features (eg. camera, torch). Thank you

**Comment by Severse** [comment]
I have decided that using portal 2 as a base isn't going to work. I would like to obtain INFRA's source code as this would greatly help this project.

**Comment by CorruptComputer** [comment]
Don't get me wrong, I would absolutely love to see a Linux port. However I don't think this is the right way to go about it. Loiste would probably never give up the source of INFRA as it would lead to piracy, if you really want it on Linux I would talk to them about it. I've offered to port it myself in the past, but they have no interest in it from what I've seen as it would cause more work for them than they would like to, as they now have more games they are working on. 

If I were you I would put my work into improving Wine, as it already works great with that and it could benefit many other games at the same time.

**Comment by CorruptComputer** [comment]
Just talked to a Loiste dev and this is currently not possible for a few reasons. They would need to update their branch of Source and that is very difficult to do with the modifications, and possibly even impossible as they would need to get Valve to approve it and send them the newer sources. Which comes to the second reason, they are under a NDA from Valve which makes it impossible for them to ever release the source for INFRA. This is part of their licensing agreement for the Source engine and there is no way around it.

**Comment by Severse** [comment]
That's a shame. Thank you so much to everybody who answered my questions. I might still try a different approach but maybe I should just leave it as it is very complicated to port it to linux and you don't really have anywhere to start from as there is not the INFRA source code nor the Portal 2 source code publicly available (unlike source sdk 2013).
