### ISSUE TITLE
reserve1-2: information boards typos

### ISSUE THREAD

**Issue by deseven** [loiste-interactive/infra-issues#1197]
"capasity" in `information_board_001_skin1`:
![](https://d7.wtf/SisymbriumPittosporaceaeMiddy.png)

"wihout" in `information_board_001_skin4`:
![](https://d7.wtf/PreindisposePhysicochemicCacodaemonic.png)

**Comment by deseven** [comment]
![](https://d7.wtf/BrochEulaliaFendering.png)

https://d7.wtf/s/information_board_001_info_skin1.vtf

![](https://d7.wtf/NativeUnrequitableFutileness.png)

https://d7.wtf/s/information_board_001_info_skin4.vtf

**Comment by Oskutin** [comment]
"Fixed"
