### ISSUE TITLE
watertreatment : Is there a way to get the water clean ? (SPOILERS)

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#120]
![2015-11-05_00003](https://cloud.githubusercontent.com/assets/15633807/10959072/b6166e18-8374-11e5-8085-8cdac2ba1a4c.jpg)

This is what I did : 
- Turned on sewer pipes in the small blue-access building near the larger blue-access building with the cracked window and alarm system.
- Went inside said building and turned off the Steel Factory pipes.
- Turned on the grit classifier in the same building.
- Went to the poisonous room and turned on the tank.
- Went to the far right building with the switch on some kind of recessed balcony (the blower building, I think it was ?)
- Went to the red access building with the water sampler thingie and successfully turned on the second secondary clarifier.
- Grabbed beaker from nearby box and took a water sample.
- Analyzed it in the lab, results say "CONTAMINATED WATER".
Am I missing something or is it supposed to be that way ?

**Comment by Oskutin** [comment]
According to Mikko, there isn't yet any way to clean the water.

**Comment by N-G-Neer** [comment]
![2015-12-19_00035](https://cloud.githubusercontent.com/assets/15633807/11915239/e0aea3f6-a69d-11e5-97fa-7d7f81ea81f5.jpg)
Another question : There used to be a lot more error lights blinking here. Did you change anything or does this actually reflect the spots you repaired/the sensor boxes you turned back on ?

**Comment by Oskutin** [comment]
Yep, it's about the sensor boxes.

**Comment by N-G-Neer** [comment]
Okay, thanks ! So I assumed I missed something on tunnel2 then ? Is the main alarm light on the left always supposed to be on ? (I would assume so since the entire tunnel almost caved in on you)
