### ISSUE TITLE
metro,central,etc: bad metrolines markings

### ISSUE THREAD

**Issue by deseven** [loiste-interactive/infra-issues#1200]
![](https://d7.wtf/UngastricNemopanthusAccusive.png)
As you can see here, line markings are swapped up (2>3, 3>2).

@Oskutin said it's better to swap markings in metromaps, so here is the list of offending textures (there may be more):  
`metro_line_map_001`  
`metro_line_map_001_skin1`  
`metro_line_map_001_skin2`  
`metro_line_map_001_skin3`  
`metro_line_map_002_skin1` (with legend)  
`metro_line_map_002_skin2` (with legend)

**Comment by deseven** [comment]
https://d7.wtf/s/metro_lines.zip

**Comment by deseven** [comment]
just updated that archive, forgot about masks

**Comment by Oskutin** [comment]
"Fixed"
