### ISSUE TITLE
isle2: "impossible" mistake target

### ISSUE THREAD

**Issue by TeamSpen210** [loiste-interactive/infra-issues#1201]
As far as I can tell, every mistake target is possible to avoid, either by going an alternate route or putting equipment back to the correct state. However, the switchbox mistake in `isle2` (`houses_not_switched_on`) seems unavoidable. This mistake fires if you interact with the switchbox, and you don't turn on power to all the houses - something that is impossible with the power provided by the generator. Being able to do so would defeat the actual puzzle here anyway. 

Looking at the various player clips, it's fairly clear it's intended that the keycard doors are required to get access to Castle Stalburg and therefore the button. So avoiding touching the switchbox is impossible. Furthermore the mistake doesn't make too much sense - the houses don't actually turn on or are setup to do so. If keeping the mistake target is desired, simply making it not depend on the generator would make sense - you leave it off, but turn on all the switches so that it's ready when the city power returns. Might require tweaking how the switches work though.

**Comment by Oskutin** [comment]
You should be able to untrigger that mistake target after visiting the castle by returning the box to default settings.
