### ISSUE TITLE
Flashlight comes up with no animation after respawn

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#121]
Sometimes when you die and respawn, or when a level loaded, when you first bring up your flashlight, it will pop up immediately without animation. I haven't tested it for the camera yet.

**Comment by aleksijuvani** [comment]
Yeah, I can confirm this. It's a very elusive bug. I don't think it happens with the camera, just with the flashlight.

**Comment by aleksijuvani** [comment]
I might have fixed this in the next update, but I can't be sure since I can't reproduce this bug reliably. Will reopen if not fixed.

**Comment by aleksijuvani** [comment]
Still an issue.

**Comment by aleksijuvani** [comment]
I might have fixed this (again). I just played all the way from `reserve1` to `tunnel2` without being able to reproduce the issue even though I died multiple times.

**Comment by aleksijuvani** [comment]
Okay, I think this is fixed for good now. I had a saved game where this was happening, and it doesn't happen there anymore so I'm like 90% confident it's fixed.
