### ISSUE TITLE
Global feedback on furnace level and suggestions

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#126]
**Crane controls**
![2015-11-04_00015](https://cloud.githubusercontent.com/assets/15571788/10974502/c0747710-83e2-11e5-8b31-c1d5a6b7a804.jpg)
I saw others complained about this, you should relly highlight the different buttons, but the real problem is: if you don't know that you can press the single button, it'll be quite impossible to figure it out because you die immediatly and you don't even know what you pressed; on the other way, if you see that all the buttons are usable the puzzle suddenly becames really easy!
A possible solution to improve the puzzle could be to have also to assemble the button on the crane controls: the player could find the missing button hidden in some corner of the map (to encourage exploration) with a note like this: *The crane controls are breaking continuosly! This morning a button fell off, could you fix it by tomorrow?*. In this way the player should:

**Turn ON power**  →  **Find the button**  →  **Use button on controls**  →  **Press the right button**
(all buttons are deadly)─────────(now all buttons but one are deadly)

**The trapdoor**
I think that the place where the trapdoor key is hidden is a nice one (not too easy, not too frustraing),
But the trapdoor itself is quite invisible, I first thought that it was fake! You could:
1. highlight the trapdoor
2. put a source of light to catch the player attention on the trapdoor and it's message
(I found the key BEFORE the trapdoor)
![screenshot_20151105181042](https://cloud.githubusercontent.com/assets/15571788/10975724/90d40c72-83e8-11e5-92c1-f32e4ba0895a.png)

**Track control voltage**
![2015-11-05_00003](https://cloud.githubusercontent.com/assets/15571788/10975842/1ea06988-83e9-11e5-802b-701f38db05aa.jpg)
This really needs to be made more visually clear: at first I thought yhat I had somehow to activate all the levers in order to turn on ALL the tracks (and I even thought that the big red light would have become green), but this is obviously impossible and I got stuck. It can be really hard to understand what each lever does, you could:
1. dont'd call the levers **1 2 3 4** but something like **1F 2F 1B 2B** (forward & backward)
2. use the color of the cables as a hint to link levers 1-3 and 2-4 to the respective tracks
![screenshot_20151105183628](https://cloud.githubusercontent.com/assets/15571788/10976444/286d0518-83ec-11e5-897d-8183460566f3.png)
3. some other type of visual linkage
![screenshot_20151105184240](https://cloud.githubusercontent.com/assets/15571788/10976623/186a7406-83ed-11e5-827c-90ab3cec36f0.png)

Also highlight the controls of the vehicles!
![2015-11-05_00004](https://cloud.githubusercontent.com/assets/15571788/10976685/70a4a3e4-83ed-11e5-896e-299f6b627336.jpg)

**The cupola furnace**
The sequence around the cupola furnace is perfect as it is, but the first times it's easy to die, it's not strictly necessary but you could put a save point just before the main switch 
![2015-11-05_00005](https://cloud.githubusercontent.com/assets/15571788/10976994/efcec6b2-83ee-11e5-950a-0015a9b59cde.jpg)

P.S. Is there a way to pass through the deadly red corridor without dying? I've tried many times with no successfull results and I didn't fint any gas masks around!

**Comment by FireWarp** [comment]
I actually thought that you had to run through the room, pick up the keys and go up the spiral staircase. I did it by bunnyhopping all the way and thought that it was an intended route. I'll post a vid soon cozi found a way to completely skip the crane puzzle and the red light corridor altogether.

As for the key visibility, I think that it is really unfair because all keys on furnace are literally invisible. I found the first key by mashing e on everything I see. The little glow for all intractable items is not enough for me to notice it.

**Comment by Oskutin** [comment]
Good suggestions.

Generally that trapdoor is just alternative shortcut, the more canon way is to power that laddle changer and descent to the lower level by jumping on it.

**Comment by Gheppio** [comment]
In that case, OK! I found the trapdoor way first and thought that it was the only one!
But in this case... better to keep it hidden!

**Comment by aleksijuvani** [comment]
> P.S. Is there a way to pass through the deadly red corridor without dying? I've tried many times with no successfull results and I didn't fint any gas masks around!

The one with the poisonous gas? There are spots with a bright white light around them. There's ventilation at those spots. You can rest there without taking damage and your health will regenerate in a few seconds.

**Comment by Oskutin** [comment]
2 and 3 done, the tracks now has visual linkage with switches.

**Comment by Oskutin** [comment]
Furnace electric switch room now has autosave.

**Comment by Gheppio** [comment]
Great!

**Comment by Oskutin** [comment]
Highlighted buttons.
