### ISSUE TITLE
Weird visual bug with flashlight illumination

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#128]
Screenshots are taken in furnace but this glitch happened also in other maps

Normal
![2015-11-05_00001](https://cloud.githubusercontent.com/assets/15571788/10977496/ac355f26-83f1-11e5-9e4f-d140af1061d1.jpg)

Glitched
![2015-11-05_00002](https://cloud.githubusercontent.com/assets/15571788/10977498/affcda4e-83f1-11e5-8db6-571058bf1195.jpg)

**Comment by aleksijuvani** [comment]
Same issue as #58.
