### ISSUE TITLE
Hide viewmodels when you zoom in (Mouse3)

### ISSUE THREAD

**Issue by Dmck2b** [loiste-interactive/infra-issues#131]
Due to how source handles the FOV changes, viewmodels become a little weird when you zoom in (see video below, camera moves nearly out of frame to the top right). As a fix for this, viewmodels could be hidden while zooming in (r_drawviewmodels 0).

https://youtu.be/ACoNxEMrZgU

**Comment by aleksijuvani** [comment]
This only seems to happen with FOVs higher than 108. Fixed in the next update.
