### ISSUE TITLE
Getting stuck inside of an elevator

### ISSUE THREAD

**Issue by FireWarp** [loiste-interactive/infra-issues#133]
https://youtu.be/5FkkvL9uxWs
reserve1

**Comment by aleksijuvani** [comment]
Judging from the visible trigger brushes, it looks like you've loaded a saved game from a previous version of the beta? The saved games aren't backwards compatible. Or is this a demo recording? I'm fairly sure that this specific issue was fixed in the last update.

**Comment by aleksijuvani** [comment]
Oh, guess not. I was just able to reproduce the issue.

**Comment by Oskutin** [comment]
Fixed
