### ISSUE TITLE
Incorrect vertex lighting on some props in the cabin

### ISSUE THREAD

**Issue by FireWarp** [loiste-interactive/infra-issues#135]
This chair is not the only prop that has odd lighting but all the props in the cabin.(disable vtx lighting on them?)
![2015-11-04_00001](https://cloud.githubusercontent.com/assets/8556074/11006322/4028d8e2-84d4-11e5-8541-74fdcbaf1502.jpg)
reserve1

**Comment by Oskutin** [comment]
Fix'd
