### ISSUE TITLE
tower: outside roof does not correspond with the inside

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#137]
I know that this isn't a priority 1 issue but I usually pay attention to these type of details
Inside [furnace, damaged]
![2015-11-05_00010](https://cloud.githubusercontent.com/assets/15571788/11006184/a32a1ada-84c2-11e5-82e6-dea16a94302b.jpg)
Outside [tower, no damage]
![screenshot_20151105201042](https://cloud.githubusercontent.com/assets/15571788/11006270/354421ae-84c3-11e5-9799-dd12786f2568.png)

**Comment by Oskutin** [comment]
Fixed
