### ISSUE TITLE
reserve1: cars with no texture on the bridge!

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#138]
![2015-11-06_00004](https://cloud.githubusercontent.com/assets/15571788/11007156/5592d018-84c8-11e5-9094-c7711f8cf4dc.jpg)
![2015-11-06_00003](https://cloud.githubusercontent.com/assets/15571788/11007160/61e762de-84c8-11e5-8515-8df586e7259d.jpg)
![2015-11-06_00001](https://cloud.githubusercontent.com/assets/15571788/11007162/628ce09c-84c8-11e5-81c5-8aa92249df4a.jpg)

**Comment by Yuccaa** [comment]
Fixed.
