### ISSUE TITLE
tunnel3: stuck in the broken tunnel

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#144]
It happened only once but I got stuck in the position of the screenshot, the player was absolutely immovable (traslation, not rotation) and I had to restart the game
![2015-11-07_00006](https://cloud.githubusercontent.com/assets/15571788/11016613/c98f006c-8587-11e5-8eb0-b1f5fb2f7c92.jpg)

**Comment by FireWarp** [comment]
You can still load autosaves by typing load aoutosave in console.

**Comment by Gheppio** [comment]
Thanks!

**Comment by Zuntti** [comment]
Fixed.
