### ISSUE TITLE
Furnace crane puzzle skip

### ISSUE THREAD

**Issue by Wingedturtle** [loiste-interactive/infra-issues#146]
It's possible to skip the crane puzzle through some creative jumping on the collapsed walkway.
You can see it in my video at about 6:30. 
https://www.youtube.com/watch?v=gD7beudprHg

**Comment by FireWarp** [comment]
This is not the only way to skip the crane puzzle ;)

**Comment by Oskutin** [comment]
That is already fixed.
 The other way could be "legit".
