### ISSUE TITLE
watertreatment: little missing texture on the ground!

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#148]
I found that there is a little object on the ground with no texture in the poisoned room of the watertreatment map.

![2015-11-07_00007](https://cloud.githubusercontent.com/assets/15571788/11016915/341bcf08-858f-11e5-895a-434876b5a41b.jpg)

A larger view:
![screenshot_20151107204006](https://cloud.githubusercontent.com/assets/15571788/11016938/cae3a3a2-858f-11e5-9543-5f89ba54b67f.jpg)

**Comment by FireWarp** [comment]
too bad watertreatment is currently unplayable for me.

**Comment by Gheppio** [comment]
So sorry! Why that specific map?

**Comment by FireWarp** [comment]
10 fps even on lowest settings, some areas though have quite acceptable framerate, but red and blue keycard labs both indoors and outdoors lag the most.

**Comment by Oskutin** [comment]
There seems to be missing decal texture.

Also this map is currently under heavy optimization process.

**Comment by Yuccaa** [comment]
Original bug fixed.
