### ISSUE TITLE
Controls need an option to restore defaults

### ISSUE THREAD

**Issue by paavohuhtala** [loiste-interactive/infra-issues#15]
![2015-11-01_00001](https://cloud.githubusercontent.com/assets/803180/10866774/30bde7e2-8049-11e5-9f7a-123aa4c93f54.jpg)

Might be caused by having had an earlier version of INFRA installed. The game should either reset controls on the very first start, or at least have an option for resetting to default bindings.

**Comment by aleksijuvani** [comment]
Added an option for resetting to default controls in the next update.
