### ISSUE TITLE
Player getting stuck on the pipes and visual errors in furnace

### ISSUE THREAD

**Issue by Yuccaa** [loiste-interactive/infra-issues#150]
Player can get stuck on this corner when walking on the pipes at the start of the level:

![infra_c4_m2_furnace0001](https://cloud.githubusercontent.com/assets/5402153/11023287/526292be-867d-11e5-9f38-3839830d4486.jpg)

The pipes are also misaligned on the right when they hit the wall (in the darkness on this image).

Then you can see the skybox too clearly when climbing on top of these lamp posts:

![infra_c4_m2_furnace0002](https://cloud.githubusercontent.com/assets/5402153/11023338/97d9e526-867e-11e5-946b-01b2ff35a555.jpg)

**Comment by Oskutin** [comment]
Fixed
