### ISSUE TITLE
furnace : Invisible walls, "stuck" and puzzle skip

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#155]
While running around dodging flames and trying not to die, I stumbled upon these invisible walls on all floors of the huge furnace thingie. There are barrels all around to indicate a blocked path and I think putting some of those here (or simply locked gates) would make things clearer.

![2015-11-09_00003](https://cloud.githubusercontent.com/assets/15633807/11046408/90cb0238-872d-11e5-9483-ac100790c5e4.jpg)

Also, while running on those catwalks trying to find alternate paths, I tried to jump over a gap and ended on the catwalk leading to the exit elevator. The elevator was still closed, the other end of the path was blocked by barrels and there were no other way down. I was stuck.

Missed that jump : 
![2015-11-09_00004](https://cloud.githubusercontent.com/assets/15633807/11046443/ca520e98-872d-11e5-9707-0203fdfe3425.jpg)

You can see the Emergency Stop control room there : 
![2015-11-09_00005](https://cloud.githubusercontent.com/assets/15633807/11046462/e9bb69f0-872d-11e5-98d6-e512d5ad0da5.jpg)

And after a while, the elevator unlocked on his own, without requiring me to shut down everything. You can still see the flames you normally have to go through on the left. (was this intentional for stuck players like me ? I think putting flame pipes under this catwalk to deter players from going this way without first shutting everything down would be better) 
![2015-11-09_00006](https://cloud.githubusercontent.com/assets/15633807/11046484/094d830c-872e-11e5-9297-8d790c8518cf.jpg)

**Comment by Oskutin** [comment]
This has been already fixed in next update.
