### ISSUE TITLE
feedback/graphical bug, furnace/tower : No signal ? Raveclub SBS ?

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#156]
Again, some very minor details that might not even be errors...Sorry for being so finicky. :P 

When the player climbs the stairs leading to the "Raveclub SBS" (which seems to be legal since you can't take "corruption pictures" of it ;P) he mentions having no signal while being within sight of the furnace tower which has telecommunications antennas on top of it. Well, at least I think those are tel-com antennas...
![2015-11-09_00010](https://cloud.githubusercontent.com/assets/15633807/11046908/17657330-8730-11e5-8c05-d9c0daaeaeaa.jpg)
![2015-11-09_00007](https://cloud.githubusercontent.com/assets/15633807/11046930/40a3eba0-8730-11e5-9c1a-81f44659b4be.jpg)

First case scenario : Those are linked to the tower's power supply which explains why they aren't working. But since those brand-new-looking antennas are sitting atop an old rusty tower, it's safe to assume those were installed long after Stalburg Steel was closed. (The place has been abandoned for so long there are 2-meters high bushes growing out of the ladles :P)

Second case scenario : Our mysterious barbecue man (or someone else) destroyed the power boxes next to said antennas in a drunken fit of rage. The cables on the floor seem to be a good indication. Since the telcom company didn't send anyone yet to fix the problem then it must have happened recently. In which case I think adding a few electric sparks effects and a "corruption photo" spot would be appropriate :)

Third case scenario : These antennas work just fine but they were struck by lighting which tripped their circuit breaker and the telecom company has yet to send someone to flip the switch back. In which case you could replace those non-interactive power boxes by some other openable cabinet, housing a turned off power switch.

![2015-11-09_00011](https://cloud.githubusercontent.com/assets/15633807/11047387/6bf22054-8732-11e5-896a-3bfcd04c5ea9.jpg)

Finally, this object was first missing its texture but now it seems its diffuse and bumpmap have been inverted
![2015-11-09_00012](https://cloud.githubusercontent.com/assets/15633807/11047568/7f95df1e-8733-11e5-95de-92819ee448e2.jpg)
Similarly, it would seem the reflection map of the barbecue will have to be regenerated to take the new texture into account
![2015-11-09_00014](https://cloud.githubusercontent.com/assets/15633807/11048229/e359a9a6-8736-11e5-89fe-1916958048e5.jpg)

**Comment by Oskutin** [comment]
Scenario 1 and 2 explains.
Up to you :P 

That missing newspaper is known issue, the content for it is stil wip.

**Comment by aleksijuvani** [comment]
It might be worth changing the monologue to mention how weird it is that there is no signal even though there are telecommunication antennas nearby. The player could also use some additional monologue at the top of the tower.
