### ISSUE TITLE
puzzle feedback reserve1 - reserve3, tunnel 1

### ISSUE THREAD

**Issue by evilhackman** [loiste-interactive/infra-issues#158]
- I think the hint regarding color lines make this puzzle too easy. (reserve1)
![2015-11-08_00030](https://cloud.githubusercontent.com/assets/15716642/11096809/375aa350-889c-11e5-8f33-59cad9e1893b.jpg)
- same here (tunnel 1): I think just writing the "door code" on the note sheet would be sufficient. The fuse box thingy is right next to the door, so it should be obvious to everyone where to unlock it.
Note could alternatively say "Emergency door code: A2, B1, C3"
![2015-11-08_00031](https://cloud.githubusercontent.com/assets/15716642/11096910/b907d1ca-889c-11e5-98e1-6b6c98236cae.jpg)

**Comment by Oskutin** [comment]
Reserve3 puzzle is now bit harder.
