### ISSUE TITLE
lighting glitch in "tunnel 1" , tunnel 1 feedback

### ISSUE THREAD

**Issue by evilhackman** [loiste-interactive/infra-issues#161]
the red light from next room shines through solid wall in the A2 flood door area 
![2015-11-11_00001](https://cloud.githubusercontent.com/assets/15716642/11106899/1f6aca62-88d9-11e5-8f02-01aafeb0ac7f.jpg)

- I think the flood doors should have labels/inscription on the wall next to them. Often you activate a certain door or crank a valve but you can't really tell where the specific door is

- there's this room "on the river" with the 2 bridges that can be lowered or raised on either side. a note inside the room says "don't climb on the roof"... I was stuck in that room, the second door simply wouldn't open. Is this on purpose or did i miss something?

**Comment by aleksijuvani** [comment]
> there's this room "on the river" with the 2 bridges that can be lowered or raised on either side. a note inside the room says "don't climb on the roof"... I was stuck in that room, the second door simply wouldn't open. Is this on purpose or did i miss something?

This is on purpose. You're supposed to climb on the roof by using the bridge as a "springboard". It's kind of subtle, but I like it.

**Comment by evilhackman** [comment]
oh yea, sounds exciting. Tbh in this game I'm extra careful since you die already when you get your feet in a puddle already, so this is far beyond what I'd dare to try normally ;-)

**Comment by Zuntti** [comment]
Fixed.
