### ISSUE TITLE
tunnel2: inconsistency in run of pipes

### ISSUE THREAD

**Issue by evilhackman** [loiste-interactive/infra-issues#162]
- the blue and red pipes run into a wall/building, but looking from inside the building there are no pipes coming through. Thus, the pipes end in a wall :p 
from outside:
![2015-11-11_00008](https://cloud.githubusercontent.com/assets/15716642/11107116/cf5203d6-88da-11e5-8e75-20aa2dc10ea0.jpg)
from inside:
![2015-11-11_00009](https://cloud.githubusercontent.com/assets/15716642/11107119/d47d0b08-88da-11e5-9021-e6e5c4b6a9df.jpg)

**Comment by Oskutin** [comment]
Added small room/area in that wall where you can see the pipes going down.
