### ISSUE TITLE
blackscreen while transitioning from tunnel2 -> tunnel 3

### ISSUE THREAD

**Issue by evilhackman** [loiste-interactive/infra-issues#163]
- I can reproduce this every time: when exiting tunnel2, tunnel3 starts loading (loading symbol shows up) but then the screen stays dark. I waited about a minute. Tunnel3 loads fine from main menu

**Comment by Oskutin** [comment]
Similar than  #75 ?

**Comment by evilhackman** [comment]
probably, but even waiting for a while did not help.
If you need a logfile or any other detail let me know

**Comment by aleksijuvani** [comment]
Could you launch the game with `-condebug`, reproduce the issue and then paste the contents of `infra/console.log` here?

You can set the launch options by right-clicking INFRA on Steam, selecting "Properties" and then "Set Launch Options". You can find the INFRA folder by selecting "Properties", "Local Files" and "Browse Local Files".

**Comment by evilhackman** [comment]
Here you go
https://www.dropbox.com/s/qdykifak5gaayr4/console.log?dl=0

By the way. Whic is the launch option/console command to show debug info like seen on some screenshots (map name, coordinates)?

**Comment by aleksijuvani** [comment]
> Here you go
https://www.dropbox.com/s/qdykifak5gaayr4/console.log?dl=0

Thanks!

> By the way. Whic is the launch option/console command to show debug info like seen on some screenshots (map name, coordinates)?

I think you're looking for `cl_showfps 1` and `cl_showpos 1`.
