### ISSUE TITLE
tunnel3 raft ride glitches

### ISSUE THREAD

**Issue by evilhackman** [loiste-interactive/infra-issues#164]
- When player dies on the raft and resumes from last checkpoint, there is no music playing anymore. Actually, I like this section better without the cheesy music. The background noises are nice.

- there are some low celings in the late section of the raft ride, which the player can simply pass through, incl. clipping into wall. Not sure if intentional or if player was actually supposed to need to duck. There is no collision.
https://www.dropbox.com/s/pa5xb6wl3o6t9g0/infra_2015_11_11_22_26_33_123.avi?dl=0

- lighting glitch when falling into water 
https://www.dropbox.com/s/dmuvfdb99w4hxa1/infra_2015_11_11_22_24_10_503.avi?dl=0

**Comment by Oskutin** [comment]
These all are fixed in next update.
