### ISSUE TITLE
[minor] valve shadow glitch (tunnel 3)

### ISSUE THREAD

**Issue by evilhackman** [loiste-interactive/infra-issues#165]
Valves have very weird shadow behaviour when illuminated with the flashlight. They do not cast shadows onto walls, but rather their boundary box or something(?).
https://www.dropbox.com/s/gew45nbhsksxat5/infra_2015_11_11_21_41_07_852.avi?dl=0

Noticed this in tunnel3, but might apply to all similar valves

**Comment by Oskutin** [comment]
I quickly tested and, It's just optical illusion due flashlights proximity and parallelity to eyes. For similar illusion of nearby ghost object happens everywhere with flashlight.  Env_projectedtextures entities in world doesn't cause similar effect, unless you look from right next to it.

**Comment by aleksijuvani** [comment]
Just to note, this only seems to happen on the lowest graphics settings.

**Comment by evilhackman** [comment]
Not only low
![2015-11-13_00001](https://cloud.githubusercontent.com/assets/15716642/11147471/6de9acba-8a16-11e5-8bde-9dc07da179cf.jpg)
