### ISSUE TITLE
tunnel4 glitches

### ISSUE THREAD

**Issue by evilhackman** [loiste-interactive/infra-issues#166]
- z fighting of surfaces
https://www.dropbox.com/s/iydfo8ow2hvwxbr/infra_2015_11_12_00_01_34_176.avi?dl=0

- missing texture:
![2015-11-12_00001](https://cloud.githubusercontent.com/assets/15716642/11107344/53b31424-88dd-11e5-9e20-b7297f6132d5.jpg)

- in the crawl section (shut down maintenance tunnel), the pipes have too much collision on the thick parts, making it hard to move. 
got stuck for a second here:
https://www.dropbox.com/s/07yl5qd717h62s0/infra_2015_11_11_23_54_09_035.avi?dl=0
very hard to move/advance here:
https://www.dropbox.com/s/yslujps7jqhz0h0/infra_2015_11_11_23_54_54_200.avi?dl=0

**Comment by Oskutin** [comment]
These are already fixed.
