### ISSUE TITLE
reserve2: door inside the wall

### ISSUE THREAD

**Issue by Starscre4M** [loiste-interactive/infra-issues#168]
On reserve2 there is this door where a chair is supposedly holding the door opened, but if you try to close it, it goes inside of the wall.

![2015-11-11_00007](https://cloud.githubusercontent.com/assets/5266547/11139534/ec0b698a-89b7-11e5-8f9f-3fdbb4f775d0.jpg)

**Comment by Oskutin** [comment]
And fixed too.
