### ISSUE TITLE
reserve2: stuck places

### ISSUE THREAD

**Issue by Starscre4M** [loiste-interactive/infra-issues#169]
If you try to crouch and go to that "passage" you get stuck under that rock and can't move at all.
![2015-11-11_00013](https://cloud.githubusercontent.com/assets/5266547/11139681/9922b6a4-89b9-11e5-8900-a9a2e21ce293.jpg)
![2015-11-11_00014](https://cloud.githubusercontent.com/assets/5266547/11139687/a47a0ae8-89b9-11e5-9cc2-e3158497870e.jpg)

You can also easily get stuck if walk between these two rocks:
![2015-11-11_00023](https://cloud.githubusercontent.com/assets/5266547/11139696/caddd8cc-89b9-11e5-8f1a-0dcffc14518b.jpg)
![2015-11-11_00022](https://cloud.githubusercontent.com/assets/5266547/11139697/d0dfbbc8-89b9-11e5-97a1-4c6888c5fcb9.jpg)

Also a minor map leak:
![2015-11-11_00011](https://cloud.githubusercontent.com/assets/5266547/11139716/fae1a3e6-89b9-11e5-8921-6d764076b3ac.jpg)
to better find it, here it is what I see if I turn around:
![2015-11-11_00010](https://cloud.githubusercontent.com/assets/5266547/11139723/0664e980-89ba-11e5-8299-6e6b07a6ddc0.jpg)

**Comment by Oskutin** [comment]
All fixed.
