### ISSUE TITLE
furnace - feedback and bugs

### ISSUE THREAD

**Issue by evilhackman** [loiste-interactive/infra-issues#171]
- Overall, this is the worst map played so far. "Probably" I suck at figuring out puzzles, but this map does overall not give good hints and is kinda too big, with too long distances to walk and too many paths closed by obstacles (why?). E.g. in the big production hall with the crane, why is the bridge next to the crane blocked with obstacles that can only be traversed from one side.
![2015-11-13_00010](https://cloud.githubusercontent.com/assets/15716642/11160715/f63afb12-8a6d-11e5-82cc-1026b41c8d23.jpg)
As a player, I'm never sure if maybe I forgot something, so incasse I do wanna go back (to the power switch area) the game forces me to walk upstairs again and balance on the pipes and walk all the way around or walk downstairs through the terrible poison gas room..... And incase a player didn't figure out yet how to survive in the poison gas room (like I did) this makes it even worse

- The hint note on the mattress can only be read with flashlight, which is bad incase player has no batteries 
![2015-11-13_00013](https://cloud.githubusercontent.com/assets/15716642/11160627/8586881a-8a6c-11e5-93ea-fa97878ac63e.jpg)

- the poison gas room is not fun and hard to figure out! Took me about 15 deaths in there till I figured out that I could breathe at the pillars. This isn't obvious enough. Maybe you need a steam effect like fresh air streaming in. I tried multiple times to directly run through the room, thinking it might be a timer thing.... Frustrating area. The fact that the checkpoint is IN the poison area, with closed door behind, adds to the frustration.
![2015-11-13_00005](https://cloud.githubusercontent.com/assets/15716642/11160659/13de6d08-8a6d-11e5-9883-bd6b311d3214.jpg)

- visual bug: after dying in the Rave Club area, and reloading checkpoint, the graffiti texture was only half painted. Could reproduce every time. Maybe this affects more decals in the area?
![2015-11-13_00006](https://cloud.githubusercontent.com/assets/15716642/11160669/2d27d772-8a6d-11e5-89ec-c9deee27b73e.jpg)

- sometimes on this pipe I was super slow (like a snail) after ducking under the first obstacle. The super slow speed would not end regardless of which direction I turned. I could not even forcefully jump down. Had to snailpace my way up until the end of the pipe. Hard to reproduce
![2015-11-13_00008](https://cloud.githubusercontent.com/assets/15716642/11160683/66487cdc-8a6d-11e5-848f-e714382b0968.jpg)

- you can easily get stuck in the gap next to the obstacles on the bridge right next to the crane
![2015-11-13_00009](https://cloud.githubusercontent.com/assets/15716642/11160698/d75d337c-8a6d-11e5-9808-5b88aeb1b243.jpg) 
right side in this here screenshot (but left side as well probably)
![2015-11-13_00011](https://cloud.githubusercontent.com/assets/15716642/11160700/de157f44-8a6d-11e5-9974-6e4f17e24082.jpg)

- you can get stuck here in the bend on the pipes below the Rave club 
![2015-11-13_00012](https://cloud.githubusercontent.com/assets/15716642/11160743/802f31ee-8a6e-11e5-94ae-037d50d669bd.jpg)

- the 2 trains had no interaction highlights, making it trial and error to figure out that they can be turned on by switch. It was reeally finicky to get the engines running (button mashing helped) and for several minutes I was running back and forth into the control room thinking I maybe might have activated the wrong tracks. Also, there should be a label somewhere indicating that these are in fact tracks 1 and 2. Where are tracks 3 and 4 btw.? It doesn't make sense! If they are on the opposite side of the room, then there needs to be another control room/switch for them over there for safety reasons and not on this side of the room
![2015-11-14_00007](https://cloud.githubusercontent.com/assets/15716642/11160796/50cf8af6-8a6f-11e5-9814-2f01eee7006b.jpg)

- the fire burst in the control room sucks. If you walk in the wrong direction (out the entry door)  you will die and have to restart. At least allow the player to duck below those 2 fire burst in the control room, so he can avoid death in that room/area. Otherwise, it's just learn-by-retry gameplay, which is bad game design.
![2015-11-14_00008](https://cloud.githubusercontent.com/assets/15716642/11160803/6f216b5a-8a6f-11e5-8358-278a9887df94.jpg)

- Still fire escape section: these paths are blocked by invisible walls, confusing the player becasue he gets the impression he might have an alternative path, which is not true, only then to be blocked by an invisible wall. Place visible obstacles instead maybe? 
![2015-11-14_00010](https://cloud.githubusercontent.com/assets/15716642/11160835/1614b4b2-8a70-11e5-8b9b-eb4a39fd2a08.jpg)
IIrc there is another identical invisble wall on the floor right below

- the section after ladle ride is unnecessarily complex. I was walking around for 10 minutes in the very dark floor level area and on all the platforms, until I finally found that one door that leads to the next area. The wooden plank leading to that one ladder on the wall next to the railing adds to the confusion, esp. sicnce you can climb the ladder but the roof-door will not open. Don't give the player a bearable crate in that area! (He will think that he needs it) I was actually carryng it around, trying out many of the other ladders as well since there are visible doors at the top of them. Don't need to menion it was in vein and I died several times. Meh!
I would suggest you block most of the paths in that area, the level is long enough without wandering around in that area.

**Comment by Oskutin** [comment]
Majority of these problems have been fixed already.

**Comment by evilhackman** [comment]
do you want me to move the unresolved bugs into seperate threads and just leave this as a feddback thread?

**Comment by Oskutin** [comment]
Sure that would be good, closing this issue now.
