### ISSUE TITLE
December 2nd update bugs compilation

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#179]
reserve1 : 
![2015-12-02_00001](https://cloud.githubusercontent.com/assets/15633807/11550001/ae731708-996b-11e5-9fcd-2bcb61685009.jpg)
Car side-view mirror through the car windows.

reserve2 : 
![2015-12-02_00002](https://cloud.githubusercontent.com/assets/15633807/11550039/f3c163e6-996b-11e5-9028-72c3438b39ba.jpg)
New broken elevator at the beginning doesn't count as photographable spot.

tunnel1 : 
![2015-12-02_00004](https://cloud.githubusercontent.com/assets/15633807/11550054/1b7163f0-996c-11e5-936c-614d7db900e4.jpg)
![2015-12-02_00003](https://cloud.githubusercontent.com/assets/15633807/11550055/1b8142d4-996c-11e5-8378-a66481f08df3.jpg)

The labels on the plan in the pipe room and the labels on the actual pipes are inverted (A1 and 1A, A2 and 2A,...)

tunnel2 : 
![2015-12-02_00005](https://cloud.githubusercontent.com/assets/15633807/11550071/4f9e102e-996c-11e5-8ecf-894bb31292a6.jpg)

When trying to enable Remote Blue Line, the error message doesn't mention the right pumps.

![2015-12-02_00008](https://cloud.githubusercontent.com/assets/15633807/11550133/eacb0688-996c-11e5-910e-d26164972f46.jpg)
Was able to turn on Valve Blue Line with all the pumps turned off.

tunnel4 : 
![2015-12-02_00014](https://cloud.githubusercontent.com/assets/15633807/11550183/75f345fe-996d-11e5-8da8-aade17384f4f.jpg)
If you stand near the end of the raft when reaching this point, you will stop being constrained to the raft, said raft will continue forward and you will fall and drown.

![2015-12-02_00015](https://cloud.githubusercontent.com/assets/15633807/11550216/b8f38bb6-996d-11e5-9a95-c515f4cca85b.jpg)
![2015-12-02_00018](https://cloud.githubusercontent.com/assets/15633807/11550217/b8f4ed94-996d-11e5-9238-434df686b258.jpg)
Broken catwalks don't count as photographable spots.

![2015-12-02_00017](https://cloud.githubusercontent.com/assets/15633807/11550228/d06edb1a-996d-11e5-814e-4078babcb799.jpg)
Not a bug, but what is the purpose of this empty box (and also the entire collapsed, covered-in-vegetation section it's in) ?

![2015-12-02_00020](https://cloud.githubusercontent.com/assets/15633807/11550285/8e313634-996e-11e5-90dc-7d06844d6415.jpg)
Got stuck in the electrified corridor. Put a crate on the bigger crate in front of the circuit-breaker, tried to get back into the crawlspace where I came from and got stuck between the ceiling pipe and the crate.

![2015-12-02_00021](https://cloud.githubusercontent.com/assets/15633807/11550302/ca5824c4-996e-11e5-959f-d041bc8a929f.jpg)
Was able to open the dynamite storage door with the current turned off. I plugged the fuse, turned the circuit-breaker on, then off then walked to the door and opened it. If I close it and try to open it again, it doesn't work and I have to repeat the maneuver.

tower:

![2015-12-02_00022](https://cloud.githubusercontent.com/assets/15633807/11550309/fa941db4-996e-11e5-863f-bb9fe7cf4713.jpg)
I think this paper note is in the wrong place. (textures also still missing)

Also the phone booth doesn't seems to work anymore. The player just picks up the phone without letting me dialing anything. I like this little Easter Egg :/

watertreatment : 

![2015-12-02_00023](https://cloud.githubusercontent.com/assets/15633807/11550321/30d9a984-996f-11e5-96d4-8ea374d062e5.jpg)
This door is still giving me sass, apparently ;P It won't close despite my best efforts.

![2015-12-02_00024](https://cloud.githubusercontent.com/assets/15633807/11550332/4c8b1f14-996f-11e5-995f-754993afc3d6.jpg)
The door-lock leading to the new blower building stays open after activating it.

I like what you did with the place, by the way ^_^. It's still lagging though. Especially when exiting the tunnel. I'm not getting any decal overflow though, just plain ol', error-less framerate drop.

Also, the player monologues are a really, really nice addition !

Finally, I think a few of the skyboxes, especially reserve2 and water-treatment could use a little less "white". When standing at the observation tower in front of the dam or at the tunnel exit in front of the treatment plant, it looks especially jarring with all that white. I don't recall it being a problem on top of the tower though...

Anyway, thanks again for the update and good luck with the next bit of the project !

**Comment by N-G-Neer** [comment]
Also, at the very start of reserve2, I somehow spawned under the elevator cabin (or at least I clipped through it) and I crashed at the bottom of the elevator shaft. As the game reloads, I keep falling through and dying.

**Comment by N-G-Neer** [comment]
Holy hardhat ! I just discovered the...hallway...level. What's up with that ? O.o Is it gonna be in the final version ?

**Comment by Oskutin** [comment]
That easter egg level? Should it be harder to find?

**Comment by N-G-Neer** [comment]
No, it should be impossible to find, remove it (just kidding) ! Damn that was scary xD I'm such a wuss I didn't go all the way. I no-clipped to see what was ahead.

I swear, if you guys tell they put green mushrooms into the Osmo Olut beer because it was addicting, but it also happen to have the undiscovered side-effect of slowly transform people into blood-thirsty ghouls, I am OUT of here. I can deal with failing elevators, flame-throwing pipes, collapsing ceilings and out-houses in drinking water tunnels, but I cannot deal with zombies, ghouls, Mr. Mushroom Guy or whatever was in that tunnel. I've seen enough Outlast/Dead Space to know where this is going D:

(Also found the other, beer-related easter egg before the raft section. This I like :P)

**Comment by Zuntti** [comment]
Fixed tunnel1 and tunnel4 bugs.

**Comment by Zuntti** [comment]
Fixed tunnel2.

**Comment by Zuntti** [comment]
Added camera target to reserve2 elevator.

**Comment by Zuntti** [comment]
Fixed watertreatment.

**Comment by Oskutin** [comment]
Tower note is in #207. Car model from the Reserve1 has been changed.
Closing this issue as majority of the problems are fixed for purpose of keeping the board clean.
