### ISSUE TITLE
Problems with Shader Model 3 error message

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#180]
I had the issue #62, that was solved disabling the secure boot so that the game wasn't forced to use integrated graphic which doesn't support Shader Model 3.
After the December 2nd update, when I try to run the game I somehow get the error message that suggest me to disable the secure boot and the program is forced to stop.
Before the update the game ran fine, I also checked the BIOS again and the secure boot is still disabled.
I suggest that this message should eventually pop up **without** interrupting the execution of the program, even because at the moment I can't  see any of the changes in the new update!
![screenshot_20151205094721](https://cloud.githubusercontent.com/assets/15571788/11606970/49ab891a-9b35-11e5-95fc-3b5d33e3aa5e.png)

**Comment by aleksijuvani** [comment]
That's weird. We had a similar issue with one of the computers at our office for apparently no reason. I guess I'll just get rid of the error message.

**Comment by aleksijuvani** [comment]
I'll try to push out an update for this later today.

**Comment by aleksijuvani** [comment]
Should be live on Steam now.

**Comment by Gheppio** [comment]
I confirm that now it works fine, I also see that a lo of things changed!
