### ISSUE TITLE
Missing Texture on lamp

### ISSUE THREAD

**Issue by Nyraion** [loiste-interactive/infra-issues#186]
![2015-11-09_00002](https://cloud.githubusercontent.com/assets/15572801/11608676/84e38cae-9b70-11e5-8e26-36c338b7797e.jpg)
 Its in the later part of tunnel 14

**Comment by Oskutin** [comment]
For me that model has textures.
Do you have the most recent version of the game?
Did you visit this location during your gameplay from reserve2 level?: http://media.moddb.com/images/games/1/9/8084/2015-11-14_00002.jpg

**Comment by Nyraion** [comment]
No i have not  visited that location, I will check on the latest version.
