### ISSUE TITLE
No sound coming from tape player

### ISSUE THREAD

**Issue by Nyraion** [loiste-interactive/infra-issues#187]
![2015-11-09_00001](https://cloud.githubusercontent.com/assets/15572801/11608681/aa2eaade-9b70-11e5-8d0c-a9e0ad0562f0.jpg)

The tape player produces no sound, even when the machinery in the room is of
Map: tunnel 14

**Comment by aleksijuvani** [comment]
We haven't recorded the voice acting for this tape yet, but you should be able to see the draft of the monologue if you turn on subtitles.
