### ISSUE TITLE
Rubble on roof has no texture on bottom

### ISSUE THREAD

**Issue by Nyraion** [loiste-interactive/infra-issues#189]
![2015-11-05_00003](https://cloud.githubusercontent.com/assets/15572801/11608694/3f4a26e8-9b71-11e5-95a1-62497e5d42f2.jpg)
![2015-11-05_00002](https://cloud.githubusercontent.com/assets/15572801/11608695/40cc51f8-9b71-11e5-963d-a802c9832058.jpg)

It is missing a bottom
Map: tunnel 1

**Comment by Oskutin** [comment]
Actually the bottom is not missing a face, it just looks like that it is due having excatly same texture than the rest of the roof.
