### ISSUE TITLE
reserve2: wrong spawn point

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#191]
When i start reserve2 **from the end of reserve1** I start compenetrated in the elevator's platform, so I fall and die, the level reloads in an infinite loop.
This doesn't happen if I load reserve2 from the main menu

Looking up:
![2015-12-05_00002](https://cloud.githubusercontent.com/assets/15571788/11609045/0dcb478c-9b7b-11e5-8326-275a10f061a5.jpg)
Looking down:
![2015-12-05_00004](https://cloud.githubusercontent.com/assets/15571788/11609047/18f03f78-9b7b-11e5-870f-52a02aa288dd.jpg)

**Comment by Oskutin** [comment]
I didn't manage to reproduce this. Tried about 15 times being&jumping&crouching in different parts of the elevator.
Can you tell me how you managed to make this happen. In what part of the elevator you were and etc.?

**Comment by N-G-Neer** [comment]
It is a very difficult bug to reproduce, but I encountered it as well. You don't have to do anything in particular. Just play reserve1 as normal, plug in the fuses, turn the lever on and activate the elevator. (Maybe try turning the lever on and off a couple of times ?)

Maybe you should constrain the player to the elevator's cabin, at least for the first few meters (like in the raft section) ?

**Comment by Gheppio** [comment]
It has been really hard to reproduce it even for me, I did it only by repeating every single action and replaying the level several times trying to confine the bug.
Seems that the bug is linked somehow to the train, if I go through the woods, see the fallen tree (line of dialogue of the line still active), stop the train, and use fuses and the elevator than the bug should appear

**Comment by Gheppio** [comment]
UPDATE: Seems that the train isn't responsible anymore for the bug, not alone at least.
I played reserve1 around 25 times and this bug happened 3 times, 
I wonder if it isn't a random event

**Comment by Oskutin** [comment]
Added some player clips that player can't touch the elevator itself before level change.

**Comment by Oskutin** [comment]
Closing this issue.
