### ISSUE TITLE
tunnel2: is this right?

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#193]
![2015-12-05_00013](https://cloud.githubusercontent.com/assets/15571788/11610442/735e7af6-9ba3-11e5-86a3-f5ffe5415b94.jpg)
In the tunnel2 map I emptied al the pools (and got the key), after that I tried successfully to turn on pump 4, than I went to the control room and opened the blue pipe:
I saw that I was able to operationalize the entire plant with all the pools empty.
![screenshot_20151205230147](https://cloud.githubusercontent.com/assets/15571788/11610500/82b516f8-9ba4-11e5-8476-3b0c2a52b545.png)
Also, after that the valves of both the blue line pumps got blocked

**Comment by Gheppio** [comment]
Also, after you opened the enrtance of the orange pipe, you can still open the blue and red pipes from the control room!

**Comment by Zuntti** [comment]
Fixed.
