### ISSUE TITLE
watertreatment: missing textures on the bus on the street

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#197]
![2015-12-07_00006](https://cloud.githubusercontent.com/assets/15571788/11625791/e0c5ae62-9cdd-11e5-821d-9bfdf50db5b6.jpg)
![2015-12-07_00004](https://cloud.githubusercontent.com/assets/15571788/11625794/e5d939f0-9cdd-11e5-9a30-b2a0cf1a6961.jpg)

**Comment by Yuccaa** [comment]
Fixed.
