### ISSUE TITLE
Missing backface gate texture(again)

### ISSUE THREAD

**Issue by FireWarp** [loiste-interactive/infra-issues#198]
![2015-12-04_00003](https://cloud.githubusercontent.com/assets/8556074/11658379/5b52c994-9dd3-11e5-96c2-983552297253.jpg)

**Comment by Oskutin** [comment]
In that case the front has the same problem. May be caused that the model is too small to be used as staticprop, converted them into dynamic.

**Comment by Oskutin** [comment]
Okay, this works now, atleast for me.
