### ISSUE TITLE
Reserve 1 still has incorrectly lit objects

### ISSUE THREAD

**Issue by FireWarp** [loiste-interactive/infra-issues#200]
Such as this boat, for example.
![2015-12-04_00001](https://cloud.githubusercontent.com/assets/8556074/11658448/be53d8a8-9dd3-11e5-91d8-84eb4f0722dd.jpg)

**Comment by Oskutin** [comment]
Model lighting errors are super annoying to fix, very time consuming due compile times and always very uncertain if something works at all.

**Comment by FireWarp** [comment]
Console commands and hammers cordon tool make things like these 10 times easier.

Find a prop with incorrect lighting -> point at it, ent_setname name, ent_fire name setlightingorigin fuse_a_mdl -> if lighting is ok, find this fuse_a_mdl in hammer and make that name entity use fuses lightorigin.

If you hate waiting for compilation you can simply cordon the area you want to revisit, remove all game logic, and put bunch of lightorigin entities inside that cordon are and then switch lighting origin in game with the command above.

**Comment by Yuccaa** [comment]
Fixed hopefully all.
