### ISSUE TITLE
watertreatement: unreadable note (?)

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#203]
I don't know if it's only a white sheet, but it seems that it should be something written here
![2015-12-19_00008](https://cloud.githubusercontent.com/assets/15571788/11914159/6b4c7fd6-a678-11e5-9eb4-24cae5ad655f.jpg)
![2015-12-19_00009](https://cloud.githubusercontent.com/assets/15571788/11914160/6f0798ea-a678-11e5-945d-deeee2a9a606.jpg)

**Comment by Yuccaa** [comment]
There should be text, but it's not yet implemented.

**Comment by Oskutin** [comment]
Closed and moved to #207
