### ISSUE TITLE
sewer: Heavy lag when alarm is on

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#205]
When the alarm is active **and** I am in one of the three areas triggered by the sensors I experience lag

**Comment by Oskutin** [comment]
Can confirm, had massive lag at start of the level (with my slow laptop), but rest of the level was fine.

**Comment by aleksijuvani** [comment]
Yeah, I can confirm this. Looks like the alarms keep triggering the `vgui_screen` inputs over and over while they are on. Maybe this is the cause?

**Comment by Zuntti** [comment]
Fixed.
