### ISSUE TITLE
sewer: The poison valve does nothing

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#206]
No variables are set when I turn this valve; I'm not sure that this is intended
![2015-12-19_00017](https://cloud.githubusercontent.com/assets/15571788/11914205/e37bfd8c-a679-11e5-9286-7f07ba80a6b4.jpg)

**Comment by Oskutin** [comment]
This is for the alternative route.

**Comment by mpeltomaa** [comment]
Never got thru of this. Don't find alternative route or any main route which would work.

**Comment by Oskutin** [comment]
There's secret escape route in the WC.
Or you just have to turn the sensors off with code.

**Comment by mpeltomaa** [comment]
I made it thru. Problem was that it was quite hard to use tablet on that table nearby tv (Which contains code). I tried to jump around, walk and do everything but that tablet didn't highlight. Finally i managed highlight (and read it) from other side of table while i was jumping :D

**Comment by Gheppio** [comment]
OK, now I got how the normal and alternative routes work.
This caused further problems that are reported in #221
