### ISSUE TITLE
Untextured/missing documents, newspapers and notes

### ISSUE THREAD

**Issue by Oskutin** [loiste-interactive/infra-issues#207]
Opening this issue for untextured/missing readable story/puzzle related items.
Please report every issue related to this into this thread.

**Comment by Oskutin** [comment]
Watertreatment binder: https://cloud.githubusercontent.com/assets/15571788/11914159/6b4c7fd6-a678-11e5-9eb4-24cae5ad655f.jpg

**Comment by Oskutin** [comment]
Tower phone switchboard:
![toqwfa](https://cloud.githubusercontent.com/assets/5402150/11915288/3de48f18-a6a8-11e5-9e87-8de7fd465a12.jpg)

**Comment by N-G-Neer** [comment]
With the following video settings, mine actually had a wood texture, akin to the object shadow bug that was solved a while ago.
![2015-12-19_00051](https://cloud.githubusercontent.com/assets/15633807/11915349/9dff87a4-a6a3-11e5-88fd-c93a3172eedc.jpg)
![2015-12-19_00026](https://cloud.githubusercontent.com/assets/15633807/11915350/a109fe2a-a6a3-11e5-9a47-a67bd7a1927c.jpg)

**Comment by N-G-Neer** [comment]
Also, here are some place-holders I found : 
![2015-12-19_00009](https://cloud.githubusercontent.com/assets/15633807/11915357/ea592146-a6a3-11e5-8edf-55d1f2cf53e6.jpg)
This one was in the newly added forest guard cabin.

![2015-12-19_00014](https://cloud.githubusercontent.com/assets/15633807/11915369/1b1c90ba-a6a4-11e5-8a80-bd804c46fe6b.jpg)
This one was found in the stash on the other side of the river before tunnel1 entrance.

![2015-12-19_00024](https://cloud.githubusercontent.com/assets/15633807/11915372/4ec37c62-a6a4-11e5-8884-20a6ad707753.jpg)
This one is inside the first technical cabinet you come across while climbing the tower.

![2015-12-19_00025](https://cloud.githubusercontent.com/assets/15633807/11915375/73c27dce-a6a4-11e5-804c-b8a259b1b8f6.jpg)
This one is found inside the condemned office in the building after the tower, right next to a tape player.

**Comment by N-G-Neer** [comment]
This document in the old tunnel in the tunnel4 level lacks a close-up camera interaction
![2015-12-20_00006](https://cloud.githubusercontent.com/assets/15633807/11918611/d35533be-a738-11e5-90f4-3e110bd0f324.jpg)

**Comment by Oskutin** [comment]
Fixed the newspaper in tunnel4.

**Comment by aleksijuvani** [comment]
this thing in `office`

![](http://images.akamai.steamusercontent.com/ugc/362904549517847863/962722694A75EFB4C2D14D54DC9FE9032C710641/)
