### ISSUE TITLE
tunnel1 : Pipes in pipe room are missing their labels

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#208]
Unless this was intentional to force the player to identify them on a color basis (in which case I would suggest using a wider variety of colors on said pipes), the labels of the pipes are gone.
![2015-12-19_00050](https://cloud.githubusercontent.com/assets/15633807/11915381/fc56c8ca-a6a4-11e5-919a-e68fe1e2264e.jpg)
![2015-12-19_00047](https://cloud.githubusercontent.com/assets/15633807/11915382/033ee028-a6a5-11e5-9b6c-56631dd49fa6.jpg)

![2015-12-02_00004](https://cloud.githubusercontent.com/assets/15633807/11915388/1e014c48-a6a5-11e5-8c7c-b3f4c4da452c.jpg)
BEFORE
![2015-12-19_00048](https://cloud.githubusercontent.com/assets/15633807/11915383/036799a0-a6a5-11e5-83c5-ce2629a614b9.jpg)
AFTER

![2015-12-19_00049](https://cloud.githubusercontent.com/assets/15633807/11915384/036b840c-a6a5-11e5-9e61-bbbb225972f8.jpg)

**Comment by N-G-Neer** [comment]
Speaking of missing labels in tunnel1, the D4 door (that you can open remotely from the office) also has its label missing 
![2015-12-20_00005](https://cloud.githubusercontent.com/assets/15633807/11918263/f035a932-a729-11e5-806e-39b5659e8ad0.jpg)

**Comment by aleksijuvani** [comment]
This shouldn't be happening. The decals show up fine on my end. This could be a bug with how decals are handled when the player respawns, but I can't seem to reproduce the issue.

**Comment by N-G-Neer** [comment]
This has to do with the quality setting. I tried the high setting and the decals re-appeared. I don't know which exact setting is to blame though.

**Comment by N-G-Neer** [comment]
Found it ! Shader Quality seems to be the culprit.

**Comment by aleksijuvani** [comment]
Thanks for the help! I managed to reproduce the issue with shader detail set to low. Fixed in the next update.
