### ISSUE TITLE
sewers : Unable to reset sewage pump puzzle

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#209]
(Unless intentional) If you mess up with the knobs configuration and get an error, you wont be able to reset the machine (I guess this is what all those warnings are for)

![2015-12-19_00046](https://cloud.githubusercontent.com/assets/15633807/11915408/82b633ba-a6a5-11e5-8f3a-72d99915c1d0.jpg)

There is an unused circuit-breaker on the opposite wall, maybe it could be used to forcefully reset the machine ?

![2015-12-19_00052](https://cloud.githubusercontent.com/assets/15633807/11915429/1afd5fd6-a6a6-11e5-90b6-29f8a7ddd5bd.jpg)

Also, does this machine have any physical effect on the level ? (Like lowering the water level somewhere) Or is it purely a "spot repaired" thing ?

**Comment by Oskutin** [comment]
It's harder optional puzzle with just "spot repaired".
And the permanent breakdown is intentional.

**Comment by N-G-Neer** [comment]
Oh, okay then :)
