### ISSUE TITLE
sewer : Inconsistency with watertreatment

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#212]
When you're in watertreatment and about to transition to sewer, there is no dead fishes after the gate.
![2015-12-19_00057](https://cloud.githubusercontent.com/assets/15633807/11915511/ab05313c-a6a9-11e5-9367-0962a018d477.jpg)

However, once the sewer level has loaded, there is a group of dead fish after the gate.
![2015-12-19_00058](https://cloud.githubusercontent.com/assets/15633807/11915512/c49d7a0a-a6a9-11e5-8fb7-0b0f18c6e7e6.jpg)

**Comment by Zuntti** [comment]
Fixed.
