### ISSUE TITLE
Close-up camera is backwards on some documents

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#213]
When pressing E to get a closer view on some important documents, the camera will assume a weird angle. These two are the only ones with that problem I've noticed so far.

![2015-12-19_00021](https://cloud.githubusercontent.com/assets/15633807/11915515/05b7ca9a-a6aa-11e5-843d-044e69b67df9.jpg)
Warning on the mattress in furnace

![2015-12-19_00022](https://cloud.githubusercontent.com/assets/15633807/11915516/05ba62dc-a6aa-11e5-9951-1172b29a7e46.jpg)
Angry letter about the kerosene barrels in furnace.

**Comment by N-G-Neer** [comment]
Found another one with the stash before the water tunnel entrance.
![2015-12-20_00004](https://cloud.githubusercontent.com/assets/15633807/11918191/6037e086-a727-11e5-8552-91943c2124d9.jpg)

**Comment by aleksijuvani** [comment]
Fixed in the next update.
