### ISSUE TITLE
sewer: invisible matrix screens and chair

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#214]
Normal
![2015-12-19_00021](https://cloud.githubusercontent.com/assets/15571788/11915529/78e186b4-a6aa-11e5-9a8a-c992e2c31171.jpg)
But when I stand in the bathroom...
![2015-12-19_00020](https://cloud.githubusercontent.com/assets/15571788/11915531/89066d98-a6aa-11e5-92fd-4bb13f57fe55.jpg)

**Comment by Zuntti** [comment]
Fixed.
