### ISSUE TITLE
sewer : Getting trapped under the toilets

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#216]
What a terrible fate.

Disable all alarms, turn off the poison pipe, unlock all the unlockable doors (bathroom included), lock the bathroom door again, exit the building through the steam trap (that initially halted your progression) cross the canal on the planks, crawl inside the red tunnel, touch the valve to activate the steam, climb back up in the bathroom, the door is locked and you can't disable the steam.

One easy fix would be to make the bathroom door unlockable from the inside, or make the laptop in the bathroom usable.

**Comment by Zuntti** [comment]
Fixed.
