### ISSUE TITLE
watertreatment : Feedback - Resuming taking pictures

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#217]
When the player leaves the tower level he should say to himself something along the lines of "Alright, I'm out of Stalburg Steel. Time to start taking pictures again." or something similar.

**Comment by aleksijuvani** [comment]
Yeah, this is a good idea. We also need to separate the picture monologue from the signal monologue at the start of `furnace`, maybe move it to when he has cut off the lock from the door and entered the factory.

**Comment by N-G-Neer** [comment]
That seems like a good place to start the picture monologue indeed.

**Comment by aleksijuvani** [comment]
The picture dialogue at the start of `furnace` is now separate from the signal dialogue. Still need to add the dialogue to `tower`.

**Comment by aleksijuvani** [comment]
This has been implemented.
