### ISSUE TITLE
reserve1 : Car has missing/placeholder textures

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#218]
![2015-12-19_00003](https://cloud.githubusercontent.com/assets/15633807/11915763/b95f8672-a6b5-11e5-86bf-a3bb076f14c4.jpg)
![2015-12-19_00004](https://cloud.githubusercontent.com/assets/15633807/11915764/b9f477e6-a6b5-11e5-9e35-35e4dbb4a3aa.jpg)

"Regular : We make cars and we love white and wireframe." :P

**Comment by Yuccaa** [comment]
Fixed in the next update:

![infra_c1_m1_office0028](https://cloud.githubusercontent.com/assets/5402153/11932644/a1a8cde0-a7ff-11e5-910b-a4e36843c467.jpg)

**Comment by N-G-Neer** [comment]
Oooh, pretty !
