### ISSUE TITLE
reserve1 : Train signal bug

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#219]
If you spam the train signal when hearing the train approaching, the train will slow down, zip ahead, slow down again, in an erratic manner, maybe trying to replicate your sequence of spam.

In this picture, the train went past the signal but stopped before hitting the tree.

![2015-12-19_00006](https://cloud.githubusercontent.com/assets/15633807/11915770/35fbdd20-a6b6-11e5-8e54-cf99a541e1dc.jpg)

**Comment by Oskutin** [comment]
This is fixed in next update.
