### ISSUE TITLE
General Feedback and Questions (SPOILERS)

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#220]
In reserve1, the player should be able to take a picture of the defective fuse-box in the very first building. Something that makes sparks this big needs to be fixed.
![2015-12-19_00005](https://cloud.githubusercontent.com/assets/15633807/11915777/dbced932-a6b6-11e5-9d0d-3d75c35943a3.jpg)

I might have already said it, but some skyboxes could use a little less white in some places. (reserve2, tower, watertreatment...)
![2015-12-19_00007](https://cloud.githubusercontent.com/assets/15633807/11915814/04f0768a-a6b8-11e5-815e-4a4f5970516c.jpg)

This is a reaaally tight fit (tunnel3)
![2015-12-19_00016](https://cloud.githubusercontent.com/assets/15633807/11915894/56441864-a6ba-11e5-95ee-2338807a41c9.jpg)

The lower keys are a bit difficult to select when disabling the generator alarm in tunnel4.
![2015-12-19_00018](https://cloud.githubusercontent.com/assets/15633807/11915898/98b9a0c4-a6ba-11e5-843c-d60d30a59de9.jpg)

Is there a particular meaning behind this ?
![2015-12-19_00008](https://cloud.githubusercontent.com/assets/15633807/11915824/4c5c11dc-a6b8-11e5-89e0-eb8e07329de4.jpg)

What about the code on the corpse tarp ?
![2015-12-19_00013](https://cloud.githubusercontent.com/assets/15633807/11915825/62efd5b4-a6b8-11e5-98ab-3ea3ef0e93fe.jpg)

Is there a point in buying a soda in watertreatment ? I read the email about the lab guys being a bunch of drunks xD
![2015-12-19_00034](https://cloud.githubusercontent.com/assets/15633807/11915834/93225978-a6b8-11e5-8536-24038c5305fc.jpg)

And finally, is this friendly looking fellow that I "affectionately" dubbed "SCP-4027" the same person as the...resident of the "Hallway" ? And most importantly, do we get to encounter him again later in the game ? (please say no D:)
![2015-12-20_00003](https://cloud.githubusercontent.com/assets/15633807/11915841/c574a71e-a6b8-11e5-95ec-f69a2dc0b475.jpg)

**Comment by Yuccaa** [comment]
Those codes are part of some grant easter egg which is unknown to some of us devs even. Gotta figure it out once the game is released I suppose.

**Comment by Oskutin** [comment]
Related to some urban legend in Stalburg region. Nothing more.

**Comment by Oskutin** [comment]
The reserve1 fuses aren't relevant enough for city authority to care much about. It doesn't affect infrastructure and it's functionality at all.

**Comment by N-G-Neer** [comment]
> Related to some urban legend in Stalburg region. Nothing more.

If you're talking about the creepy painting, my heart-attack back in the 4027 Hallway level begs to differ xD

**Comment by N-G-Neer** [comment]
I also think it would be a good idea to allow the player to press R when he is holding neither the flashlight nor the camera to give him the number of battery packs he is currently carrying.

**Comment by aleksijuvani** [comment]
> I also think it would be a good idea to allow the player to press R when he is holding neither the flashlight nor the camera to give him the number of battery packs he is currently carrying.

Yeah, this is something that I've been meaning to implement for a while, but I'm still thinking about the best way to do it.

I suppose that the player could hold `R` with the camera equipped and have the player character say how many batteries he has for that. Same goes for the flashlight.

Something clever could be done if he has both equipped, but I'm kind of worried about how much work it would be to edit like literally a hundred audio files for that. It would probably be for the best if nothing happened when he has both (or neither) equipped.

**Comment by N-G-Neer** [comment]
>Something clever could be done if he has both equipped, but I'm kind of worried about how much work it would be to edit like literally a hundred audio files for that. It would probably be for the best if nothing happened when he has both (or neither) equipped.

Ah, yes. I forget the game is supposed to be fully voiced in the end ^^. Speaking of which I think the only line of dialog I've heard so far was a confused "What the hell ?" when the crane drops the barrel in the forklift puzzle.

**Comment by Yuccaa** [comment]
>Ah, yes. I forget the game is supposed to be fully voiced in the end ^^. Speaking of which I think the only line of dialog I've heard so far was a confused "What the hell ?" when the crane drops the barrel in the forklift puzzle.

Oh that test sound was left there? That definitely won't be the final voice of the player.

**Comment by Yuccaa** [comment]
The sky is less white now.
