### ISSUE TITLE
sewer: suggestion and possible bug about the poison pipe

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#221]
![2015-12-19_00017](https://cloud.githubusercontent.com/assets/15571788/11917275/f8d567c2-a700-11e5-8443-6ea87b09c8da.jpg)
The problem is that that valve seems located on the main poison pipe, so it felt strange to still have poison on the main exit because of the sensor still active; you could do something like that
![screenshot_20151220095333](https://cloud.githubusercontent.com/assets/15571788/11917281/2f7b1646-a701-11e5-9f46-b35f2252cc0f.png)
Also a problem, turning this valve seems to stop the poison underground only **for a limited amount of time**: If you turn the valve → go down(no poison) → go up → go down again after a while (poison again!). You have to open and close the valve again in order to pass through.

**Comment by Zuntti** [comment]
Valve pipe is now in the poison underground.
