### ISSUE TITLE
reserve1: player can get stuck

### ISSUE THREAD

**Issue by Dragory** [loiste-interactive/infra-issues#222]
Stuck:
![2015-12-20_00002](https://cloud.githubusercontent.com/assets/2606411/11918323/a80773ce-a734-11e5-9579-2538f6ffb3c5.jpg)

Where you can access this area (walk forward on the right):
![2015-12-20_00004](https://cloud.githubusercontent.com/assets/2606411/11918324/b02b7172-a734-11e5-9f11-0f489ad29e9f.jpg)

## Additionally

This area can only be exited by sprint-jumping:
![2015-12-20_00007](https://cloud.githubusercontent.com/assets/2606411/11918332/ff2c2e60-a734-11e5-86a5-482d557aa02b.jpg)

**Comment by Oskutin** [comment]
Fixed.
