### ISSUE TITLE
watertreatment : Secondary clarifier P2 is marked as ON despite being inactive

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#223]
When you arrive at the treatment plant, the secondary clarifier P2 is labeled as active even before you do anything about it.
![2015-12-20_00008](https://cloud.githubusercontent.com/assets/15633807/11918919/5ea31dd8-a742-11e5-878b-83b23f0e88e7.jpg)

**Comment by Zuntti** [comment]
Fixed.
