### ISSUE TITLE
sewer feedback 

### ISSUE THREAD

**Issue by FireWarp** [loiste-interactive/infra-issues#227]
Woah, you sure did a great job on this level. Unlike watertreatment, it is solid, refreshing, it offers well-implemented new puzzles and much massive events. 
Let's begin:
Maybe it is just my perception of how game mechanics work, but those sensor things were confusing to me even with subtitles on: I thought you left a nasty bug with a trigger_multiple triggering poison at the beginning of the map because I couldn't notice the sensor. I think you should give them a cool beep sound and make them glow red when they see you instead of that annoying alarm. 

 This trigger can be skipped by jumping on a fence.
![2015-12-19_00006](https://cloud.githubusercontent.com/assets/8556074/11958567/986b11ae-a8d9-11e5-9132-c6b25805f792.jpg)

Forklift puzzle was both fantastic and frustrating at the same time. The general design for it was cool but the implementation was a let down. 
![2015-12-22_00001](https://cloud.githubusercontent.com/assets/8556074/11958826/30c9ef00-a8db-11e5-8fde-392550552f8d.jpg)
The mini-crane thing: I have some concern about the design of the control room: it has dark vomit-like color lighting, dusty windows, and the annoying monitor, obstructing my view on the car. I understand the concept of having to look through monitors to navigate the crane, but I'd rather just walk outside and check out things myself. Put that monitor a shelf down and remove the metal thing, or make the monitor look more natural by removing noise and black and white filter. 
Crane controls are plain dumb, unintuitive and clumsy. Why not just put a SOMA-like controllable joystic and a lift lever? That would make much more sense and also be less frustrating to control.  I also noticed a massive fps drop when turning on the crane makes it even more frustrating.

![2015-12-19_00007](https://cloud.githubusercontent.com/assets/8556074/11959206/2abf3852-a8dd-11e5-9bec-5f0f1d3309d4.jpg)
forklift's "fork" can go all the way through the roof.

**Comment by FireWarp** [comment]
Continuing on with forklift puzzle: I feel like I wasn't rewarded with anything at all after completing this. It is a problem with the entire game, it gets even worse when you realise that most of it's puzzles are "turn that valve and progress further". Electricity pool in tunnel4 is a great example of this - you have just finished this long rage inducing section dying more than once, and what you get after that is even more puzzles? I'm not saying that section outside was lackluster, but it was simply not enough for me to relax after that.
Some player dialogue would be cool and refreshing(we haven't gotten any since watertreatment contro room).
Adding up to what I said about crane control room thing, making this puzzle little bit harder would definately work . I found the diesel canister thing cheap for such a puzzle, so why not have differently colored canisters with different kinds of fuel, place a mark on the back of the forklift that would work as a hint to what kind of fuel we need. There we go, a harmless addition!

**Comment by Oskutin** [comment]
Fixed that trigger, forklift work and made the monitor better and crane more visible.

**Comment by Yuccaa** [comment]
More canisters were added, and the fps drop has been fixed in the next update.
