### ISSUE TITLE
Minor door issues in office

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#228]
![](http://images.akamai.steamusercontent.com/ugc/362904121309233176/A24D393EE226EE899DE628AC1DFB757DC0841ECE/)

missing sounds or animations, can't be closed

![](http://images.akamai.steamusercontent.com/ugc/362904121312322262/3C57BDAE2F483FE6D5F7C78526488132D7E1DB1D/)

missing sounds or animations, can't be closed

![](http://images.akamai.steamusercontent.com/ugc/362904121311845893/7D81E1CD6D50DB4D579EE0630F11CA2D75E7A8A8/)

missing animations i think

![](http://images.akamai.steamusercontent.com/ugc/362904121311849232/2521B7DCDD91382B2292964009A42644E5801DA9/)

this closet can't be used even though similar ones can be used in player's office

![](http://images.akamai.steamusercontent.com/ugc/362904121311851980/BDFA7112286CB83A6E87DFE12120114634CD1F06/)

missing sounds i think

![](http://images.akamai.steamusercontent.com/ugc/362904121312325794/56F9788A804450D43FCA903B6B67B4B0269A8B8C/)

wrong sounds, sounds like a handle

![](http://images.akamai.steamusercontent.com/ugc/362904121312326975/7D015CBF75A3BF7145616F4FAAF0EE8E32D7180F/)

missing animations i think

**Comment by Yuccaa** [comment]
Fixed all.
