### ISSUE TITLE
Floor cubemap issues in office

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#229]
![](http://images.akamai.steamusercontent.com/ugc/362904121312323789/D75DDF8D8D219BE392EA8764F4695BBBE70E3E9A/)

![](http://images.akamai.steamusercontent.com/ugc/362904121311845893/7D81E1CD6D50DB4D579EE0630F11CA2D75E7A8A8/)

**Comment by Yuccaa** [comment]
Fixed.

**Comment by aleksijuvani** [comment]
two more that aren't fixed yet

![](http://images.akamai.steamusercontent.com/ugc/362904549517852262/2E010FB1F01C51F3BDA4EC07A0DFBAFA4377D93E/)

![](http://images.akamai.steamusercontent.com/ugc/362904121321147796/05A850D1EC2EDC83A7B01FE8A0FA367CB076E886/)

**Comment by Oskutin** [comment]
Should be fixed now.
