### ISSUE TITLE
dam_door1 in reserve1 can't be closed once opened

### ISSUE THREAD

**Issue by paavohuhtala** [loiste-interactive/infra-issues#23]
Doesn't really break anything, but it differs in behaviour from every other door in the map.

Might be related to this error message:
```
Unlocking prop_door 'dam_door1' at (262 -981 -3328) with no hardware. All openable doors must have hardware!
```

**Comment by Oskutin** [comment]
Does this happen with the other door with lock?

**Comment by Oskutin** [comment]
Fixed.
