### ISSUE TITLE
tower : Out of Stalburg Steel monologue triggers too soon.

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#231]
![2016-01-09_00014](https://cloud.githubusercontent.com/assets/15633807/12216675/1c9e3442-b6ea-11e5-92f6-4309dc2d498f.jpg)
![2016-01-09_00015](https://cloud.githubusercontent.com/assets/15633807/12216676/1cc412c0-b6ea-11e5-88fa-93bcaf3c1ab1.jpg)

The player is pretty much still in Stalburg Steel at this point, and broken stuff can't be taken pictures of.

**Comment by Yuccaa** [comment]
Fixed.
