### ISSUE TITLE
sewer : Transformers all have the same label

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#232]
![2016-01-09_00012](https://cloud.githubusercontent.com/assets/15633807/12216682/5ad83af0-b6ea-11e5-8918-a5e165805889.jpg)
![2016-01-09_00013](https://cloud.githubusercontent.com/assets/15633807/12216683/5afa6d14-b6ea-11e5-92b0-6d79e8f03368.jpg)

**Comment by Yuccaa** [comment]
They are wrong anyway as those are transformers instead of generators.

**Comment by N-G-Neer** [comment]
Thought so too :P

**Comment by Zuntti** [comment]
Fixed.
