### ISSUE TITLE
office : Seam visible in parking wall.

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#233]
![2016-01-09_00010](https://cloud.githubusercontent.com/assets/15633807/12216687/8d0ca3a8-b6ea-11e5-8a96-e89a7c9b3edf.jpg)

I don't know if this is part of the shadow artifact fix mentioned in the CHANGES section.

**Comment by Yuccaa** [comment]
Part of it and therefore already fixed.
