### ISSUE TITLE
tower : Payphone feedback

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#234]
Unless I'm doing something wrong, the first phone number is not working (010 159 322 90)

Also, nice little easter egg if you have a good memory for phone numbers (or the ability to take screenshots) I look forward to some tea ^^

Lastly, what an intriguing conversation for the internal line...

**Comment by aleksijuvani** [comment]
The internal line is supposed to be an answering machine. There was supposed to be a line that says "you have one new message" in the beginning, but that was broken. I've fixed it now.

Oh, and that phone number you tried to call is a red herring. This is on purpose. It just plays a busy tone.
