### ISSUE TITLE
office : Seam visible in elevator

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#237]
You can see the outside through small gaps between the elevator screen and the rest of the cabin. Same for the metal panel that falls off after the blackout.
![2016-01-09_00020](https://cloud.githubusercontent.com/assets/15633807/12217004/cfad9d76-b6f3-11e5-9efd-0d580895d6d8.jpg)
![2016-01-09_00021](https://cloud.githubusercontent.com/assets/15633807/12217005/d0f105ec-b6f3-11e5-907d-43e82bcee6b4.jpg)

**Comment by Yuccaa** [comment]
Fixed.
