### ISSUE TITLE
office : Weird artifacts in the kitchen's office

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#238]
![2016-01-09_00024](https://cloud.githubusercontent.com/assets/15633807/12217019/1fc3503a-b6f4-11e5-972c-8e262c0b84bd.jpg)
![2016-01-09_00025](https://cloud.githubusercontent.com/assets/15633807/12217021/20feb48a-b6f4-11e5-927a-0c7deebf267b.jpg)

The papers pinned on the cork board flicker when standing outside the office.

**Comment by aleksijuvani** [comment]
I think this happens on other maps too with that particular model. Looks like a depth buffer precision issue that causes the notes to clip through the board behind them, exposing the ambient occlusion baked into the board.

**Comment by Yuccaa** [comment]
Fixed.
