### ISSUE TITLE
office : Areaportal error (I.T service)

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#239]
![2016-01-09_00026](https://cloud.githubusercontent.com/assets/15633807/12217030/4d89e970-b6f4-11e5-8c68-aa9c3bda45e8.jpg)
![2016-01-09_00027](https://cloud.githubusercontent.com/assets/15633807/12217031/4eac20de-b6f4-11e5-82b3-fefa7df8a32d.jpg)
![2016-01-09_00028](https://cloud.githubusercontent.com/assets/15633807/12217032/4f8115b4-b6f4-11e5-9338-9e759d943a67.jpg)

Went to the I.T's front desk, then through the server room, then looped back to the lobby.

**Comment by Yuccaa** [comment]
Fixed.
