### ISSUE TITLE
Use highlights remain visible even when object can no longer be used

### ISSUE THREAD

**Issue by paavohuhtala** [loiste-interactive/infra-issues#24]
https://dl.dropboxusercontent.com/u/5017522/ShareX/2015/11/2015-11-01_13-45-32.webm

**Comment by paavohuhtala** [comment]
Also this door:
https://dl.dropboxusercontent.com/u/5017522/ShareX/2015/11/2015-11-01_13-59-55.webm
setpos -631.096863 -10799.625000 -3263.968750;setang 13.537416 -11.716942 0.000000

**Comment by aleksijuvani** [comment]
Fixed in the next update.
