### ISSUE TITLE
reserve2 : Particle effects flicker

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#240]
![2016-01-09_00040](https://cloud.githubusercontent.com/assets/15633807/12217232/6ed6c52a-b6fa-11e5-9028-071b033650bf.jpg)
![2016-01-09_00041](https://cloud.githubusercontent.com/assets/15633807/12217234/6f067388-b6fa-11e5-87b9-b078cf6657f5.jpg)
![2016-01-09_00042](https://cloud.githubusercontent.com/assets/15633807/12217233/6f038e02-b6fa-11e5-82c8-fa4722704ac7.jpg)

When standing at a certain distance, in the first room after the elevator, the water particles will turn on and off at random.

**Comment by N-G-Neer** [comment]
Other flicker (decals, not particles)
![2016-01-09_00039](https://cloud.githubusercontent.com/assets/15633807/12217365/3563c8fc-b6fe-11e5-81e3-ab44a4ebe1ac.jpg)
![2016-01-09_00038](https://cloud.githubusercontent.com/assets/15633807/12217366/35681880-b6fe-11e5-993a-b3afd0f75386.jpg)

**Comment by aleksijuvani** [comment]
Particles fixed in the next update. Might open a separate issue for other flickering stuff, but there isn't much that can be done about it.
