### ISSUE TITLE
tunnel2 : Phone call suggestion

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#241]
When the player calls his boss, he should report the corpse he found back at the tunnel door-control building, and maybe also make mention of the stash near the tunnel entrance as well.

**Comment by madattak** [comment]
It bugged me that he didn't think it was worth mentioning that he found a corpse.

**Comment by DiscendoVox** [comment]
This may be because the corpse isn't entirely "canon". It appears to be tied to some greater ingame secret, still unfound. Note the code on the edge of the tarp covering it.
