### ISSUE TITLE
tunnel1 : Can't take picture of corruption document

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#242]
Unless that's just supposed to be a journal's headline. (Then again I think some newspapers are considered corruption documents)

This one is found bellow the catwalk with the timed remote doors (D1,D2,D3 and D4)
![2016-01-09_00043](https://cloud.githubusercontent.com/assets/15633807/12217503/0abcc57c-b703-11e5-98ff-8d96497ca574.jpg)

**Comment by Yuccaa** [comment]
Fixed.
