### ISSUE TITLE
Player can access an area that should be inaccessible in office

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#246]
You can climb on top of the railing on the 7th floor and from there you can sprint jump to this spot.

![](http://images.akamai.steamusercontent.com/ugc/362904121321169312/50131228FFDABEEB3AA55776D65B30A328AC7807/)

![](http://images.akamai.steamusercontent.com/ugc/362904121321170452/0374524CF25442649920BDD8FDE1C2863E4FB6A1/)

**Comment by Oskutin** [comment]
Fixed
