### ISSUE TITLE
reserve1 signal box plays click sound on use even when "block reserved" is active

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#250]
Kinda weird. Maybe allow using the button, but don't make it change the signal? Alternatively don't play sound on use when "block reserved" is active.

![](http://images.akamai.steamusercontent.com/ugc/362904549517901963/D3E28FF465FA913C71373F199FEEAC50FC7F270E/)

**Comment by Oskutin** [comment]
fix'd
