### ISSUE TITLE
[feedback] about locked doors

### ISSUE THREAD

**Issue by evilhackman** [loiste-interactive/infra-issues#252]
This almost drove me crazy in furnace:
I had picked up both keys from the poisonous cellar, yet the control room door in the production hall upstairs would not open and I was stuck for what feels like hours. All that happened was me rattling at the door. I tried dozens times, went back and forth, reloaded level...
Then randomly I found out a specific behaviour at locked doors: 
- look at the door in a random direction or any direction that is not the lock -> rattle
- look specifically at the lock -> unlock it

Imo this ris bad! I would suggest that any interaction with a locked door simply unlocks it incase player has the key. Pretty sure I'm not the only one to dumb to figure this out and being stuck and frustrated

**Comment by Oskutin** [comment]
There isn't any doors in the levels requiring to aim directly into the lock.

**Comment by evilhackman** [comment]
Yes, whatever version is on Steam right now.
Could it be related to screen resolution? Mine is 1600x1200.

**Comment by Oskutin** [comment]
Can you give me picture of the said door?
Was you able to play this level: https://camo.githubusercontent.com/6c47201826baed2e489c13ed90eb85427b4ee460/687474703a2f2f66696c65732e3133333775706c6f61642e6e65742f323031352d31322d33315f30303030312d3266323761322e6a7067

**Comment by evilhackman** [comment]
I don't have a screenshot right now, but this is the area 
![2015-11-13_00007](https://cloud.githubusercontent.com/assets/15716642/12254146/fdfe8e44-b8e5-11e5-9fb5-4752a8f6b03b.jpg)
![2015-11-13_00008](https://cloud.githubusercontent.com/assets/15716642/12254148/ffb00254-b8e5-11e5-9764-e91e8f935a12.jpg)
It's the upstairs control room.

And yes, I was able to play the introduction level

**Comment by Oskutin** [comment]
Fixed
