### ISSUE TITLE
furnace, bugs and feedback

### ISSUE THREAD

**Issue by evilhackman** [loiste-interactive/infra-issues#253]
- minor visual bug: weird lighting at shelf in tools room in poison cellar
![2016-01-11_00001](https://cloud.githubusercontent.com/assets/15716642/12248760/c9f006d4-b8bb-11e5-96b6-1f33185a4b6d.jpg)

- minor visual bug: lights shining through wall at power switch in production hall
![2016-01-11_00002](https://cloud.githubusercontent.com/assets/15716642/12248771/e20a7cc2-b8bb-11e5-832a-93fe20b7cef2.jpg)

- gamebreaking: barrel(s) may block entrance to fuse room. The barrels must roll down instantly! If not, the player may easily block them while standing there with the brick in hands. The 2nd barrel has a high likelines to stay on the box and easily get pushed into the entrance
![2016-01-11_00005](https://cloud.githubusercontent.com/assets/15716642/12248844/549eaeb6-b8bc-11e5-9f8d-86c2ab63c7bc.jpg)

feedback: the finale is better overall than in previous iterations. Yet I don't get why you added the 3-fuses puzzle. It's annoying and requires loads of walking back and forth and searching for fuses. It really only prolongs the level, which is already one of the slowest. Imo 1 or 2 fuses would be more than enough

**Comment by Oskutin** [comment]
Fixed
