### ISSUE TITLE
[need hint] getting off the tower?

### ISSUE THREAD

**Issue by evilhackman** [loiste-interactive/infra-issues#254]
I'm stuck on the tower. I figured out how to activate the cell communication by pushing the fuses on the roof. Then downstairs at the power switch box, character says "this did the trick, now i need to find a way to get down"
Do I need both power levers to work? The right always causes a short circuit.

**Comment by Oskutin** [comment]
Use the funicular.

**Comment by evilhackman** [comment]
the funicular button isn't doing anything. Do all 4 fuses need to be active (glowing state)? What about the power levers in the comm room?

**Comment by Oskutin** [comment]
Does the radio mast have red blinking light?

**Comment by evilhackman** [comment]
Nothing is blinking

Here's the thing: I think I'm doing it wrongf, yet the monologue tells me I was succesfull and want to leave the tower..
Here's my setup
-downstairs
![2016-01-12_00002](https://cloud.githubusercontent.com/assets/15716642/12270233/600c1222-b955-11e5-98f1-507d04f6dfb0.jpg)
-roof:
![2016-01-12_00001](https://cloud.githubusercontent.com/assets/15716642/12270236/65b5132c-b955-11e5-8772-de5c03a75e98.jpg)

[b]RESULT after pushing left Reset downstairs [/b]
![2016-01-12_00003](https://cloud.githubusercontent.com/assets/15716642/12270273/827859c4-b955-11e5-81ea-de4e89fa7793.jpg)
![2016-01-12_00004](https://cloud.githubusercontent.com/assets/15716642/12270274/84081482-b955-11e5-90fd-011f00d3b1fa.jpg)

I could for the hell of it not figure out the correct procedure though :(

**Comment by Oskutin** [comment]
Turn those burnt fuses off.

Hmm, i could add spark effect to those burnt fuses to make it more clear that they're broken.

**Comment by evilhackman** [comment]
Ok I'll try!?
Anyways, the monologue "that did the trick" should not be showing up while I'm doing it wrong (see above)

**Comment by Oskutin** [comment]
Added sparks and fixed the monologue.
