### ISSUE TITLE
reserve1 cottage doors missing use highlights

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#257]
Shouldn't be useable or should have use highlights. One of the cottages uses the same green wooden door model from `furnace`, but it's unuseable there. I see a couple of quick solutions here:

* Add use highlights to the doors and change the green wooden door model (or its skin)
* Remove the knocking sound from the doors altogether

**Comment by Yuccaa** [comment]
Fixed.
