### ISSUE TITLE
Train brake sound is illogical 

### ISSUE THREAD

**Issue by Yuccaa** [loiste-interactive/infra-issues#259]
The brake screeching sound loudness should stay the same during the whole breaking sequence.

**Comment by madattak** [comment]
I thought you were just being picky when you mentioned this, but the train sound was odd!

**Comment by Oskutin** [comment]
Fixed

**Comment by aleksijuvani** [comment]
I think this is still an issue.

**Comment by Yuccaa** [comment]
Fixed for good.
