### ISSUE TITLE
reserve2: possible bug in synchroscope puzzle

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#266]
I synchronized only one of the two synchroscope, than pressed the activation button: it stayed red, but the switch activated anyway. After that the second synchroscope was impossible to synchronize
![screenshot_20160116104508](https://cloud.githubusercontent.com/assets/15571788/12371767/3dfedc18-bc3f-11e5-904a-c9bbb916db40.png)

**Comment by Yuccaa** [comment]
Intended behavior, but might need better way to tell the player this is supposed to happen.
