### ISSUE TITLE
Office NPCs missing colors on Shader Model 2

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#269]
Having all these people around causes periodic little freezes when info like that appear
![screenshot_20160116111937](https://cloud.githubusercontent.com/assets/15571788/12371876/1b837794-bc43-11e5-9298-59cb94aa5557.png)
Also, some of the collegues have some problems of compenetration or visual bugs
![screenshot_20160116110648](https://cloud.githubusercontent.com/assets/15571788/12371858/0e80951e-bc42-11e5-8327-16963e8a7eb8.png)
![screenshot_20160116110748](https://cloud.githubusercontent.com/assets/15571788/12371859/11275c26-bc42-11e5-8c95-cbca7b78918b.png)
Also, why the red hair?
Seeing only red-tailed women around you underlines that there is only one female model 
![2016-01-16_00002](https://cloud.githubusercontent.com/assets/15571788/12371868/7f965c5c-bc42-11e5-8c18-2d33dcec97d6.jpg)

**Comment by Gheppio** [comment]
Wait, wait, I see from screenshots posted now on the community hub that other players have different (and better, fortunately) npc decals
ME
![2016-01-16_00001](https://cloud.githubusercontent.com/assets/15571788/12372137/226a5a8c-bc4d-11e5-9aad-1b7cae1f29a7.jpg)
OTHERS (seen on community hub)
![screenshot_20160116123100](https://cloud.githubusercontent.com/assets/15571788/12372139/32eed86a-bc4d-11e5-98b2-742f207f5472.png)
Is this a bug or it's intended?

**Comment by Yuccaa** [comment]
That sitting woman having hands clipping through the skirt has been fixed.

**Comment by Yuccaa** [comment]
You're missing the colour tinting from your npcs. What are your settings?

**Comment by Gheppio** [comment]
Here are the video settings I set
![2016-01-16_00018](https://cloud.githubusercontent.com/assets/15571788/12373469/63a836e0-bc7a-11e5-9e5d-cd189c7e994b.jpg)
At the moment I'm also verifying cache's integrity

**Comment by Gheppio** [comment]
Found a missing file, but the problem is still there!

**Comment by Yuccaa** [comment]
It's probably a shader problem, but at least I couldn't replicate it with the exact same settings.

**Comment by Gheppio** [comment]
Anything else that I could try? Maybe reinstalling all?

**Comment by Gheppio** [comment]
I reinstalled the game but the problem persists, all women are red-tailed, I hope that this won't happen to many others.

**Comment by Yuccaa** [comment]
Okay this probably has something to do with your hardware conflicting with the shaders. Mind posting your setup?

**Comment by Gheppio** [comment]
Yes, do you mean the msinfo32 right?
Which e-mail do I have to send it?

**Comment by Yuccaa** [comment]
Yeah. Send it to jukka @ loisteinteractive.com

**Comment by Gheppio** [comment]
Sent

**Comment by aleksijuvani** [comment]
The color issues on the NPCs are caused by the game running on the integrated graphics card (which doesn't support Shader Model 3). See #293.
