### ISSUE TITLE
Some achievements not triggering.

### ISSUE THREAD

**Issue by Oskutin** [loiste-interactive/infra-issues#271]

**Comment by Arcky431** [comment]
"Restoring the Flow" achievement doesn't seem to be working properly.

After repairing one of the flow meters, the console prints the following:
*basemodpanel received event Client:CmdKeyValues*

However, unlike the camera spots achievement or the geocaches one, the console is not printing the following:
*basemodpanel received event OnProfileDataSave*

Progress doesn't seem to be tracked at all.

**Comment by aleksijuvani** [comment]
Probably a duplicate of #276.
