### ISSUE TITLE
transition to infra_c5_m2_sewer

### ISSUE THREAD

**Issue by tittyn** [loiste-interactive/infra-issues#273]
My game crashes every time when transitioning from infra_c5_m1_watertreatment to   infra_c5_m2_sewer.
"infra.exe has stopped working"
i5 6500 & HD6850, max settings except 4x AA and filtering if that matters.

**Comment by Yuccaa** [comment]
This is already fixed on today's update which will go live in a few hours.

**Comment by Yuccaa** [comment]
Should be fixed now.
