### ISSUE TITLE
Invert Mouse option not exposed in menu

### ISSUE THREAD

**Issue by Knetic** [loiste-interactive/infra-issues#274]
Mouse cannot be inverted through the controls menu. Changing `m_yaw` or `m_yaw2` to negative numbers in `config.cfg` seems to have no effect. And despite it being listed in binds, `toggleconsole` does not seem to be active in either the first cutscene or main menu.

It should go without saying that a lot of people use inverted mouse. The option should be exposed, if possible.

Others have had the same issue but not reported it; [here](http://steamcommunity.com/app/251110/discussions/0/458606248627379704/).

**Comment by aleksijuvani** [comment]
I've implemented this in the next update. We'll be shipping it later today or some time tomorrow at the latest. You'll have the option to choose between "inverted X", "inverted Y" and "inverted X + Y".

**Comment by Knetic** [comment]
Awesome! Thanks for the quick turnaround! :+1:
