### ISSUE TITLE
Play button in main menu causes crash to desktop

### ISSUE THREAD

**Issue by sexbad** [loiste-interactive/infra-issues#275]
Hello friends.

I've already played more than three hours of the game, so I'm not sure how this happened now, but I'm getting a CTD from the Play button in the main menu. The options menu is perfectly accessible, but the Play button freezes, replays the button press sound a few times, and then crashes to desktop.

I am running on Windows 7 64-bit, with an AMD FX-8320 8-core @3.50 GHz and an nVidia GeForce GTX 970, and 16GB of RAM.

I am including a crash log that appeared in my game directory.

I know there is apparently a patch planned in the next couple of hours, so I hope that it will be fixed in that somehow, but I figured that I should post this just to be sure.

[infra_6272_crash_2016_1_16T20_49_46C0.zip](https://github.com/loiste-interactive/infra-issues/files/93081/infra_6272_crash_2016_1_16T20_49_46C0.zip)

**Comment by Oskutin** [comment]
In what level did you reach?

**Comment by sexbad** [comment]
I don't remember a specific name, but it was a water treatment plant, I think. It had flow diagrams, contemporary computers, and brightly colored pipes,

**Comment by sexbad** [comment]
I'm happy to say that the menu is working fine after this latest patch.
