### ISSUE TITLE
"No game session" - Achievements not unlocking

### ISSUE THREAD

**Issue by Arcky431** [loiste-interactive/infra-issues#276]
I started playing today from the beginning just fine and I got the first achievement after completing the "Preparations" chapter. Shortly after, in the following chapter, achievements stopped unlocking and their progress (camera spots, etc) stopped being tracked.

I enabled the developer console to see what was happening. Well, this is it:

-- Right after launching the game, the game is set to VAC Insecure (not sure if this has anything to do with it or not) and it displays the following message (No Game Session):

![2016-01-16_00003](https://cloud.githubusercontent.com/assets/4933658/12374266/600cbcb0-bc96-11e5-8182-498247c89e05.jpg)

-- Once I load a quick save, the same message displays again on the console:

![2016-01-16_00004](https://cloud.githubusercontent.com/assets/4933658/12374267/6011fb62-bc96-11e5-9e58-b2bd441c1a72.jpg)

-- After completing an achievement, which should then become unlocked, this is printed instead:

![2016-01-16_00005](https://cloud.githubusercontent.com/assets/4933658/12374268/6014ff6a-bc96-11e5-8de4-8f793b6efe21.jpg)

However, ever since I began to play, I did not turn cheats on nor did I do anything that I was not supposed to do other than playing.
For the record, it seems to be happening just with Infra, I'm not having trouble with any other game. I also tried reinstalling and restarting Steam, reinstalling Infra and starting a new game multiple times with no result. My Steam connection seems to be working flawlessly.

Not sure what is happening here.

This is what I had so far when achievements stopped working for me:

http://steamcommunity.com/id/Arcky1/stats/251110/?tab=achievements

**Comment by Arcky431** [comment]
A quick update on this: I found a work around.

Starting a new game seems to fix the issue until you go back to the menu / exit Infra. The issue disappears **only if** I start a new game and *then* load my quick save. On the other hand, if I load any save **before** starting a new game first, I get the NO GAME SESSION message as shown above.

**Comment by MuckPie** [comment]
> A quick update on this: I found a work around.
> 
> Starting a new game seems to fix the issue until you go back to the menu / exit Infra. The issue disappears only if I start a new game and then load my quick save. On the other hand, if I load any save before starting a new game first, I get the NO GAME SESSION message as shown above.

You are a saint!

**Comment by aleksijuvani** [comment]
> A quick update on this: I found a work around.

> Starting a new game seems to fix the issue until you go back to the menu / exit Infra. The issue disappears only if I start a new game and then load my quick save. On the other hand, if I load any save before starting a new game first, I get the NO GAME SESSION message as shown above.

Hey, thanks for the steps to reproduce the issue. I think I know what's wrong. I'll get this fixed soon.

**Comment by aleksijuvani** [comment]
This has been fixed in the next update.
