### ISSUE TITLE
Loading screen between office and reserve1 stays black.

### ISSUE THREAD

**Issue by HooptyBooty** [loiste-interactive/infra-issues#277]
The issue only appeared when I changed the graphical settings to get a better performance, otherwise the level loaded fine before. Now, I see the loading icon disappear after +- 1min of loading and my screen remain black and I hear no sound. It's a shame because I like the game so far.

**Comment by Demolisher05** [comment]
Same here, and changing the graphics back to normal didn't fix anything. Since I changed the graphics in the office, I never even got to the reserve, just a black screen. If I try clicking, I can hear noises like when changing the settings on the main menu, but that's it.

**Comment by HooptyBooty** [comment]
The problem was fixed by itself.
