### ISSUE TITLE
Attempting to connect to server - connection failure prevents playing the game

### ISSUE THREAD

**Issue by Oskutin** [loiste-interactive/infra-issues#278]
Steam cloud issue?

**Comment by aleksijuvani** [comment]
As a workaround, Steam Cloud can be disabled by right-clicking INFRA on Steam, selecting "Properties", then "Updates" and then unticking "Enable Steam Cloud synchronization for INFRA".

**Comment by aleksijuvani** [comment]
Is this still an issue?
