### ISSUE TITLE
Out of bounds error in watertreatment

### ISSUE THREAD

**Issue by Yuccaa** [loiste-interactive/infra-issues#283]
![infra_c5_m1_watertreatment0017](https://cloud.githubusercontent.com/assets/5402153/12378215/f07712f6-bd3f-11e5-94fe-5f53d8ec2a39.jpg)

By first jumping on the blue barrels, then on the electrical box and then climbing on the fence the player can get on top of the building, where he can jump out of the map. A playerclip is needed on the building roof.

**Comment by Zuntti** [comment]
Fixed.
