### ISSUE TITLE
[howto] debug commands, console, level selection?

### ISSUE THREAD

**Issue by evilhackman** [loiste-interactive/infra-issues#284]
Hi.

Now since the game is realeased, the debug console has disappeared, and also has the map selection.
I would really like to continue to provide feedback and bug reports, so it would be nice if someone could provide a short list of useful commands to make things easier.
Maybe we can sticky this post and make it a comprehensive guide for testers!?

- how to activate and access the console?
- how to manually load a level?
- console commands to show debug info map name and player coordinates

**Comment by Sonador** [comment]
Activate console by launching the game with the launch option -console
Manually load a level with "Map <mapname>" (An autocomplete list will appear)
net_graph 1 will display coordinate and debug info
status will list mapname and other info
