### ISSUE TITLE
model stitching problems

### ISSUE THREAD

**Issue by evilhackman** [loiste-interactive/infra-issues#287]
SOme of the NPC models have visible seams, esp. at the amrs, sometimes even visible gaps. It's more noticable from a distance, when it starts flickering.
![2016-01-17_00002](https://cloud.githubusercontent.com/assets/15716642/12378990/03ad18a6-bd50-11e5-8164-839c57869b32.jpg)
![2016-01-17_00003](https://cloud.githubusercontent.com/assets/15716642/12378992/080893d0-bd50-11e5-8cb0-a0707b76ad6c.jpg)
![2016-01-17_00004](https://cloud.githubusercontent.com/assets/15716642/12378994/0aeeb566-bd50-11e5-9931-a0909bd08571.jpg)

It's also esp. visible here at the 16:11 minute mark http://www.twitch.tv/tddaz/v/35855744

**Comment by Yuccaa** [comment]
This was actually just fixed in the last update.

**Comment by Yuccaa** [comment]
Actually some variations still have these problems.

**Comment by aleksijuvani** [comment]
If I remember correctly, these small seams were fixed in 1.0.4 or 1.0.5 or 1.0.6. Haven't investigated the distance bug yet, but it looks like it could have something to do with the graphics settings.
