### ISSUE TITLE
Decals respawn over existing decals if the player dies

### ISSUE THREAD

**Issue by paavohuhtala** [loiste-interactive/infra-issues#29]
m1_tunnel
```setpos 1199.797729 -4613.586426 900.031250;setang 14.519519 147.545807 0.000000```
![2015-11-01_00005](https://cloud.githubusercontent.com/assets/803180/10869072/13f727ba-80ab-11e5-99b7-d70294ab8f29.jpg)

**Comment by aleksijuvani** [comment]
Should be fixed in the next patch.
