### ISSUE TITLE
Unable to pick up bolt cutters.

### ISSUE THREAD

**Issue by Oskutin** [loiste-interactive/infra-issues#290]
http://steamcommunity.com/app/251110/discussions/0/458606248634142814/?tscn=1453084068

**Comment by jaredforshey** [comment]
I opened (and then closed) an issue on here for the same thing; I couldn't replicate the issue after starting a new game. My save game was from Saturday night, and I think there may have been a Steam update for the game Sunday before I started playing again and encountered the bolt cutters for the first time. I wonder if that is relevant.

When I was experiencing the issue, there was another issue where the control panels with the two power switches for the generators in the next room (with malfunctioning gen 2) had no texture and appeared as a completely black obelisk that the flashlight would not illuminate. Starting a new game fixed that too, just in case that gives you some indication of the timeframe I'm talking about.

My previous ticket: https://github.com/loiste-interactive/infra-issues/issues/286
