### ISSUE TITLE
Player teleports into the floor (and the intro controls break) if the game is saved and loaded during the intro

### ISSUE THREAD

**Issue by Uusis69** [loiste-interactive/infra-issues#291]
Upon starting the game, players character sank in the floor after the meeting ended and meeting room door was closed and player was given controls. 
http://steamcommunity.com/sharedfiles/filedetails/?id=603321260
http://steamcommunity.com/sharedfiles/filedetails/?id=603321120
http://steamcommunity.com/sharedfiles/filedetails/?id=603321174

First I checked the settings, didn't remember to apply anything and started the game. Got like two or three lines from the characters before I saved on the Save Slot 1 and Exited to Main Menu. I went and changed Captioning from None to Subtitles. And applied. 
In Game options I turned off Motion Blur and applied. Fov was at 90. Also changed mouse sensitivity from 2.0 to 2.3 and applied.

I was able to replicate it when saved middle of the Meeting, exiting to main menu and pressing "Continue".

http://files.1337upload.net/2016-01-18-1101-32-ac6d15.mp4
The replicated bug. Able to get out by crouching.

Okay further testing. It happens again, if you load the save slot which you saved in the middle of the Meeting and do stuff differently in the Meeting itself.

**Comment by aleksijuvani** [comment]
Hey, thanks for reporting this and thanks for the steps to reproduce the issue. I'll try to get this fixed as soon as possible.

**Comment by aleksijuvani** [comment]
I've fixed the controls in the next update. Still working on the view issue.

**Comment by aleksijuvani** [comment]
Both fixed in the next update.
