### ISSUE TITLE
annoying sound alarm in infra_c3_m2_tunnel2 in the office you can trigger the fire alarm

### ISSUE THREAD

**Issue by demonz312** [loiste-interactive/infra-issues#292]
when you trigger the fire alarm it never stop, please if you can make somehow it will turn off by delay or player could turn off it

http://steamcommunity.com/id/Demonz312/screenshot/353898034218661941

**Comment by Yuccaa** [comment]
This is intended action, triggering a fire alarm without fire is probably not the wisest thing to do.

**Comment by AkariKitsune** [comment]
I say it should be changed so it can be turned off. The sound can be really annoying, especially with complex puzzles in the small treatment plant map.
