### ISSUE TITLE
Water reflections break on low graphics settings

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#293]
The bug is not systematic, it happens sometimes but, when it does, every level that has water shows this thing in the reflections. The image is fixed to the player wiew and seems to be a part of some sort of building. 
I think this bug might be related to issue #267 
![2016-01-09_00016](https://cloud.githubusercontent.com/assets/15571788/12400549/0e66e0e8-be21-11e5-897b-b8f05641b482.jpg)
![2016-01-09_00017](https://cloud.githubusercontent.com/assets/15571788/12400550/12241af2-be21-11e5-97d3-045f668f29ca.jpg)
![2016-01-09_00018](https://cloud.githubusercontent.com/assets/15571788/12400551/14c1afd6-be21-11e5-93b8-3373f6b42e40.jpg)
![2016-01-09_00019](https://cloud.githubusercontent.com/assets/15571788/12400559/260b54cc-be21-11e5-9ea5-76cc9819a96f.jpg)

![2016-01-18_00013](https://cloud.githubusercontent.com/assets/15571788/12400553/1b2b01ba-be21-11e5-8344-d3dfe329c957.jpg)

**Comment by Oskutin** [comment]
All those reflections seems to be from the office level.

**Comment by Gheppio** [comment]
I thought the same thing, I'm even more convinced that this issue #267 where the image is rotated so that the office structure is out of the FOV

**Comment by aleksijuvani** [comment]
I think that's "cheap water". That shouldn't be happening unless you're running on very old hardware. Are you sure that the game is using your dedicated graphics card instead of your integrated one like before?

**Comment by Gheppio** [comment]
You're right aleskijuvani! 
The mat_info says Intel HD Graphics 400 again instead of NVIDIA geforce gt 740M!
The strange thing is that I just controlled the BIOS and secure boot is still disabled, also I've set infra.exe on Nvidia control panel to be ran with high performance Nvidia processor instead of integrated graphic, so I don't understand what makes it switch to integrated graphic!

**Comment by aleksijuvani** [comment]
That's really weird. Source Engine has always had problems with Nvidia Optimus though. I'm not sure if there's much that I can do to fix this. Valve keeps blaming Nvidia and Nvidia keeps blaming Valve on this.

I think there's a launch parameter in a newer version of the Source Engine that you can use to work around the issue, but ours doesn't have that. I'll take a look at this later.

**Comment by PC75** [comment]
I can't see the own reflection in the river or in the office's mirrors of the bathrooms or on metallic door.

**Comment by PC75** [comment]
This is a Steam shoot of where I can't see me in the mirror:
http://steamcommunity.com/sharedfiles/filedetails/?id=641332991

**Comment by CorruptComputer** [comment]
@PC75 The last three images are an areaportal issue, this will be fixed in the next update and that playerless reflection is a different issue than this one.

**Comment by aleksijuvani** [comment]
Turns out that this wasn't a Shader Model 2 issue, but an issue with low graphics settings. This has now been fixed.
