### ISSUE TITLE
reserve3: disappearing objects in the corpse room

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#294]
Things disappear with distance

A chair
![screenshot_20160118203301](https://cloud.githubusercontent.com/assets/15571788/12400834/c0b8c3b4-be22-11e5-8c27-d9664d8c9c9c.png)
![2016-01-16_00023](https://cloud.githubusercontent.com/assets/15571788/12400841/cd0a61c2-be22-11e5-9e18-529922f8ee36.jpg)

The corpse and the table
![2016-01-16_00024](https://cloud.githubusercontent.com/assets/15571788/12400855/e06e372a-be22-11e5-9518-add0b25abd2d.jpg)
![2016-01-16_00025](https://cloud.githubusercontent.com/assets/15571788/12400858/e3917066-be22-11e5-92e6-1eb60ffb2cf2.jpg)

**Comment by Oskutin** [comment]
They have too short fade distance, will be increased.

**Comment by Oskutin** [comment]
Fixed
