### ISSUE TITLE
Unable to unlock sawmill's outside door even after taking the key

### ISSUE THREAD

**Issue by Arcky431** [loiste-interactive/infra-issues#299]
Once you take the key, if you first open this door:

![2016-01-19_00002](https://cloud.githubusercontent.com/assets/4933658/12421646/79e261e2-bec3-11e5-8b68-ce5f296d6201.jpg)

And then attempt to open this one:

![2016-01-19_00003](https://cloud.githubusercontent.com/assets/4933658/12421657/84f94320-bec3-11e5-8bb9-8edc369f303e.jpg)

The second one will stay locked no matter what. However, if you first open the outside door and then you open the inner one, everything seems to be correct.

**Comment by Yuccaa** [comment]
Fixed.
