### ISSUE TITLE
Can't turn off blue pumps in water chlorination plant

### ISSUE THREAD

**Issue by madattak** [loiste-interactive/infra-issues#302]
The valves on the blue pumps (A3 and A4) at the chlorination plant (tunnel2) highlight when looked at but cannot be turned and make no 'stuck' animation. Same result when the pipes flowing into it are open or closed. Restarted the game and closed both pipes, now I could turn off the pumps.

**Comment by CorruptComputer** [comment]
It is also possible to close pumps A1 and A2 when water is flowing, they are unable to be reopened after though. Going to the computer to turn off the flow gives the "You must turn Pumps A1 and A2 first!" message, this breaks the entire puzzle and the only way to fix is to restart the level.

**Comment by Oskutin** [comment]
Managed to get the blue ones fixed, but red are still problematic

**Comment by Oskutin** [comment]
Okay, the red pumps are now working correctly too.
