### ISSUE TITLE
Unreachable geocache?

### ISSUE THREAD

**Issue by Arcky431** [loiste-interactive/infra-issues#311]
Alright, one of the geocaches in **sewer** seems to be unreachable. The whole area around it is player clipped (or looks like it is, anyway).

You can't go beyond that "big electrical box" that's on the right side of the canal (after going under the bridge) as there appears to be a player clip. You can't cross the canal either, nor go over the fence or the guard's room.

I used noclip to get to the zone but even from inside I couldn't find a single way to get around the player clips. Am I missing something?

This is the geocache I'm talking about.

![2016-01-20_00002](https://cloud.githubusercontent.com/assets/4933658/12454479/011c4fea-bf98-11e5-89f2-fe86d8c2f189.jpg)

**Comment by Zuntti** [comment]
Fixed.
