### ISSUE TITLE
"Restoring the flow" achievement

### ISSUE THREAD

**Issue by Arcky431** [loiste-interactive/infra-issues#315]
Just a quick note on this achievement - It doesn't seem to be working for anyone. I'm pretty sure I've fixed all of those water flow meters, but their repairing progress stays at 0%. Also, if repairing them is supposed to count towards the "**Structural Analyst Extraordinaire**" achivement, I'm not sure if they're being tracked for that one either. Just thought I'd mention it.

**Comment by aleksijuvani** [comment]
Oh, shoot. You're right. Thanks for reporting this. I'll have this fixed in the next update.

Also, repairing them doesn't count towards Structural Analyst Extraordinaire, that's a separate counter.

**Comment by aleksijuvani** [comment]
Fixed in the next update.
