### ISSUE TITLE
Possible to get stuck in elevator base in hydro plant chapter 3

### ISSUE THREAD

**Issue by lordcrc** [loiste-interactive/infra-issues#321]
In the hydro plant area after the raft, it's possible to jump into the base of the broken elevator. If you stand at the top of the small stairs in front of the elevator, one can climb (spacebar) the outer railing. From there one can jump onto the inner railing and then drop into the base. Once into the base the player is stuck with no way out.

I tried this because there was a very tempting ladder there which sadly did not work :P

**Comment by lordcrc** [comment]
The easiest way to fix this is probably just to make sure you can't climb the railing. It only works in that one spot IIRC.

**Comment by Oskutin** [comment]
Fixed
