### ISSUE TITLE
Possible to get stuck between wall and pipe in chlorination plant

### ISSUE THREAD

**Issue by lordcrc** [loiste-interactive/infra-issues#322]
In the room you enter right before the pump room, it's possible to get stuck between the wall and a pipe.

As the player first enters the room (underneath the smoke-break balcony), on the right side there is a pit, with a large pipe in the corner closest to the player. It's possible to jump onto the pipe and then go between the wall and the pipe. Once there the player is stuck and cannot move.

**Comment by Oskutin** [comment]
Fixed
