### ISSUE TITLE
car driver door is solid red and has no windows.

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#324]
Picture says it all. Was broken in the last update.
![2016-01-22_00001](https://cloud.githubusercontent.com/assets/1034930/12503311/80195b4e-c0d3-11e5-935c-5070abf07716.jpg)

**Comment by Oskutin** [comment]
This is weird, works for me.

**Comment by aleksijuvani** [comment]
Hey @sebastiannielsen, if you have the developer console enabled, could you type in `mat_info` and copy & paste the output here?

You should be able to enable the console if you right-click INFRA on Steam, select "Properties" and then "Set Launch Options..." and type in `-console` and press "OK" and "Close".

**Comment by sebastiannielsen** [comment]
here is the output.
Note that the car driver door becomes good after pressing USE on it.
![2016-01-23_00001](https://cloud.githubusercontent.com/assets/1034930/12531291/ddf0c030-c1f6-11e5-9252-e6b10e6c394a.jpg)

**Comment by sebastiannielsen** [comment]
Still not fixed in latest version. Note that I have resetted all saved and have begun on a new play, so this is not a save issue: 
![20160315072716_1](https://cloud.githubusercontent.com/assets/1034930/13770760/9b409038-ea89-11e5-8887-26332c1e16cd.jpg)

**Comment by sebastiannielsen** [comment]
Verified: Its only present when use highlighs are disabled in game options. When use highlights are enabled, the car driver door works normally.

**Comment by aleksijuvani** [comment]
Fixed.
