### ISSUE TITLE
Chapter 4 global lighting is too dark

### ISSUE THREAD

**Issue by AbueloNemesis** [loiste-interactive/infra-issues#325]
And too dark is being generous, considering there is just blackness in lots of areas. I'm not sure if this is a bug or made in purpose, but both are wrong IMO.

Let's check this example:

![2016-01-22_00001](https://cloud.githubusercontent.com/assets/16831352/12504809/7af0c4be-c0e1-11e5-9bf1-734afa082e29.jpg)
These are the stairs at the end of the "big machinery room" of Stalburg Steel, the room is full of light everywhere, but for some unknown reason when you approach to this place (which it seems to have standard light when you look at it in the distance) it starts to become extremely dark. This happens to most supposed-to-be-dark places there, and I suspect it could be the same in the entire level or even the full chapter.

This is another example, i just can't understand why the wall is pure black considering that light source right there, even a directional one should project some light on the wall and around it:
![2016-01-22_00010](https://cloud.githubusercontent.com/assets/16831352/12504814/8a9066cc-c0e1-11e5-914c-d9316d6b78d3.jpg)

Things get complicated when you proceed to the nex big room, we see even more intense light on here. But, these small "stands" have inside some consoles like painted in black, they don't care there are lots of light out there and even some windows with powerful light sources in front of them:
![2016-01-22_00005](https://cloud.githubusercontent.com/assets/16831352/12504931/910536da-c0e2-11e5-9a7e-82b7fa0b28e9.jpg)
![2016-01-22_00007](https://cloud.githubusercontent.com/assets/16831352/12504823/9c4b2438-c0e1-11e5-9f6f-1af321feda13.jpg)
![2016-01-22_00008](https://cloud.githubusercontent.com/assets/16831352/12504829/a3d551f6-c0e1-11e5-836b-6f72c1b84c0a.jpg)
![2016-01-22_00009](https://cloud.githubusercontent.com/assets/16831352/12504834/aac3f8e6-c0e1-11e5-979b-f206f2cbe047.jpg)

Downstairs is the same issue, full-light windows projects zero bright right here, except a tiny reflection in the floor:
![2016-01-22_00006](https://cloud.githubusercontent.com/assets/16831352/12504838/b475ede0-c0e1-11e5-9f30-d3b5940e2a92.jpg)

Also here you can see an example of how the light is affected by distance of the player because potato. First screenshot is at a reasonable distance, second one is when you approach to there:
![2016-01-22_00011](https://cloud.githubusercontent.com/assets/16831352/12504846/c4a47920-c0e1-11e5-9d59-41e05ad7b774.jpg)
![2016-01-22_00012](https://cloud.githubusercontent.com/assets/16831352/12504847/c9121da0-c0e1-11e5-90df-9fcdf0c67b02.jpg)

And the list goes on, every corner is potentially a source of zero light.

Ok I know you guys probably want to offer a level with some deeper dark areas (assuming this is not a bug) and probably give more importance to the flashlight, but there is a huge difference between dark and complete blackness, which is unrealistic in these cases. Previous chapters gave a more realistic and comprehensive lighting on these situations (and they were underground ones!), here I just feel like the inside of a blackhole is waiting for me when I'm just a step away from most light sources.

I barely remember my days with Hammer Editor, but I know this particular problem happened to me a few times.

**Comment by Oskutin** [comment]
Added some light sources here and there.
