### ISSUE TITLE
Reserve 1 update locked this cave entrance?

### ISSUE THREAD

**Issue by Arcky431** [loiste-interactive/infra-issues#326]
Since issue #301 was fixed in the latest update (1.0.7), the entrance to this hidden cave appears to have been locked. I mention #301 due to that displacement issue being really close to the cave, and I guess it has something to do with this. I'm not sure of it though.

![2016-01-22_00001](https://cloud.githubusercontent.com/assets/4933658/12509872/05df9cde-c106-11e5-9c3e-e151120a44e3.jpg)

**Comment by Oskutin** [comment]
Fixed, will appear in the next update.
