### ISSUE TITLE
Utility light in tunnel2 has no texture

### ISSUE THREAD

**Issue by paavohuhtala** [loiste-interactive/infra-issues#33]
`setpos -308.519073 -4691.206543 818.031250;setang 6.537426 -129.672760 0.000000`
![2015-11-01_00006](https://cloud.githubusercontent.com/assets/803180/10869119/f080794c-80ac-11e5-9ad7-1cfe72ee04aa.jpg)

**Comment by Zuntti** [comment]
Fixed.
