### ISSUE TITLE
office : possible to clip through this NPC

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#345]
![2016-01-24_00005](https://cloud.githubusercontent.com/assets/15633807/12549556/58acbffa-c35e-11e5-8a74-076c9fc5c575.jpg)

Also, I think this particular NPC doesn't have any dialogue lines. (unless this is the case for all female NPCs ?)

**Comment by Yuccaa** [comment]
Is this still possible?
