### ISSUE TITLE
tunnel: keypad doesn't work

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#350]
![2016-01-24_00015](https://cloud.githubusercontent.com/assets/15633807/12551133/a337d46a-c368-11e5-8dfa-b2bd9c1a4305.jpg)

Not that I mind, but other people might be curious about SCP-4027 :P

**Comment by Oskutin** [comment]
It requires to be powered with fuse.

**Comment by aleksijuvani** [comment]
The screen should be off if there's no power, like what happens with the alarm panel in `tunnel4`. Right now this is just confusing.

**Comment by Zuntti** [comment]
Fixed.
