### ISSUE TITLE
tunnel2 : Green mushrooms should be toxic

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#351]
![2016-01-25_00001](https://cloud.githubusercontent.com/assets/15633807/12551185/f03e60d0-c368-11e5-8964-9466a536f46d.jpg)

They're not in a great number here, but this is a confined space, so...Plus they are toxic in the lab storage room in watertreatment.

**Comment by Oskutin** [comment]
Now they are.
