### ISSUE TITLE
tunnel4 : Possible stuck spot between the generators

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#354]
Managed to get unstuck after a few minutes of struggling, but the problem could be avoided easily if the generator switches were just a few inches forward.
![2016-01-25_00006](https://cloud.githubusercontent.com/assets/15633807/12551315/c2b83b6c-c369-11e5-901f-bdc0172bdc7f.jpg)

**Comment by Oskutin** [comment]
Fixed
