### ISSUE TITLE
tunnel4 : Can't take a picture of collapsed area from this side

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#355]
Right after the storage room and before the electrified hallway, I wasn't able to to a picture of this collapsed section. However I was able to on the other side.
![2016-01-25_00007](https://cloud.githubusercontent.com/assets/15633807/12551349/05330e04-c36a-11e5-9e98-f1cfabe7da80.jpg)

**Comment by Oskutin** [comment]
Actually you can, if you haven't taken photo from the other side.
