### ISSUE TITLE
furnace : Possible to skip this hazard

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#356]
![2016-01-25_00009](https://cloud.githubusercontent.com/assets/15633807/12551361/1496f298-c36a-11e5-952c-e505a6042ca6.jpg)
When the main furnace turns back on and all goes to hell, you can squeeze behind these pipes without needing to turn off the valve.

**Comment by Oskutin** [comment]
Fixed, thanks.

**Comment by CorruptComputer** [comment]
I'm furnace there is actually a way to skip the whole thing and the first time I played through I never turned it on. I'll take a video of this later, but if you want to test it here are the steps: go up the stairs near the shutoff button, climb onto the railing, get on top of the little box (it's slightly higher than the railing), jump around the fence.
