### ISSUE TITLE
watertreatment : Screen still displays incorrect informations.

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#358]
![2016-01-25_00015](https://cloud.githubusercontent.com/assets/15633807/12551417/923f1c2a-c36a-11e5-9591-7c10df5b0b0e.jpg)
Picture taken after activating the grit classifier in the alarm building. Shouldn't the Grit Classifier 01 be green ?

**Comment by Zuntti** [comment]
Fixed.
