### ISSUE TITLE
watertreatment : Achievement suggestion

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#361]
If you buy a drink and bring it inside the control room you should get an achievement like "Anarchist" or "Screw your rules" or something similar :P 
![2016-01-25_00022](https://cloud.githubusercontent.com/assets/15633807/12551502/433d94ca-c36b-11e5-989b-3aa3cb05350b.jpg)

**Comment by Zuntti** [comment]
Added.

**Comment by N-G-Neer** [comment]
Nice, thanks ^^
