### ISSUE TITLE
sewer : Toilet ladder is finicky to climb up

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#363]
![2016-01-25_00025](https://cloud.githubusercontent.com/assets/15633807/12551629/38374de0-c36c-11e5-89a4-7688b86d68da.jpg)

**Comment by sebastiannielsen** [comment]
Its really not the ladder, but rather the lack of sufficent space to stand on, once reaching top of ladder. This causes the ladder logic not to release the player at the top. The wall with "Exit" sign needs to be moved futrer away so theres some floor to stand on in front of the "Exit" sign.

**Comment by Oskutin** [comment]
Should be fixed now
