### ISSUE TITLE
Control panel shows Clarifier as active when enabling Grit classifier.

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#364]
The control panel shows clarifier 2 as active, when you press the button to the Grit classifier 1.
The icon for Grit classifier 1 is always a red X, regardless.

Expected behaviour:
If the grit classifier is enabled (eg button have pressed so the screen shaked), the grit classifier 1 icon should become a green > when pressing the grit classifier 1 button inside the water sample room.
In the same way, clarifier 2 icon should become active when pressing the clarifier 2 button, but only if grit classifier 1 icon is a >.

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/infra-issues/issues/358
