### ISSUE TITLE
sewer2 : Player dies from the collapse in the safe area

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#365]
If the player stares at the door opening instead of turning his back and letting the collapse happen, he will die even though this room is supposed to be safe.
![2016-01-25_00029](https://cloud.githubusercontent.com/assets/15633807/12552793/23bbf1ec-c374-11e5-8ebc-f18663e2656a.jpg)

**Comment by Zuntti** [comment]
Fixed.
