### ISSUE TITLE
The geocache in the cave in reserve1 is a little bit too far to reach without jumping around a bit

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#384]
![2016-01-29_00001](https://cloud.githubusercontent.com/assets/3168386/12682287/5249049c-c6bb-11e5-8cf5-7393fb0680b2.jpg)

(already took the geocache so it's not visible in the picture, but move it a bit towards the player)

**Comment by Zuntti** [comment]
Fixed.
