### ISSUE TITLE
The indicator light here stays red until the valve is in

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#388]
![2016-01-29_00009](https://cloud.githubusercontent.com/assets/3168386/12682421/f7454672-c6bb-11e5-8222-320058057b5a.jpg)

(picture only for position reference)

Kind of weird. I think it should be able to display green even if the valve isn't in yet. This way you can check the puzzle status before finding the valve. The computer screens still display it, but this doesn't, so it's kind of inconsistent and confusing.

**Comment by sebastiannielsen** [comment]
Agreed. Logically, the system that controls the lamp cannot know if the valve is physically in (since that is a mecanical connection), so it should become green regardless of valve position when water is not flowing.

**Comment by Oskutin** [comment]
Fixed
