### ISSUE TITLE
There should be an autosave at this corruption document

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#390]
![2016-01-29_00012](https://cloud.githubusercontent.com/assets/3168386/12682499/76a655d2-c6bc-11e5-967f-284d75cad9ba.jpg)

There should be an autosave after photographing the document there. If you fall into the water, it's kind of annoying to having to turn on the water flow monitor again and walking all the way back there.

**Comment by Zuntti** [comment]
Fixed.
