### ISSUE TITLE
Entering this shore shouldn't instantly kill the player, but instead do gradual damage until he inevitably dies

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#391]
![2016-01-29_00016](https://cloud.githubusercontent.com/assets/3168386/12682563/c2beca80-c6bc-11e5-971a-e667c4500723.jpg)

I think the other "shores" could do with the same treatment.

**Comment by Oskutin** [comment]
Trigger_hurts there have max damage as 20 and Nervegas damage type.

**Comment by aleksijuvani** [comment]
I tried this earlier and there was some kind of invisible wall and the player took over 2000 damage afterwards.
