### ISSUE TITLE
All the junk near the water is annoying to walk over and shouldn't have collisions

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#393]
![2016-01-29_00018](https://cloud.githubusercontent.com/assets/3168386/12682646/34132992-c6bd-11e5-819a-22fb0b962e62.jpg)
![2016-01-29_00022](https://cloud.githubusercontent.com/assets/3168386/12682647/34171c8c-c6bd-11e5-929b-fe398ab0b2e3.jpg)
![2016-01-29_00021](https://cloud.githubusercontent.com/assets/3168386/12682648/341ef682-c6bd-11e5-84a3-311862f517f4.jpg)
![2016-01-29_00020](https://cloud.githubusercontent.com/assets/3168386/12682650/3483bfd6-c6bd-11e5-803a-d899612e3c8d.jpg)
![2016-01-29_00019](https://cloud.githubusercontent.com/assets/3168386/12682649/34720502-c6bd-11e5-93d0-0252cb8dc70b.jpg)
![2016-01-29_00028](https://cloud.githubusercontent.com/assets/3168386/12682684/6952a0b0-c6bd-11e5-91b2-e2d5d7d2b273.jpg)
![2016-01-29_00030](https://cloud.githubusercontent.com/assets/3168386/12682686/69594906-c6bd-11e5-8cdf-8d201848aecd.jpg)
![2016-01-29_00029](https://cloud.githubusercontent.com/assets/3168386/12682687/6983a840-c6bd-11e5-9fff-75337a7e2db7.jpg)

**Comment by Zuntti** [comment]
Fixed.
