### ISSUE TITLE
This note is a bit too dark to be easily read

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#394]
![2016-01-29_00024](https://cloud.githubusercontent.com/assets/3168386/12682715/a6475204-c6bd-11e5-95f2-0222f33f4424.jpg)

**Comment by aleksijuvani** [comment]
There's a light switch that could be made functional here.

![2016-01-29_00025](https://cloud.githubusercontent.com/assets/3168386/12682754/dd46f67e-c6bd-11e5-818b-5b29fd840060.jpg)

**Comment by Zuntti** [comment]
Added functional light switch.
