### ISSUE TITLE
This key box in tunnel4 doesn't work like you'd expect it to work at all

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#395]
![2016-01-29_00026](https://cloud.githubusercontent.com/assets/3168386/12682766/f0454154-c6bd-11e5-95e4-5cf8e5ba67d7.jpg)

opening the box shouldn't automatically pick up the keys

also the box should have its own use highlights in addition to the keys

**Comment by Zuntti** [comment]
Fixed.
