### ISSUE TITLE
The paint on the keypad doesn't make much sense

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#396]
![2016-01-29_00027](https://cloud.githubusercontent.com/assets/3168386/12682777/0722f4d4-c6be-11e5-84e5-474567472cbc.jpg)

I actually saw a few people getting stuck here because of this. Their reasoning was that if someone typed in the code with paint on his hands, it would wear off as he tapped the keys. If the code was `3459`, `3` should have the most paint, `4` the second most, then `5` and lastly `9`. Right now it looks like it's the other way around which doesn't make sense.

**Comment by Zuntti** [comment]
Fixed.
