### ISSUE TITLE
Light sprites sometimes not turned on

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#398]
![2016-01-29_00032](https://cloud.githubusercontent.com/assets/3168386/12682917/b3ce1de4-c6be-11e5-88a7-52f44a00f124.jpg)

The sprites here aren't turned on sometimes. Looks like it might happen while entering the area through the dynamite puzzle. I backtracked to the alternative route and then back again and the lights were on this time.

**Comment by aleksijuvani** [comment]
I tried this again and the sprites appeared correctly. Might have something to do with the player dying?

**Comment by Zuntti** [comment]
Changed to sprites
