### ISSUE TITLE
This ladder works really weirdly in furnace

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#402]
![2016-01-29_00042](https://cloud.githubusercontent.com/assets/3168386/12683030/6a63b910-c6bf-11e5-8b76-6b3c345b52ba.jpg)

It should be possible to use space to climb on top of the planks and then climb the ladder. Right now the planks have their own ladder which feels super wrong.

**Comment by Oskutin** [comment]
Fixes
