### ISSUE TITLE
All this crap on the floor shouldn't have collisions in tower

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#405]
![2016-01-29_00056](https://cloud.githubusercontent.com/assets/3168386/12683917/d71a3278-c6c4-11e5-864b-e3dc7ff164b8.jpg)
![2016-01-29_00055](https://cloud.githubusercontent.com/assets/3168386/12683918/d73a57e2-c6c4-11e5-86e1-4e304b96408c.jpg)
![2016-01-29_00054](https://cloud.githubusercontent.com/assets/3168386/12683919/d74d6fda-c6c4-11e5-9351-c92d1553a1f9.jpg)
![2016-01-29_00053](https://cloud.githubusercontent.com/assets/3168386/12683920/d7502810-c6c4-11e5-8c0f-bc10915893fb.jpg)

**Comment by sebastiannielsen** [comment]
The bottles I can agree, maybe it could be replaced with a trigger så the standing bottle is tipped over and becomes smashed with a "CLIRRRKK" sound when walking near), but the suitcase, bucket and beer frame should maybe instead use "soft physics" (prop_physics_multiplayer) so when walking near them, they are kicked out of way, for the realism.

**Comment by Zuntti** [comment]
Fixed.
