### ISSUE TITLE
The missing valves in watertreatment feel like there's supposed to be a puzzle there even though there is none

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#409]
![2016-01-29_00060](https://cloud.githubusercontent.com/assets/3168386/12684063/5f6fa824-c6c5-11e5-8672-42783b5334f1.jpg)

Not just me, also seen in the playthrough by @N-G-Neer.

**Comment by Zuntti** [comment]
Fixed.
