### ISSUE TITLE
The "contaminated water" report can't be picked up until the printer has stopped making sounds

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#410]
![2016-01-29_00061](https://cloud.githubusercontent.com/assets/3168386/12684112/9f40adae-c6c5-11e5-82ab-99f5663a9379.jpg)

(picture only for position reference)

It's kind of weird that it receives use highlights, but the player can't actually pick it up without waiting for a few seconds. I feel like this should be photographable instead of pick-uppable anyway.

**Comment by Zuntti** [comment]
Fixed.
