### ISSUE TITLE
tunnel4 uses wrong global for the water flow meter

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#413]
It uses "INFRA: Tunnel4 water flow meter turned on", when it should be using "infra_waterflow_tunnel4" instead. This messes up the blinking lights on watertreatment.

**Comment by Oskutin** [comment]
Watertreatment uses: "INFRA: Tunnel4 water flow meter turned on"

**Comment by Oskutin** [comment]
Fixed.
