### ISSUE TITLE
tunnel2 uses wrong global for "water supply is stopped"

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#414]
Similar to #413, except with "INFRA: Tunnel2 water supply is stopped" when it should be "infra_pumping_station_stopped". This messes up the blinking lights in watertreatment. The rest of the globals in this level are correct.

**Comment by Oskutin** [comment]
Watertreatment uses: "INFRA: Tunnel2 water supply is stopped"

**Comment by Oskutin** [comment]
Fixed
