### ISSUE TITLE
Watertreatment - Grit Classifier 01 Appearing as off when on

### ISSUE THREAD

**Issue by madattak** [loiste-interactive/infra-issues#415]
http://snag.gy/IjG7X.jpg
The Grit Classifier was turned on, and the puzzle behaved as so as far as I can tell, yet it appears as off on the screen. (I got the weird blowing wind sound when I fixed the rest of the system, so I assume that means it was solved correctly)

**Comment by aleksijuvani** [comment]
Duplicate of #358. Fixed in the next update.
