### ISSUE TITLE
Rope looks weird on reserve1

### ISSUE THREAD

**Issue by CorruptComputer** [loiste-interactive/infra-issues#419]
![image](https://cloud.githubusercontent.com/assets/5573038/12700187/eac5f47c-c79d-11e5-8847-046d53e8914e.png)

**Comment by sebastiannielsen** [comment]
(left and right is viewed as on standing on raft and looking towards the wheel)

yes, and also when turning the wheel, it turns in the wrong direction if you look how the mechanism works. When the raft is moving to the left, the rope moves to the right (as the rope is static when using the raft wheel), thus the wheel should rotate counter-clockwise. Currently the wheel rotates clockwise.

Also check the wheels on the ends (im unsure about these, if these is correct or not). The end wheels should rotate clockwise when raft moves right, and counter-clockwise when moving left. Note that the opposite wheel of the rope should rotate when using the end wheels, eg the wheels on both ends should rotate in unison, in the same direction, but the raft wheel should NOT rotate when using the end wheels.

**Comment by Yuccaa** [comment]
Fixed the rope and the wheel directions.
