### ISSUE TITLE
Camera doesn't always focus when looking at a camera target

### ISSUE THREAD

**Issue by CorruptComputer** [loiste-interactive/infra-issues#422]
![2016-01-30_00003](https://cloud.githubusercontent.com/assets/5573038/12700358/83c68654-c7a4-11e5-8f81-9b556279a341.jpg)

**Comment by aleksijuvani** [comment]
I tested this last night and it should be photographable. Maybe the camera target has too small of a range? Does it focus if you go a bit closer?

**Comment by CorruptComputer** [comment]
I tried getting closer, until it blew up. When I took the picture the sound cue played, but the camera never focused.

**Comment by aleksijuvani** [comment]
Interesting. I don't think it has anything to do with this specific camera target, but is something that happens with camera targets in general. I'll have to take a closer look.

**Comment by aleksijuvani** [comment]
Fixed.
