### ISSUE TITLE
Vent too bright in the sawmill

### ISSUE THREAD

**Issue by CorruptComputer** [loiste-interactive/infra-issues#423]
![2016-01-30_00004](https://cloud.githubusercontent.com/assets/5573038/12700359/9df9d486-c7a4-11e5-9fde-4224881793a6.jpg)

**Comment by aleksijuvani** [comment]
We did some tweaks to the lighting, so I'm not sure if this happens anymore. @Yuccaa?

**Comment by CorruptComputer** [comment]
All my issues last night were from 1.0.8 if that helps.

**Comment by aleksijuvani** [comment]
Yeah, we've been working on some changes for this map, but they didn't make it into 1.0.8. They'll be in the next patch maybe.

**Comment by Yuccaa** [comment]
Fixed.
