### ISSUE TITLE
Sawmill wires cannot be photographed when player is close

### ISSUE THREAD

**Issue by CorruptComputer** [loiste-interactive/infra-issues#425]
![2016-01-30_00006](https://cloud.githubusercontent.com/assets/5573038/12700411/197fb038-c7a7-11e5-95ba-df84c03ef143.jpg)
![2016-01-30_00005](https://cloud.githubusercontent.com/assets/5573038/12700410/197e72b8-c7a7-11e5-8621-74c9bd49832c.jpg)

**Comment by Yuccaa** [comment]
Fixed.
