### ISSUE TITLE
Bird does not fly away from player at dam vantage point

### ISSUE THREAD

**Issue by CorruptComputer** [loiste-interactive/infra-issues#427]
![2016-01-30_00007](https://cloud.githubusercontent.com/assets/5573038/12700419/5cf2f500-c7a7-11e5-8378-08e222a6c026.jpg)

**Comment by aleksijuvani** [comment]
This one is kind of weird. Sometimes he flies away and sometimes he doesn't.

**Comment by Yuccaa** [comment]
Fixed.
