### ISSUE TITLE
Cannot photograph damaged infrastructure during the raft ride

### ISSUE THREAD

**Issue by CorruptComputer** [loiste-interactive/infra-issues#429]
![2016-01-31_00001](https://cloud.githubusercontent.com/assets/5573038/12701004/749a4f74-c7bf-11e5-9509-6e2d394eac98.jpg)

**Comment by aleksijuvani** [comment]
At the moment the player can't photograph anything during the raft ride. I think this should be changed.

**Comment by aleksijuvani** [comment]
It should now be possible to photograph stuff while on the raft. The only thing left is to add camera targets to these two maps.

**Comment by Yuccaa** [comment]
Added camera targets to both levels.
