### ISSUE TITLE
Reserve 1, water flows only if you look in right angle

### ISSUE THREAD

**Issue by mpeltomaa** [loiste-interactive/infra-issues#43]
Flow:
![img_2316](https://cloud.githubusercontent.com/assets/6035374/10869683/219b1ebc-80bf-11e5-82f8-cd1ac8c95892.JPG)

No flow:
![img_2321](https://cloud.githubusercontent.com/assets/6035374/10869684/2e6dd9fe-80bf-11e5-87b1-33b12e014494.JPG)

**Comment by shadowsun28** [comment]
yeah same thing here.

**Comment by Oskutin** [comment]
This should be now fixed

**Comment by aleksijuvani** [comment]
Still an issue.

**Comment by N-G-Neer** [comment]
Seems to be fixed in the December 19th update, as the water has been removed altogether.

**Comment by mpeltomaa** [comment]
I can verify that this is not working but behaviour changed a bit.
