### ISSUE TITLE
Crash upon transitioning to watertreatment

### ISSUE THREAD

**Issue by CorruptComputer** [loiste-interactive/infra-issues#431]
I just left tower and when loading into watertreatment the game crashed.
Windows crash log:
````
Faulting application name: infra.exe, version: 0.0.0.0, time stamp: 0x56aa2671
Faulting module name: tier0.dll, version: 0.0.0.0, time stamp: 0x56aa267d
Exception code: 0x40000015
Fault offset: 0x0001c3e2
Faulting process id: 0xca8
Faulting application start time: 0x01d15bda0fc65fea
Faulting application path: E:\Steam\steamapps\common\infra\infra.exe
Faulting module path: E:\Steam\steamapps\common\infra\bin\tier0.dll
Report Id: 924918a8-c208-45d0-ba95-726288f68e52
Faulting package full name: 
Faulting package-relative application ID: 
````

Dump File:
[AppCrash_infra.exe_17dad059e156c9e7fa93443c038313e3111fba3_3ca7b1ec_29ffa3e4.zip](https://github.com/loiste-interactive/infra-issues/files/111176/AppCrash_infra.exe_17dad059e156c9e7fa93443c038313e3111fba3_3ca7b1ec_29ffa3e4.zip)

If it helps I had also checked my playtime a few minutes before and was almost at 4 hours on a single save/session.

**Comment by aleksijuvani** [comment]
Thanks for reporting this. It's probably an out of memory issue, similar to #289 and #417. Did the crash produce any `mdmp` files in the game folder? Could you send those to me?

**Comment by aleksijuvani** [comment]
Fixed in the next update. This is an out of memory crash, so YMMV.
