### ISSUE TITLE
Broken staircase is not photographable

### ISSUE THREAD

**Issue by CorruptComputer** [loiste-interactive/infra-issues#434]
I know this is during the Stalburg Steel part of the game, but even though the place is abandoned I think the city would still try to keep it safe.

![2016-01-31_00003](https://cloud.githubusercontent.com/assets/5573038/12703448/42d30cde-c809-11e5-8139-58b1fa0b7c41.jpg)

**Comment by Yuccaa** [comment]
This is indeed part of the Stalburg Steel, and as it's a closed off area the city doesn't need to do anything about it, nor they could as it's a private property.
