### ISSUE TITLE
Doors hit player in the face

### ISSUE THREAD

**Issue by CorruptComputer** [loiste-interactive/infra-issues#435]
I think a good way to deal with this is have the door always open away from the player, depending on which side they approach it from.

![2016-01-31_00005](https://cloud.githubusercontent.com/assets/5573038/12703461/8fe3e4e4-c809-11e5-9f16-6ccca7e8e286.jpg)
![2016-01-31_00007](https://cloud.githubusercontent.com/assets/5573038/12703469/a82a6942-c809-11e5-802a-c5745aa246fe.jpg)
![2016-01-31_00009](https://cloud.githubusercontent.com/assets/5573038/12703468/a82a6a82-c809-11e5-8005-3d31aec708db.jpg)
![2016-01-31_00010](https://cloud.githubusercontent.com/assets/5573038/12703470/a82ee684-c809-11e5-9249-8aa25fa74a04.jpg)
![2016-01-31_00014](https://cloud.githubusercontent.com/assets/5573038/12703471/a82f99c6-c809-11e5-8034-b560d242f798.jpg)
![2016-01-31_00015](https://cloud.githubusercontent.com/assets/5573038/12703472/a8307922-c809-11e5-8f96-d0571133377a.jpg)
![2016-01-31_00018](https://cloud.githubusercontent.com/assets/5573038/12703473/a831e53c-c809-11e5-8d08-9c192272bc1d.jpg)

**Comment by Yuccaa** [comment]
Intended behavior. Doors open to the direction of the exit like in real life.
