### ISSUE TITLE
The glowing mushrooms camera target in watertreatment has too small of a range

### ISSUE THREAD

**Issue by CorruptComputer** [loiste-interactive/infra-issues#438]
![2016-01-31_00013](https://cloud.githubusercontent.com/assets/5573038/12703497/191c0fe8-c80a-11e5-896a-5d2df9c94389.jpg)

**Comment by Yuccaa** [comment]
Actually you can, the range of the camera target just seems to be too small.

**Comment by Zuntti** [comment]
Fixed.
