### ISSUE TITLE
It's possible to skip the furnace finale trigger by climbing on this railing and then jumping to the catwalk

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#443]
![2016-01-31_00021](https://cloud.githubusercontent.com/assets/3168386/12704294/80937ed0-c860-11e5-8cc4-0eede70b0153.jpg)
![2016-01-31_00019](https://cloud.githubusercontent.com/assets/3168386/12704296/87579832-c860-11e5-848a-1749874441b1.jpg)

**Comment by Oskutin** [comment]
Fixed
