### ISSUE TITLE
In tunnel, you can take the yellow valve with you to the drawbridge route, but you can't attach it to any of the valve spots

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#444]
![2016-01-31_00016](https://cloud.githubusercontent.com/assets/3168386/12704306/ce240d18-c860-11e5-8697-a13eded537e1.jpg)
![2016-01-31_00015](https://cloud.githubusercontent.com/assets/3168386/12704309/ceb410b6-c860-11e5-896e-03e4c1e7d55d.jpg)
![2016-01-31_00014](https://cloud.githubusercontent.com/assets/3168386/12704307/ce6bd95e-c860-11e5-875d-a63d728dc38b.jpg)
![2016-01-31_00013](https://cloud.githubusercontent.com/assets/3168386/12704308/ce6f2596-c860-11e5-8ff9-d840d589641d.jpg)

**Comment by Zuntti** [comment]
Fixed.
