### ISSUE TITLE
The use highlights for the water sample cup can be seen through the water sampler

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#453]
![2016-01-31_00027](https://cloud.githubusercontent.com/assets/3168386/12704390/a3029080-c862-11e5-9c0e-b503ce81c394.jpg)

Maybe delete it while the "hatch" is closed and respawn it when it opens? Alternatively use a toggleable brush which blocks line of sight for the traces (similar to the alarm control panel keypad in `tunnel`).

**Comment by Zuntti** [comment]
Fixed.
