### ISSUE TITLE
Autosave + last checkpoint created while dying

### ISSUE THREAD

**Issue by peflo** [loiste-interactive/infra-issues#455]
I fell off the roof of the sawmill and the game seems to have autosaved during the death animation.  If I load the autosave or restart from last checkpoint I'm stuck with a black screen with the falling death sound playing every few seconds.
Since I hadn't manually saved this means I'll need to start the game from the beginning.

**Comment by aleksijuvani** [comment]
As of INFRA: Part 2, the game can no longer be saved while the player is dying. It's still possible to get stuck in a death loop if the game is manually saved just before the player dies, though. I've opened issue #804 for this.
