### ISSUE TITLE
watertreatment newspaper spelling mistakes

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#459]
![2016-02-02_00005](https://cloud.githubusercontent.com/assets/3168386/12755434/02cf421c-c9d8-11e5-90b8-4e5052eeac40.jpg)

"Main Square Protests Still Raging on" -> "Main Square Protests Still Raging On"
"says one the protesters" -> "says one of the protesters"
"Stalburg business life" -> "business life of Stalburg"
"in it's newsletter" -> "in its newsletter"

**Comment by Yuccaa** [comment]
Fixed.
