### ISSUE TITLE
Spark glow particles are visible through walls

### ISSUE THREAD

**Issue by mpeltomaa** [loiste-interactive/infra-issues#46]
When done, sparks from other screen are shown thru walls (white round spots)

**Comment by mpeltomaa** [comment]
![img_2369](https://cloud.githubusercontent.com/assets/6035374/10869955/20b96050-80c7-11e5-9347-749e176b0cb2.JPG)
Managed to capture white spot.

**Comment by CorruptComputer** [comment]
I can confirm that this happens.

**Comment by CorruptComputer** [comment]
Also I don't have a screenshot of this, but the fire that happens soon after this is invisible, but the particles are not.

**Comment by aleksijuvani** [comment]
![colorballs](https://cloud.githubusercontent.com/assets/6035374/10870238/68138a3c-80ce-11e5-9800-c9c24cf10e25.jpg)

**Comment by Nyraion** [comment]
This also happens in the hydro plant when the generators are turned on

**Comment by Oskutin** [comment]
Should be fixed in next update.

**Comment by aleksijuvani** [comment]
no it's not

**Comment by N-G-Neer** [comment]
The sparks in the flooded dam room are no longer visible through wall in the December 19th update.
