### ISSUE TITLE
Multiple issues in the blower building of water treatment

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#461]
First issue:
The wheel is useable after the blower has been turned on.
Expected behaviour: The wheel should be unuseable while blower is on, and useable once blower is off again.

Second issue:
When pressing the button for the blower, nothing happens until you press it a second time, then a green circle appears on the screen, like the blower was sorta "on" when arriving.

**Comment by Zuntti** [comment]
Fixed.
