### ISSUE TITLE
Player can get stuck in this spot at the end of furnace

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#462]
![2016-02-03_00006](https://cloud.githubusercontent.com/assets/3168386/12794869/ecdab3a4-cabf-11e5-8a8a-220cf016d36e.jpg)

If you jump down from the upper level just after the steam pipes, you can get stuck in the fenced area.

![2016-02-03_00005](https://cloud.githubusercontent.com/assets/3168386/12794874/f4a579de-cabf-11e5-8297-6755a6a1280f.jpg)

You can also access the lower area by jumping down from there, but I think there are triggers that kill the player sprinkled around the area so it's not a huge issue.

**Comment by Oskutin** [comment]
Fixed
