### ISSUE TITLE
This note on the gate shouldn't be useable

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#467]
![2016-02-05_00003](https://cloud.githubusercontent.com/assets/3168386/12845020/a3a99be4-cc0b-11e5-8d72-bad9a556654b.jpg)

Using the gate anywhere should open the gate. Right now it's too easy to accidentally use the note instead. The note doesn't have use highlights either so it's weird.

**Comment by Yuccaa** [comment]
Fixed.
