### ISSUE TITLE
Newspapers in sewer not photographable

### ISSUE THREAD

**Issue by Yuccaa** [loiste-interactive/infra-issues#485]
![image](https://cloud.githubusercontent.com/assets/5402153/13018668/870a7fa8-d1d3-11e5-80de-f97ec7bfdbf7.png)
![image](https://cloud.githubusercontent.com/assets/5402153/13018670/8c10647c-d1d3-11e5-8aa1-ca37190f1ca8.png)

**Comment by Oskutin** [comment]
Fixed
