### ISSUE TITLE
Illogical keycard coloring scheme for the lab

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#489]
I noticed that the keycard reader for the Storage is white (to exit from storage into the lab).
If we think logically, if the broken keycard reader at the opposide end of storage would work, it would mean that office personell (white keycard holders) would be able to access the lab (a high security area) without being authorized to do so (eg having a red keycard).

I would suggest that the outside keycard reader, is changed to accept both white and red keycards, which could signify by a dual-color sign and the text "Red White" on the sign.
Then on the inside lab glass door (which currently is unlocked), is fitted with a red keycard reader on both sides.
So even if the keycard reader in the opposide end of storage would work, office personell wouldn't be able to access the lab, only the lobby in the lab.

The functional change this would make, is that it would become possible to access the storage possessing only a white keycard. But that would be more logical.

**Comment by Zuntti** [comment]
Fixed.
