### ISSUE TITLE
Areaportals break at the dam 

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#499]
After I have proceeded past the control room, and then return back to the generator room/elevator room, this strange whiteout appears:
![20160315080307_1](https://cloud.githubusercontent.com/assets/1034930/13770723/5793e79a-ea89-11e5-8589-eae2f00046ee.jpg)
![20160315080313_1](https://cloud.githubusercontent.com/assets/1034930/13770725/59865dee-ea89-11e5-9482-b7fb11620c27.jpg)

Note that this is on a completely resetted, fresh play, so this is not a save/version conflict issue.

**Comment by Yuccaa** [comment]
Fixed.

**Comment by sebastiannielsen** [comment]
Still not fixed.

**Comment by Yuccaa** [comment]
We meet again, old nemesis. I have 'fixed' this issue like a dozen times now. This time it should be fixed for good. I sincerely hope so.
