### ISSUE TITLE
Bug with the one-way door powering scheme at the dynamite container.

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#500]
When you have fixed the generators and gone through the generator flood door, theres 2 paths you can take to reach the dynamite container.
Either through the gate, along the tunnel wall, until you reach a small shed.
Or, you can take the route through the flood door.

Both of these doors have electrical locks, to enforce a "one-way" scheme, so you can't visit the area for the "along the tunnel wall" if you select the flood door path and vice versa.

The bug, is that when you activate the wall switch for the flood door path, the path for gate also enabled, so you can go into the "along-the-tunnelway-path" area, thus defeating the whole intention of the locks on the doors.
I don't think thats intended to be that way.

**Comment by Yuccaa** [comment]
Fixed.
