### ISSUE TITLE
The track wagons in steel factory for pushing the ladle, are behaving incorrectly to common logic

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#501]
The track wagons inside the steel factory behaves a little bit incorrect.
When you apply reverse track voltage to the wagons, the lever on the wagon would also turn backwards when activating the wagon.

This is incorrect for 2 reasons:
1: If the wagons are controlled by track voltage, it wouldn't matter for the motors if you push the lever up or down.
2: If the wagons DO have a direction controller by having a 2-pole polarity reversing switch, pushing the lever down would reverse the reversed polarity, which would mean that normal track voltage + up lever, or reversed track voltage + down lever, would be the same direction.

Thus, since the direction of the wagons are controlled by the track voltage switches in the control room, the levers on the wagons itself should always actuate in the same direction regardless of which direction the wagons are moving. The common logic here would be to have the levers in the fully down position, and when using them, they will actuate to fully up position, and then the wagon will travel in the direction determited by the track voltage switches in control room.

**Comment by Yuccaa** [comment]
The train swtiches now only move to one position.
