### ISSUE TITLE
Autosaves during the raft ride need refining

### ISSUE THREAD

**Issue by Yuccaa** [loiste-interactive/infra-issues#505]
It's possible to be thrown into an endless respawn loop with certain autosaves and raft positions when the save triggers.

**Comment by aleksijuvani** [comment]
The last autosave in tunnel3 is one of these. The player will keep hitting their head on the beam unless they're holding the crouch button.

**Comment by aleksijuvani** [comment]
The dangerous autosave just before the end of the green mushroom cave in tunnel4 is also potentially bad. It's very close to the rocks.

**Comment by Yuccaa** [comment]
Done.
