### ISSUE TITLE
Outside lamps for the heavy door in the beginning of the forgotten world is not working.

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#508]
![20160319115120_1](https://cloud.githubusercontent.com/assets/1034930/13901297/f676d168-ee1e-11e5-820f-0af9f9eb9269.jpg)

(If this is not intentional because they are broken, but a idea would then be to make the glass broken in some way too, eg cracks and such)
(with outside, I refer from the perspective of the whole area, since the broken heavy door 1 leads directly to the outside, thus in forgotten world, you begin on the inside and go outside of the heavy door 2)

**Comment by Zuntti** [comment]
Fixed.
