### ISSUE TITLE
Emergency Bolt Cutters glass not breaking

### ISSUE THREAD

**Issue by Centax** [loiste-interactive/infra-issues#510]
I've been trying to break the glass on the emergency bolt cutter with a brick for like half an hour nothing is working I don't know if this recent patch might have caused a problem this is on version 1.1.1 I feel like this glass should break when the brick is just brought into the vicinity of the glass but this is not happening.  I've seen video of other people breaking the glass and tried to recreate their exact actions but no luck.

**Comment by Yuccaa** [comment]
You're supposed to throw the brick at glass. Defaut key binding is left mouse button.

We need to add a hint for throwing items somewhere, since it seems some people have missed it.

**Comment by aleksijuvani** [comment]
I've added a hint for throwing held objects.
