### ISSUE TITLE
Pipe room issues: A2 pipe should light red when turned off & pipe room fuse isn't working

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#513]
The A2 pipe should have its light green at start, and then turn red when turned off.
When I first played through the pipe room puzzle, I first tought A2 was some draining pipe that you opened to drain the flood out of the pipe room enough to unlock the flood door.

But now I noticed that the pipe A2 is the one with a large crack in it, and actually you shut that pipe off.

Also, one thing I noticed was that the pipe room is still active even if you don't turn on the fuse for the pipe room in the main breaker panel (at the heavy door in start).
Suggestion: If either the main breaker panel is off (red light) and/or the pipe room fuse isn't activated, all lights on pipe room panel should be out (both for water sensor and all the pipes, even for the C pipes and such), and the door lock lights for the door on top level should be out too, and door be locked.

**Comment by Zuntti** [comment]
Fixed A2 pipe light and now if you don't turn on pipe room fuse you can't open the C2 flood door or use pipe room panel.
