### ISSUE TITLE
Reserve2 : Broke the synchroscopes puzzle

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#514]
I turned the room controls on, turned the generator power on, and went to sync the synchroscopes.

The first one stopped alright, but the second one stopped way after its mark. 
![20160322180316_1](https://cloud.githubusercontent.com/assets/15633807/13960483/d007b1c8-f058-11e5-9086-232c91f74236.jpg)

I turned the generators off and on again, re-sync'd the first synchroscope, no problems, but the second one wouldn't stop anymore and keep spinning no matter when and how many times I pressed the button.

**Comment by N-G-Neer** [comment]
Tested it some more. If you hit the button when the handle is in the "West/9hour" position, it will stop after it's mark, no matter which synchroscope. However, upon rebooting the power, only the right synchroscope will continue spinning.

**Comment by Yuccaa** [comment]
Fixed.
