### ISSUE TITLE
Reserve 1, clip through first bridge

### ISSUE THREAD

**Issue by TreyNutz** [loiste-interactive/infra-issues#516]
In Reserve 1, if you crouch and go as far as possible to the side away from the geocache:

![20160322083036_1](https://cloud.githubusercontent.com/assets/17556020/13963594/30af947c-f023-11e5-8507-8044f727f3ad.jpg)

You can see through the bottom of the bridge:

![20160322083019_1](https://cloud.githubusercontent.com/assets/17556020/13963599/386997ee-f023-11e5-882a-c4e5b11c68ac.jpg)

**Comment by Yuccaa** [comment]
Fixed.
