### ISSUE TITLE
Office, shirts occasionally clip through ties

### ISSUE THREAD

**Issue by TreyNutz** [loiste-interactive/infra-issues#517]
The guy on the left:

![20160322081112_1](https://cloud.githubusercontent.com/assets/17556020/13963695/98c20266-f023-11e5-9f79-3905eeb5c215.jpg)

and here:

![20160322082135_1](https://cloud.githubusercontent.com/assets/17556020/13963708/a815052e-f023-11e5-8fa8-4d39dfe330dc.jpg)

**Comment by riksaa** [comment]
Fixed
