### ISSUE TITLE
Elevator fuse is not working in main breaker panel

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#518]
Elevator fuse is not working in the main panel at the heavy door.
If the panel is off (red light) or the elevator fuse is off, the elevator at the end of the level still works.

I think the elevator fuse should be made working, eg if its off or panel is off, it will not be possible to call the elevator after the ceiling collapse.
HOWEVER, a good idea could then be to, if the fuse is off or panel is off, disable all autosave checkpoints directly after the drawbridge puzzle, and also all save points directly after the pipe room, so the player does not get stuck with no ability to return and no ability to load a earlier checkpoint.

And if the player attempt to call the elevator with the fuse or panel in the beginning of the level off, it could say:
"Oh crap,I forgot to turn on the elevator fuse."

**Comment by Yuccaa** [comment]
The fuse is for the freight elevator behind the door with the cyan glow, not for the exit elevator.
