### ISSUE TITLE
3D skybox flickers in watertreatment + decal overflow

### ISSUE THREAD

**Issue by paavohuhtala** [loiste-interactive/infra-issues#52]
```
R_DrawDecalsAll: overflowing m_aBatches. Reduce # of decals in the scene.
```

![2015-11-01_00009](https://cloud.githubusercontent.com/assets/803180/10870243/82239b9c-80ce-11e5-89d5-695fce02e47a.jpg)

**Comment by paavohuhtala** [comment]
Also, performance isn't very good. About 30-40fps compared to 100-200fps in most other areas.

**Comment by Yuccaa** [comment]
Flickering and decal overflow fixed. Performance is still worked on.
