### ISSUE TITLE
This door in tower is missing sounds

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#520]
![20160326205051_1](https://cloud.githubusercontent.com/assets/3168386/14061897/70262f42-f395-11e5-8507-94fc1f03adcc.jpg)

**Comment by AbueloNemesis** [comment]
Not sure if related, but some doors at stalburg steel are silent when opening and closing them (but at least the "locking" sound is there).

**Comment by Yuccaa** [comment]
Fixed.
