### ISSUE TITLE
[Blocker] Generators and lift puzzle after rafting can be dead locked (pun intented)

### ISSUE THREAD

**Issue by punahilkka** [loiste-interactive/infra-issues#523]
So, have all 4 gennies running, call the elevator down, then go die in the river. 

Result: respawn, elevator is not down. Call button does nothing. Generators running (so puzzle didn't reset).

Expected result 1: Respawn, elevator is down and usable.
Expected result 2: Respawn, elevator is up, call button works.

**Comment by punahilkka** [comment]
The map is tunnel4

You could have the pinned steam discussion point to your issues reporting instructions instead of the issue list. Or both!

**Comment by Oskutin** [comment]
You're not supposed to use that elevator, it's red herring.

**Comment by punahilkka** [comment]
Yes, just noticed it myself after restarting the level and observing the elevator.
