### ISSUE TITLE
Able to get out of the playable area in tower

### ISSUE THREAD

**Issue by hawkiee552** [loiste-interactive/infra-issues#526]
Just before you enter the office building at the bottom of the tower, you can climb up onto the rail, then up on the pipes. Then, you can jump step by step downwards onto the pipe connections without taking major fall damage, and if done right you're safe on the ground.

Could be prevented by making the pipe connections no-collideable or simply create a respawn trigger on the ground beneath.

![20160331194804_1](https://cloud.githubusercontent.com/assets/18194426/14185537/9bc3fbdc-f77a-11e5-9037-59f36a898caa.jpg)

**Comment by sebastiannielsen** [comment]
The first solution would be better, eg making the flanges no-collideable.
Another solution would be to add some large equipment on the pipes just after the water (eg, where the second flange from left is on the horizontal section of pipe), like motor valves, large manual levers and valves, measuring units, and meters and such, and then use a player clip on this, so it looks like the equipment is so large so its not possible to pass, and the only option is to return or jump down in water.

**Comment by hawkiee552** [comment]
By the way, it's possible to jump down on the other end of the pipe too.

**Comment by Yuccaa** [comment]
Fixed.
