### ISSUE TITLE
Able to get out of the playable area in sewer1

### ISSUE THREAD

**Issue by hawkiee552** [loiste-interactive/infra-issues#527]
If you collect all three boxes and bring them to a fencegate (the one closest to your right when you come out from the hacker den), you might be able to stack them and jump up onto the fencegate and drop over.

![20160331220026_1](https://cloud.githubusercontent.com/assets/18194426/14189382/38a8225e-f78d-11e5-9ba6-8122a5fc5459.jpg)

Now this isn't anything game breaking, but an invisible wall would prevent anyone like me from getting out of the map.

**Comment by sebastiannielsen** [comment]
I would rather suggest extending the top fence portion instead of adding a invisible wall.

**Comment by hawkiee552** [comment]
I have no idea why this got closed, whoops.

**Comment by Zuntti** [comment]
Fixed.
