### ISSUE TITLE
Able to get out of the playable area in office (and skip a part of it)

### ISSUE THREAD

**Issue by hawkiee552** [loiste-interactive/infra-issues#528]
From the 7th floor, you can climb up onto the railing and jump down while strafing in towards the wall, and land on the 6th floor with minor fall damage.

This leaves you on the 6th floor which isn't meant to be walked on, and can be repeated numerous times until you're down at the café. Then you could jump down from there and skip a significant part of the game by taking your letter and proceeding onwards. 

![20160401150947_1](https://cloud.githubusercontent.com/assets/18194426/14207979/60f9a6e8-f81d-11e5-881e-1ad5028120d6.jpg)

Could be fixed by placing an invisible wall along the open rail at 6th floor with a slight slope at the bottom, which throws you out in the open so that you can't stand on the rail itself.

**Comment by sebastiannielsen** [comment]
Duplicate: https://github.com/loiste-interactive/infra-issues/issues/347
