### ISSUE TITLE
Able to get out of the playable area in watertreatment

### ISSUE THREAD

**Issue by hawkiee552** [loiste-interactive/infra-issues#529]
By jumping onto the blue barrels and to the wooden ledge by the wall, you can crawl along the wall and jump onto the pipe's connection. Then walk around the pipe and jump behind the house.

![20160401162844_1](https://cloud.githubusercontent.com/assets/18194426/14210094/c4d3d210-f827-11e5-95e9-047c304df514.jpg)

Either a no-collideable ledge, or an invisible wall could help here. You devs know what to do anyways! :)

**Comment by hawkiee552** [comment]
I was also able to climb up onto the orange barrel here, then follow the pipes to "4"-pillar, climbing up the pillar and the fence and jump over it.

![20160401232522_1](https://cloud.githubusercontent.com/assets/18194426/14220840/f3c78d4c-f862-11e5-9157-14f3d5a4f9c3.jpg)

**Comment by hawkiee552** [comment]
The first out-of-map could be solved by doing the same as on the other building, or as on the sawmill in reserve2 by having a slope which pushes the player down into the water.

![20160402201851_1](https://cloud.githubusercontent.com/assets/18194426/14228272/79425d5a-f910-11e5-9ba2-c09d2c2c4cfa.jpg)

**Comment by Zuntti** [comment]
Fixed.
