### ISSUE TITLE
Invisible barrier when going down this staircase in watertreatment

### ISSUE THREAD

**Issue by paavohuhtala** [loiste-interactive/infra-issues#53]
`setpos 971.781250 3004.687744 460.245728;setang -0.969845 -75.392021 0.000000`
![2015-11-01_00010](https://cloud.githubusercontent.com/assets/803180/10870313/4bd05a9c-80d0-11e5-9f17-6fef2a5a9858.jpg)

There seems to be an invisible brush blocking your way when you try to walk down the stairs. You can jump over it though.

**Comment by Yuccaa** [comment]
Fixed.
