### ISSUE TITLE
Able to jump up onto clip wall on tower

### ISSUE THREAD

**Issue by hawkiee552** [loiste-interactive/infra-issues#530]
By jumping onto the railing, then on the electrical box, the lamp and finally up ontop of the clip wall. Not a huge error though. 

![20160402214446_1](https://cloud.githubusercontent.com/assets/18194426/14228687/fe295cc4-f91c-11e5-98d7-f29b55310968.jpg)

Sorry for the awful colors hah

**Comment by Yuccaa** [comment]
Fixed.
