### ISSUE TITLE
Save management in menu

### ISSUE THREAD

**Issue by NeKzor** [loiste-interactive/infra-issues#531]
It would be really helpful if you allow us to delete saves in the slots save menu. I'd also recommend to merge the game save button and the game load button into one single button. This means only one save slot list which allows us to save/overwrite, delete and load a save game.

Another related suggestions have been mentioned [here](http://steamcommunity.com/app/251110/discussions/1/458606877317329502) already (it's about time stamps and screenshot of saves).

**Comment by aleksijuvani** [comment]
The saved game menus have been improved in the next update. They now display the current chapter and the time played.

![20160331194448_1](https://cloud.githubusercontent.com/assets/3168386/14252047/4a7486cc-fa8e-11e5-9e0a-f43253190412.jpg)
![20160331194149_1](https://cloud.githubusercontent.com/assets/3168386/14252048/4a7583e2-fa8e-11e5-8fe1-ff35cd79790d.jpg)

I'm not sure about deleting saves. I mean sure it would be nice to have, but it would require a redesign of the menus to make sense. There are only 4 slots available, and you can overwrite those saves, so I don't see it as a huge issue.

**Comment by sebastiannielsen** [comment]
Don't forget to add language tokens for "Chapter", "Played", "CH.", "H" and "MIN".

**Comment by aleksijuvani** [comment]
The menu items are localized as follows:

```
"infra_menu_autosave" "Autosave"
"infra_menu_quicksave" "Quicksave"
"infra_menu_save_slot" "Save Slot %d"
"infra_menu_save_slot_info_chapter" "%s – Chapter %d"
"infra_menu_save_slot_info_chapter_hours" "%s – Ch. %d, played %d h"
"infra_menu_save_slot_info_chapter_minutes" "%s – Ch. %d, played %d min"
"infra_menu_save_slot_info_chapter_hours_minutes" "%s – Ch. %d, %d h %d min"
"infra_menu_save_slot_info_hours" "%s – played %d h"
"infra_menu_save_slot_info_minutes" "%s – played %d min"
"infra_menu_save_slot_info_hours_minutes" "%s – %d h %d min"
"infra_menu_empty_save_slot" "Empty Save Slot %d"
```
