### ISSUE TITLE
A can of water is lying on the floor just outside the test machine

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#532]
I noticed there was a can of sample water on the floor just beside the test machine in the lab, that can be inserted and immediately get the Contaminated water paper.
This is present in the current version.

I don't think thats intentional, since that takes away the need from getting a water sample from the machine inside the clarifier control room.

**Comment by aleksijuvani** [comment]
I can't quite remember, but I think this has already been fixed for the next update. @Zuntti?

**Comment by Zuntti** [comment]
Fixed.
