### ISSUE TITLE
Trees clipping through a wall in watertreatment

### ISSUE THREAD

**Issue by paavohuhtala** [loiste-interactive/infra-issues#54]
`setpos 100.260109 2883.812256 384.031250;setang 6.222799 -173.209885 0.000000`
![2015-11-01_00011](https://cloud.githubusercontent.com/assets/803180/10870351/418b5b44-80d1-11e5-90c6-3a7bad3e1b96.jpg)

**Comment by Yuccaa** [comment]
Fixed.
