### ISSUE TITLE
Missing player clips in sewer

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#540]
![20160402142034_1](https://cloud.githubusercontent.com/assets/3168386/14382006/2f38d428-fd93-11e5-8859-808eee828757.jpg)

The bridge should have a player clip covering the "floor". Right now the camera does some weird jumping when walking on it.

![20160402142007_1](https://cloud.githubusercontent.com/assets/3168386/14382007/2f57c824-fd93-11e5-9a6c-2325ebc5ed4e.jpg)

Steps are missing player clips here.

![20160402142153_1](https://cloud.githubusercontent.com/assets/3168386/14382017/353a2b42-fd93-11e5-8ba0-3cbe92805cee.jpg)

This gate should be blocked by a player clip. Right now the player can jump on top of that small ledge and it looks bad.

**Comment by aleksijuvani** [comment]
![20160408141834_1](https://cloud.githubusercontent.com/assets/3168386/14382229/dc348540-fd94-11e5-8829-de1227132255.jpg)

Also these stairs are still broken.

**Comment by Zuntti** [comment]
Fixed.
