### ISSUE TITLE
The player clip here in reserve3 is too steep to walk over from this direction

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#541]
![20160408141149_1](https://cloud.githubusercontent.com/assets/3168386/14382092/ee18cd58-fd93-11e5-8ff8-662286da4180.jpg)

Change to use the "stairs" texture instead or make less steep?

**Comment by hawkiee552** [comment]
It could be solved by just adding "steps" or even out the clip. 

The clip itself looks like this:

![20160408234239_1](https://cloud.githubusercontent.com/assets/18194426/14398346/b0d25e50-fde3-11e5-9a78-112a1c7aec2f.jpg)

**Comment by Zuntti** [comment]
Fixed.
