### ISSUE TITLE
There shouldn't be a trigger_push here in sewer

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#544]
![20160408141745_1](https://cloud.githubusercontent.com/assets/3168386/14382211/b0e42ce2-fd94-11e5-87d4-caca45c162da.jpg)

**Comment by hawkiee552** [comment]
I wondered why that trigger_push was there, was going to report it, but thought it was intentional.

**Comment by Zuntti** [comment]
Fixed.
