### ISSUE TITLE
The elevator gate in reserve2 shouldn't have collisions, but instead a player clip that can be crouched under

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#545]
![20160408173112_1](https://cloud.githubusercontent.com/assets/3168386/14386941/b3873a46-fdaf-11e5-895c-12615e7133d1.jpg)

It's pretty hard to climb up now after the climbing mechanic was updated.

**Comment by Yuccaa** [comment]
Fixed.
