### ISSUE TITLE
The player shouldn't need to crouch to get on top of this crate in the tunnel4 flooded electrified hallway

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#550]
![20160410133230_1](https://cloud.githubusercontent.com/assets/3168386/14409721/359b3882-ff24-11e5-95f2-5bfd933b79a8.jpg)
![20160410133234_1](https://cloud.githubusercontent.com/assets/3168386/14409722/35b86ace-ff24-11e5-8b32-70baa61df8b9.jpg)

Perhaps replace the crate with something smaller?

**Comment by Zuntti** [comment]
Fixed.
