### ISSUE TITLE
office : Leaving the meeting during long sentence

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#553]
If you right-click during a long sentence in the meeting, your boss will only scold you once you're out and the door is already closed.
![20160416171922_1](https://cloud.githubusercontent.com/assets/15633807/14581888/5718638a-03f8-11e6-9310-a217fe97ad6b.jpg)

(Also I think the "awkward" pose after the "which building did you accidentally demolish this time" could be a little shorter, unless intended.)

**Comment by aleksijuvani** [comment]
Fixed.
