### ISSUE TITLE
office : Various lighting issues

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#555]
![20160416173854_1](https://cloud.githubusercontent.com/assets/15633807/14582115/8209c9e0-03fc-11e6-8bb9-1259ba76e268.jpg)

Also, these rolling shelves appear really bright for a few seconds then slowly fade to a more realistic looking color.
![20160416173759_1](https://cloud.githubusercontent.com/assets/15633807/14582123/a557c456-03fc-11e6-984c-5a437c607d85.jpg)
![20160416173802_1](https://cloud.githubusercontent.com/assets/15633807/14582125/a6db3b28-03fc-11e6-9bc1-4f686bde2edd.jpg)

From the seventh floor, these orange couches are flickering
![20160416173004_1](https://cloud.githubusercontent.com/assets/15633807/14582127/c235a660-03fc-11e6-97dd-d20c05c7a97f.jpg)
![20160416173009_1](https://cloud.githubusercontent.com/assets/15633807/14582128/c3cb1988-03fc-11e6-8737-288b614b0626.jpg)

**Comment by Yuccaa** [comment]
All but the sofas fixed.

**Comment by Yuccaa** [comment]
All fixed.
