### ISSUE TITLE
Missing subtitle at Water Treatment's Office

### ISSUE THREAD

**Issue by AbueloNemesis** [loiste-interactive/infra-issues#558]
In the control room with the giant panel of sensor monitors and when talking with the boss, if all meters were activated there is no text subtitle shown when the player talks about it in that specific situation.

The line in the subtitles_english.txt is this one:

`"player.phonecall.watertreatment.stoppedflow"					"<clr:250,231,181>If I'm reading this right, the water flow has stopped in all tunnels."`

Text is right, but "stoppedflow" is wrong. The audio playing there is "allmeters".

FIxing it changing "stoppedflow" with "allmeters" and compiling it had no effect.

**Comment by aleksijuvani** [comment]
Duplicate of #442.
