### ISSUE TITLE
reserve2 player clip refinements

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#559]
![20160417161759_1_clip](https://cloud.githubusercontent.com/assets/3168386/14587237/70772f1c-04b8-11e6-9f11-a7ba4ca4caa1.jpg)

**Comment by aleksijuvani** [comment]
actually the lower half could use a clip too so you can't get stuck on the windows

**Comment by aleksijuvani** [comment]
while we're at it why not these windows too

![20160417162434_1](https://cloud.githubusercontent.com/assets/3168386/14587254/e59c5e0c-04b8-11e6-81ea-406d19363f0c.jpg)

not really an issue but whatever

**Comment by aleksijuvani** [comment]
![20160417162533_1](https://cloud.githubusercontent.com/assets/3168386/14587264/273e87d6-04b9-11e6-9c68-f6aa8f0013f8.jpg)
![20160417162547_1](https://cloud.githubusercontent.com/assets/3168386/14587265/275b19b4-04b9-11e6-941c-523a0aad9002.jpg)

the railing clips at these spots are a bit funky too

you can hear the metal footsteps and your view bobs slightly at these spots

**Comment by aleksijuvani** [comment]
![20160417162905_1](https://cloud.githubusercontent.com/assets/3168386/14587290/840d0ec4-04b9-11e6-8585-ed3cfff26724.jpg)

these stairs are missing a clip

**Comment by Yuccaa** [comment]
All fixed.
