### ISSUE TITLE
A canister's LOD model has a different colour 

### ISSUE THREAD

**Issue by paavohuhtala** [loiste-interactive/infra-issues#56]
Watertreatment, `setpos 2041.968750 1534.769409 388.031250;setang 3.299356 132.846024 -0.000000`
![2015-11-01_00012](https://cloud.githubusercontent.com/assets/803180/10870451/1897fd0c-80d4-11e5-9c7f-c3111712f1ab.jpg)
![2015-11-01_00013](https://cloud.githubusercontent.com/assets/803180/10870452/195b4898-80d4-11e5-96b7-21513512e212.jpg)

**Comment by aleksijuvani** [comment]
Similar issue here with a barrel model, but the color appears in the lower detail version and disappears in the high detail version.

![251110_2015-11-11_00001](https://cloud.githubusercontent.com/assets/3168386/11097733/a62e6732-88a9-11e5-8c60-9a3c722622bb.png)

**Comment by aleksijuvani** [comment]
Fixed.
