### ISSUE TITLE
sewer2 : background noises during credits

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#560]
After the player puts his hardhat to the ultimate test, you can still hear creaks and steam huffs in the background while the credits are rolling and the music is playing.

**Comment by CorruptComputer** [comment]
I would call this intentional, personally I like it. It shows that after the initial collapse there are aftershocks that continue to spread out. It would be better if they slowly got further and further away, showing that there is a chain reaction happening because of the initial collapse.

**Comment by Yuccaa** [comment]
No longer relevant.
