### ISSUE TITLE
sewer : possible to get stuck in the forklift hangar

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#562]
If the player throws the only good fuel canister down the empty elevator shaft, there's no way to get it out.

In the words of Yucca, there should be an automatic reload when it happens and save when picking up the canister for the first time.

**Comment by aleksijuvani** [comment]
This is a problem with all "find the item" puzzles really, from boxes to fuses. The difference here is that there aren't multiple fuel cans laying around. I would suggest adding an additional fuel canister somewhere in the building.

I don't think that we should add a "game over" state for something as trivial as losing a fuel canister. Besides, it would be impossible to detect when the fuel can is stuck and when it's not. What if the player takes it outside the building and tosses it over a fence or whatever?

**Comment by Yuccaa** [comment]
Well the latter is of course a possibility but would require significant effort on the player's part. Getting it accidentally in the elevator shaft is something I can see happening however.

**Comment by Yuccaa** [comment]
Actually there was a pretty simple solution to this: allowing the player to enter the elevator shaft.
