### ISSUE TITLE
watertreatment : red valves are off-centered

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#564]
![20160422181055_1](https://cloud.githubusercontent.com/assets/15633807/14747927/5aed13a2-08b7-11e6-9cdf-5f4cfcfc0cdd.jpg)
![20160422181107_1](https://cloud.githubusercontent.com/assets/15633807/14747928/5be03370-08b7-11e6-8723-0d68e424d1b9.jpg)

**Comment by sebastiannielsen** [comment]
Try temporarly turning off the highlight. The highlight marks the whole object, inclusive the stud that goes into the valve house.

**Comment by Yuccaa** [comment]
Just tested, they actually are off-centered a few cm or so.

**Comment by Zuntti** [comment]
Fixed.
