### ISSUE TITLE
sewer : shortcut

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#568]
![20160422174347_1](https://cloud.githubusercontent.com/assets/15633807/14748120/4e38e658-08b8-11e6-94f3-e2e9826afecb.jpg)

It's not obvious the player can jam the door. There should be a "Automatic Door. Keep Clear" sign.

Also, the small stair makes it a bit finicky to go through the other way. Maybe the door should be in the place of the wooden panel ?

**Comment by Sidewinder53** [comment]
So, what's the purpose of this gateway? Just an additional way to get trough the level, or is there something hidden I did not discover yet? Cause, I mean, you can also get trough the smoky tunnel and from there you can use the staircase on the side of the building and then you get to the exact same location.

**Comment by Yuccaa** [comment]
It's an alternative route to complete the level.

**Comment by Yuccaa** [comment]
Added a sign to both gates.
