### ISSUE TITLE
Walking on bricks can fling the player.

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#570]
![20160426032841_1](https://cloud.githubusercontent.com/assets/15633807/14830980/c90da088-0bf3-11e6-8d75-f0fd33e0dc45.jpg)

Whenever the player is walking over bricks, those can fling him in any direction.

**Comment by aleksijuvani** [comment]
I've been thinking about disabling collisions between the player and all props under a certain size. Bottles might need some special treatment so that walking over them will break them though.

**Comment by aleksijuvani** [comment]
Collision is now automatically disabled between the player and props under a certain size and weight.
