### ISSUE TITLE
tunnel1 : Flood gates valve

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#571]
![20160430194953_1](https://cloud.githubusercontent.com/assets/15633807/14937658/c1ef10b6-0f0e-11e6-95f6-2ba1d9a6cf69.jpg)

If you try to use the A1 or A2 valve as soon as it becomes possible, the flood door will stay in place until you let go of the valve. Then it will dash up to the current position.

**Comment by Sidewinder53** [comment]
This room is a huge mess - sorry to say that. I have seen several people playing this game and no one figured out how to deal with the situation after two or three tries. The best player I know managed to get out of the rooms after 4 re-tries, and even then it's pretty hard to figure out what exactly happen and why you escaped.

**Comment by Yuccaa** [comment]
This must've been fixed, since I can't reproduce the issue.
