### ISSUE TITLE
Watertreatment storage room: Should stock up on HP toner instead of Canon toner.

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#572]
I noticed in the watertreatment storage room, that can be accessed if you go opposide the stairs on the lower floor, that the watertreatment is stocking up only Canon or "Cannot" Toner, but every printer in all buildings of the watertreatment is HP (or "HC").

I find it unusual that watertreatment would stock up on toner they don't have any use for.
In the office (first level) however, theres a fair amount of Canon MFC's or "Cannot", so the office does have use for the Toner.

Suggested fix: Replace toner in watertreatment with HP.

**Comment by Yuccaa** [comment]
Added a Cannot printer to second floor.
