### ISSUE TITLE
Crash on Raise Camera in Version 1.1.2

### ISSUE THREAD

**Issue by eahiii** [loiste-interactive/infra-issues#573]
I'm experiencing a consistent crash when raising the camera in the latest update.  I've done clean installs, wiped data, and started without saves - the crash is reproducible in every scenario.  I simply press 1 to raise the camera, and the game immediately crashes and leaves a crash MDMP file behind.

I have also attempted to rebind the "Raise Camera" to "C" instead of "1" - this results in the same crash.

Pressing "F" to raise the flashlight works correctly.

Three example dumps are attached.

[infra_mdmp.zip](https://github.com/loiste-interactive/infra-issues/files/247340/infra_mdmp.zip)

**Comment by aleksijuvani** [comment]
Thanks for reporting this and providing the crash dumps. It looks like this only happens when you have "show hints" disabled in the options menu. I'll fix this and push out a hotfix to Steam.

**Comment by aleksijuvani** [comment]
Fixed in 1.1.3. I'm including an another fix in 1.1.3 which requires recompiling one of the maps, so it'll take a few hours before I can push the update to Steam.
