### ISSUE TITLE
Issues with the use highlights of this lever

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#575]
![20160510172144_1](https://cloud.githubusercontent.com/assets/3168386/15150204/e9e1d3ce-16d4-11e6-9ee6-46e1819faf54.jpg)
![20160510172156_1](https://cloud.githubusercontent.com/assets/3168386/15150207/ec41c782-16d4-11e6-8fc5-601396cb0f40.jpg)

The button moves into the wall after it has been used, so the use highlights will start to flicker depending on the player's eye angles. The button should just kill itself after it has been used, since the lever can't be flipped back off anyways.

**Comment by aleksijuvani** [comment]
I've disabled the movement of all buttons in the game, so this button no longer moves. It should still kill itself after it has been used though,

**Comment by Yuccaa** [comment]
Fixed.
