### ISSUE TITLE
Stuck spot in furnace

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#576]
![20160510171637_1](https://cloud.githubusercontent.com/assets/3168386/15150278/2f902a88-16d5-11e6-8f91-5c1d6802a8bc.jpg)
![20160510171641_1](https://cloud.githubusercontent.com/assets/3168386/15150281/31f43f76-16d5-11e6-9deb-9e25d28e7e71.jpg)
![20160510171646_1](https://cloud.githubusercontent.com/assets/3168386/15150283/332a35da-16d5-11e6-93e6-c71801a99368.jpg)

The player can use this crate to climb on top of the fence and get himself stuck in the enclosed area. 

The player can also use the crate to climb on top of the fence and then on top of the crane steel beams. If the player tries to jump back down, he will instantly be killed by a trigger.

![20160510171833_1](https://cloud.githubusercontent.com/assets/3168386/15150316/607a0114-16d5-11e6-9fa0-ddeae6f3df5b.jpg)

I think the easiest solution to this would be to move or remove the crate.

**Comment by Yuccaa** [comment]
Removed.
