### ISSUE TITLE
These two levers in tower need to have on/off labels

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#577]
![20160510172935_1](https://cloud.githubusercontent.com/assets/3168386/15150375/907cabe6-16d5-11e6-8eb1-4ecb18b1ae3f.jpg)

The functionality of these two levers is confusing. The player might turn them off prior to hitting the power switch, causing nothing to happen, and then erroneously thinking that he fixed the panel (when he in fact has just turned it off). This has also happened in a Let's Play video that I forgot the name of.

**Comment by sebastiannielsen** [comment]
I think a indicator light would be more suitable and more "in-place" here.

There could be 2 lights on each of the 2 topmost boxes:
Power input
Power output

So if the switch for the box in question is turned off, neither Power input and Power output will light up. If the switch is turned on but fuse is not yet fixed, or the box hasn't been reset with the reset button, only "Power input" should light (while the red light is on).
If the box in question have been fully fixed and the red light is off and the switch for the box is on, both "Power input" and "Power output" can be on.

**Comment by Yuccaa** [comment]
Fixed.
