### ISSUE TITLE
There's an invisible wall blocking movement on this railing in office

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#578]
![20160510190501_1](https://cloud.githubusercontent.com/assets/3168386/15153519/3252180a-16e2-11e6-8ade-210b00468d0f.jpg)
![20160510190512_1](https://cloud.githubusercontent.com/assets/3168386/15153523/33f6e000-16e2-11e6-9a5c-a1e1c464aad2.jpg)

**Comment by Yuccaa** [comment]
Fixed.
