### ISSUE TITLE
Stuck in pipe on chapter 3

### ISSUE THREAD

**Issue by auriamg** [loiste-interactive/infra-issues#584]
In chapter 3, where there is the water pipes puzzles, you need to shut off all water flow and then go down a pipe that says "entrance", with a ladder inside. However I am unable to go to the bottom, I can get below the ladder but end floating in mid-air without ever being able to reach the bottom of the pipe (see attached screenshots) and there I get stuck and am unable to progress

![infra1](https://cloud.githubusercontent.com/assets/4296971/15627949/2cec7598-24c2-11e6-9cc9-acb564c5c9dd.jpg)
![infra2](https://cloud.githubusercontent.com/assets/4296971/15627950/2cec9a8c-24c2-11e6-85b8-d124a9e7b76a.jpg)
![infra3](https://cloud.githubusercontent.com/assets/4296971/15627948/2cec42f8-24c2-11e6-8698-4ed19c988b8b.jpg)

**Comment by Yuccaa** [comment]
Have you tried crouching? Seems to solve the problem.

**Comment by auriamg** [comment]
Indeed crouching did help, thanks

**Comment by Yuccaa** [comment]
Fixed.
