### ISSUE TITLE
watertreatment: Floating rack

### ISSUE THREAD

**Issue by Sidewinder53** [loiste-interactive/infra-issues#585]
![20160529154449_1](https://cloud.githubusercontent.com/assets/19623985/15634317/404c37f4-25c1-11e6-9838-8f8eec8d9088.jpg)
![20160529154453_1](https://cloud.githubusercontent.com/assets/19623985/15634318/404daa94-25c1-11e6-8858-3e4ddb464f4a.jpg)

That's pretty much everything you need to know ;)

**Comment by Zuntti** [comment]
Fixed.
