### ISSUE TITLE
tunnel2: feedback

### ISSUE THREAD

**Issue by CorruptComputer** [loiste-interactive/infra-issues#588]
These wires don't make sense, because these are the manual valves:
![20160601164357_1](https://cloud.githubusercontent.com/assets/5573038/15727027/bb2ab4d2-2819-11e6-8052-d98f25f0bc56.jpg)
They should be moved to here, and have an electronic valve or some sort of indicator on whether it is open or not:
![20160601164418_1](https://cloud.githubusercontent.com/assets/5573038/15727046/d5d64be8-2819-11e6-95c8-4bf570b257a9.jpg)
---
This note is almost unreadable:
![20160601164501_1](https://cloud.githubusercontent.com/assets/5573038/15727077/058dccc6-281a-11e6-803d-5b0af5d1915d.jpg)
---
This should probably be a camera target:
![20160601164524_1](https://cloud.githubusercontent.com/assets/5573038/15727090/12c64062-281a-11e6-9e7b-0e750744d935.jpg)
---
The boxes around the red pipe look out of place:
![20160601164706_1](https://cloud.githubusercontent.com/assets/5573038/15727107/2c96360a-281a-11e6-8651-524070156f49.jpg)
![20160601164600_1](https://cloud.githubusercontent.com/assets/5573038/15727108/2c9666d4-281a-11e6-98cf-85b467298cb8.jpg)
---
There is no real reason for one light to be red and the other to be green, maybe make both green and have it go on/off with the flow of the pipe?
![20160601164735_1](https://cloud.githubusercontent.com/assets/5573038/15727171/7dedc82e-281a-11e6-972a-d3cb7f994b11.jpg)
![20160601164733_1](https://cloud.githubusercontent.com/assets/5573038/15727172/7defba30-281a-11e6-98d8-84bd521e2cd7.jpg)
---
These wires disappear:
![20160601164755_1](https://cloud.githubusercontent.com/assets/5573038/15727183/8c9a6ff8-281a-11e6-8c14-324a7fe98db8.jpg)
![20160601164803_1](https://cloud.githubusercontent.com/assets/5573038/15727182/8c99e86c-281a-11e6-975e-a09e57efe566.jpg)
---
The wires on the ceiling are being pushed by wind:
![20160601164915_1](https://cloud.githubusercontent.com/assets/5573038/15727206/a80bce94-281a-11e6-8b51-b869f91b4055.jpg)
---
Some of the piping in this room is confusing and out of place:
![20160601164954_1](https://cloud.githubusercontent.com/assets/5573038/15727234/c99557a6-281a-11e6-96b0-c5cc7a466eea.jpg)
Also, it seems weird to have blue pipes going into the red pipes pool:
![20160601165013_1](https://cloud.githubusercontent.com/assets/5573038/15727233/c992d738-281a-11e6-90f7-86132bf4b237.jpg)
---
The light over this door should be switched to the green one because the door is open:
![20160601165036_1](https://cloud.githubusercontent.com/assets/5573038/15727242/da456fb4-281a-11e6-8b8b-2e16d7107ce5.jpg)
---
There is no indicator that this is on when you press the button, maybe make the needle move and a sound?
![20160601165119_1](https://cloud.githubusercontent.com/assets/5573038/15727259/f9265c2c-281a-11e6-81d3-c6f4714ca938.jpg)

**Comment by CorruptComputer** [comment]
Another small note for the confusing piping, most placed IRL would have identical layouts for something such as the pools in that room, in order to make it easier to maintenence. In INFRA each pool has its own kind of piping and some pools have more/less pipes than others.

**Comment by madattak** [comment]
All pools having the same piping would feel pretty cut and paste. For most people it probably looks better like this. The piping in the pools never really struck me as odd at all to be honest. The chlorine tank not reacting to be switched on was noticeable for me though

**Comment by aleksijuvani** [comment]
I've opened separate issues for all of these. I didn't for the note, because that is intended to be almost unreadable.
