### ISSUE TITLE
Annoying part of game, music drops, bug in steering

### ISSUE THREAD

**Issue by mpeltomaa** [loiste-interactive/infra-issues#59]
Part where you need to ride with pallet(?) thru tunnels is annoying. And this is for couple of reasons:

1. It's too dark and hard to see where are the edges of pallet.
2. Steering is awkward.

If you drop in the water, game throws you back a bit and you can try again. Thats ok, but after spawning again pallet won't steer enough to get thru that hole (see picture). Unless you first drive a bit to right (wrong way) and then back to left. If you try to steer left when game starts, it won't go left enough and will hit of the wall.
![pallet_1](https://cloud.githubusercontent.com/assets/6035374/10870748/155bca68-80db-11e5-8e19-33e476ffcc5d.jpg)

And if you drop in the water, even once, music is lost.

End of this part (where is rock based tunnel), it is too dark (see picture 2).

![pallet2](https://cloud.githubusercontent.com/assets/6035374/10870752/183bcda0-80db-11e5-829d-42caed5fdd6a.jpg)

**Comment by Oskutin** [comment]
Tunnel is now brighter.
Strafe/steer speed is now little higher.
Music problem is soon fixed too, tracked at #34
