### ISSUE TITLE
The player probably shouldn't yell anything after pulling the fire alarm in tunnel2

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#593]
I mean, what did you expect to happen?

**Comment by aleksijuvani** [comment]
![20160604152952_1](https://cloud.githubusercontent.com/assets/3168386/15799554/31a189d2-2a69-11e6-8d7b-035c42498b86.jpg)

**Comment by madattak** [comment]
Disagree. Made me laugh.

**Comment by CorruptComputer** [comment]
Maybe a "Shit, that wasn't the lights" comment would be better?

**Comment by aleksijuvani** [comment]
Yeah, that's funny. Could work.

**Comment by aleksijuvani** [comment]
Done.
