### ISSUE TITLE
tunnel2 → tunnel3 level transition can result in the player getting stuck

### ISSUE THREAD

**Issue by madattak** [loiste-interactive/infra-issues#596]
While attempting to get the 'Better than before' achievement  (Didn't get it :( )  when I went through the vents, after the loading screen I was frozen in place, and could only turn on the spot and not move.
I press 'Restart from most recent Save' and that just put me in a black void with a sun and the wind sound playing. 
Save file included. 
[76561198035632014.zip](https://github.com/loiste-interactive/infra-issues/files/305089/76561198035632014.zip)

**Comment by aleksijuvani** [comment]
Thanks for providing the saved games. Looks like the player can get stuck inside the vent after the level transition if he's hugging the wall and moving towards it just before the level changes.

![20160608205950_1](https://cloud.githubusercontent.com/assets/3168386/15905100/3d4e4080-2dbc-11e6-984e-1feae0fdc2f3.jpg)

Loading the most recent saved game afterwards indeed places the player in the void:

![20160608205957_1](https://cloud.githubusercontent.com/assets/3168386/15905102/3f88d482-2dbc-11e6-95c1-ca3cd59fec4f.jpg)

**Comment by madattak** [comment]
Is there anyway to restore my save?

**Comment by madattak** [comment]
Is there some way to restore my save?

**Comment by aleksijuvani** [comment]
Remove `autosave.sav`, and then rename `autosave01.sav` to `autosave.sav`. Go to the main menu and load the autosave.

This should put you in the previous level, just before the level change.

**Comment by Yuccaa** [comment]
Fixed.
