### ISSUE TITLE
Player can get stuck behind this tree in reserve3

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#602]
![20160614192721_1](https://cloud.githubusercontent.com/assets/3168386/16050899/17eb31e6-3266-11e6-91d7-bc7467626889.jpg)
![20160614192713_1](https://cloud.githubusercontent.com/assets/3168386/16050902/192aff46-3266-11e6-8521-64fdca2b6c69.jpg)

**Comment by Yuccaa** [comment]
Fixed.
