### ISSUE TITLE
The autosave in reserve2 just before the control room keeps getting triggered while standing in the trigger

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#608]

**Comment by aleksijuvani** [comment]
Same issue with the autosave at the security door control panel.

![20160707195439_1](https://cloud.githubusercontent.com/assets/3168386/16661703/d52e6368-447c-11e6-8de1-828d147e1ce6.jpg)

**Comment by aleksijuvani** [comment]
Here's a picture of the control room autosave trigger as well.

![20160707195840_1](https://cloud.githubusercontent.com/assets/3168386/16661774/3c1bf676-447d-11e6-84e8-0b36285a5da6.jpg)

**Comment by Yuccaa** [comment]
Fixed.
