### ISSUE TITLE
The player shouldn't be able to climb on top of the car in reserve1

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#609]
![20160616130458_1](https://cloud.githubusercontent.com/assets/3168386/16115346/1552639a-33cf-11e6-879a-ed4db09a5e7a.jpg)
![20160616130507_1](https://cloud.githubusercontent.com/assets/3168386/16115349/17090392-33cf-11e6-81f2-2a13140cc4e4.jpg)

**Comment by Yuccaa** [comment]
Fixed.
