### ISSUE TITLE
This geocache in reserve1 is really unfortunately placed

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#610]
![20160616130517_1](https://cloud.githubusercontent.com/assets/3168386/16115369/3bec58a8-33cf-11e6-9f84-4da92596dffc.jpg)

Most players seem to pick it up during the phone call, which doesn't trigger the geocache monologue from the player. They have no idea what they just picked up.

It might be better to move this to the other side of the bridge or perhaps remove it completely.

**Comment by Yuccaa** [comment]
Moved it to the other side of the bridge, and moved the stuff there to this side.

**Comment by aleksijuvani** [comment]
This is still an issue. Players still pick it up during the phone call. Should be removed entirely.

**Comment by aleksijuvani** [comment]
This is also an issue with the batteries. We shouldn't have any pickupable objects before the power plant.

**Comment by Yuccaa** [comment]
Changed the cache to be better hidden. Removed batteries from before the powerplant.
