### ISSUE TITLE
This camera target in reserve3 can be photographed from a weird angle

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#613]
![20160618214557_1](https://cloud.githubusercontent.com/assets/3168386/16173420/f13df1d6-35a9-11e6-8524-32004789f8fa.jpg)
![20160618214554_1](https://cloud.githubusercontent.com/assets/3168386/16173421/f265a34c-35a9-11e6-8573-e266b5d3458f.jpg)

This could be solved by placing triggers on the catwalk and next to the hole to enable/disable the camera target.

**Comment by Yuccaa** [comment]
Fixed.
