### ISSUE TITLE
This door frame in office can be used by the player

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#615]
![20160619041915_1](https://cloud.githubusercontent.com/assets/3168386/16176890/818f9d14-3624-11e6-8986-43264c01d00c.jpg)

**Comment by aleksijuvani** [comment]
I've added a hack that fixes this for now, but it really should be fixed in the map at some point.

**Comment by Yuccaa** [comment]
Fixed.
