### ISSUE TITLE
The latched door in sewer can be opened from the wrong side

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#618]
![20160619143233_1](https://cloud.githubusercontent.com/assets/3168386/16177056/b83e26ea-362a-11e6-8776-163e2b98b5e6.jpg)
![20160619143241_1](https://cloud.githubusercontent.com/assets/3168386/16177057/b95fd9ba-362a-11e6-988a-d2d1d29d034b.jpg)
![20160619143243_1](https://cloud.githubusercontent.com/assets/3168386/16177058/ba7ac4fe-362a-11e6-9262-d5986e52ef3e.jpg)

**Comment by Yuccaa** [comment]
Fixed.
