### ISSUE TITLE
The game freezes periodically!

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#62]
Every time I begin a chapter, after some time the game gets stuck and does not respond: I can see only the current frame and I can't ctrl+tab to exit, only ctrl+alt+canc works.
In the chapter  'Forgotten World' it gave me enough time to complete tunnel1 before it crashed at the beginning of tunnel2; but in the chapter 'Just Another Day at Work', which the first time seemed to work well, it crashes systematically after only 3-4 seconds!

I can't understand what causes this problem but I don't believe it's related to something I explicitly do in the game because it happens in very different moments (from exeption of the 3-4 seconds one in chapter 2)

**Comment by aleksijuvani** [comment]
Apparently this is something that can happen if Steam is not running. Did you launch the game through Steam and have Steam running on the background?

The game should create a `mdmp` file each time it crashes. You can find those if you right-click the game on Steam, select "Properties", then "Local Files" and "Browse Local Files". If you could upload those `mdmp` files somewhere (or just mail them to me at aleksi@loisteinteractive.com), I could take a look at why it's crashing.

Could you also post your system specs?

**Comment by Gheppio** [comment]
I launch the game through Steam and have it running with its overlay, I'll send you the crash reports but I can't find this mdmp files, what is their path from infra\ ?

**Comment by aleksijuvani** [comment]
They should be in the same folder as `infra.exe`. If they are not created that could be a bit problematic. Can you send me your system specs?

**Comment by Gheppio** [comment]
Seems that are not created!
![screenshot_20151101214244](https://cloud.githubusercontent.com/assets/15571788/10871231/8a5cd69e-80e1-11e5-89ea-14efddc388d7.png)
My system specs are:
![screenshot_20151101214349](https://cloud.githubusercontent.com/assets/15571788/10871235/a7c2d72e-80e1-11e5-9f60-aeb92e393c31.png)

**Comment by Gheppio** [comment]
A littile update on this problem:
If I verify the game's cache after the crashes it says that one file hasn't been convalidated, but I can't know which file is.
I also tried to run the application as administrator and with compatibility mode for older windows versions but the problem persisted.

A secondary problem: For now I have also the total sound problem #42 but for me  -dev + F1 didn't work at all in order to open the console; I gained access to the console window only with the launch option  -console and rebuilt audio cache manually (btw wery good audio! Since now I had to imagine the sounds from the error messages!)

I believed that the two problems might be correlated but the crashes are still happening and now I can even hear clearly that the audio is looping!

**Comment by aleksijuvani** [comment]
I have one thing that you could try. Does the game still crash if you start the levels from the console (with the `map` command) **instead of** from the main menu? You should get an autocomplete list of all maps once you type in `map` followed by a space.

**Comment by aleksijuvani** [comment]
Oh, what you could also do is add `-condebug` to the launch options on Steam. When it crashes, send me the `infra/console.log` file. You can put it up on [pastebin](http://pastebin.com/) or email it to me at aleksi@loisteinteractive.com.

**Comment by Gheppio** [comment]
It crashes even if I run the maps from the console, but now at least I can test all the maps!
I'm sending you two different console logs.

**Comment by aleksijuvani** [comment]
Got the logs. Can you also send me [a full system report by following these instructions?](https://support.steampowered.com/kb_article.php?ref=1376-WTZN-9132) (except that instead of sending it to Steam Support, send it to my email!)

**Comment by Gheppio** [comment]
Sent!

**Comment by aleksijuvani** [comment]
Got it, thanks. One more thing. Can you paste me the output of `mat_info` from the console?

**Comment by Gheppio** [comment]
ShaderAPI: shaderapidx9.dll
Shader API Driver Info:

Driver : nvumdshim.dll Version : 2533352100660300
Driver Description :  Intel(R) HD Graphics 4000
Chipset version 32902 358 361173059 9

Display mode : 1366 x 768 @60Hz (BGRX8888)
Vertex Shader Version : 3.0 Pixel Shader Version : 3.0

Device Caps :
CANBLTSYSTONONLOCAL  Y  CANRENDERAFTERFLIP  Y  HWRASTERIZATION  Y 
HWTRANSFORMANDLIGHT  Y  NPATCHES  N  PUREDEVICE  Y 
SEPARATETEXTUREMEMORIES  N  TEXTURENONLOCALVIDMEM  Y  TEXTURESYSTEMMEMORY  N 
TEXTUREVIDEOMEMORY  Y  TLVERTEXSYSTEMMEMORY  Y  TLVERTEXVIDEOMEMORY  Y 

Primitive Caps :
BLENDOP  Y  CLIPPLANESCALEDPOINTS  N  CLIPTLVERTS  Y 
COLORWRITEENABLE  Y  MASKZ  Y  TSSARGTEMP  Y 

Raster Caps :
FOGRANGE  Y  FOGTABLE  Y  FOGVERTEX  Y  ZFOG  Y  WFOG  Y 
MIPMAPLODBIAS  Y  WBUFFER  N  ZBIAS  Y  ZTEST  Y 
Size of Texture Memory : -2097152 kb
Max Texture Dimensions : 8192 x 8192
Max Texture Aspect Ratio : *8192*
Max Textures : 8

Texture Caps :
ALPHA  Y  CUBEMAP  Y  MIPCUBEMAP  Y  SQUAREONLY  N 
vendor id: 0x8086
device id: 0x166
SHADERAPI CAPS:
m_NumSamplers: 16
m_NumVertexSamplers: 4
m_HasSetDeviceGammaRamp: no
m_SupportsPixelShaders_2_b: yes
m_SupportsShaderModel_3_0: no
m_SupportsCompressedVertices: 1
m_bSupportsAnisotropicFiltering: yes
m_nMaxAnisotropy: 16
m_MaxTextureWidth: 8192
m_MaxTextureHeight: 8192
m_MaxTextureAspectRatio: 8192
m_MaxPrimitiveCount: 16777215
m_ZBiasAndSlopeScaledDepthBiasSupported: yes
m_NumPixelShaderConstants: 32
m_NumVertexShaderConstants: 256
m_NumBooleanVertexShaderConstants: 16
m_NumIntegerVertexShaderConstants: 16
m_TextureMemorySize: -2147483648
m_MaxNumLights: 4
m_MaxVertexShaderBlendMatrices: 53
m_SupportsMipmappedCubemaps: yes
m_nDXSupportLevel: 92
m_PreferDynamicTextures: yes
m_MaxUserClipPlanes: 6
m_SupportsSRGB: yes
m_HDRType: HDR_TYPE_INTEGER
m_UseFastClipping: no
m_pShaderDLL: 
m_bNeedsATICentroidHack: no
m_bDisableShaderOptimizations: no
m_MaxSimultaneousRenderTargets: 4
m_bPreferZPrepass: no
m_bSuppressPixelShaderCentroidHackFixup: no
m_bPreferTexturesInHWMemory: no
m_bPreferHardwareSync: yes
m_bUnsupported: no

**Comment by aleksijuvani** [comment]
Thanks for bearing with me!

This looks like an Nvidia Optimus bug. The game is using your integrated graphics instead of the discrete graphics card. This wouldn't normally be a problem (except for a performance problem), but it looks like your integrated graphics don't support Shader Model 3 which INFRA requires to run properly.

It looks like you have Secure Boot enabled. Does disabling Secure Boot from your BIOS fix the issue? Does `mat_info` still report "Intel(R) HD Graphics 4000" as "driver description" afterwards?

**Comment by Gheppio** [comment]
You're right, with secure boot disable it says NVIDIA geforce gt 740M!

**Comment by aleksijuvani** [comment]
Awesome! Did that fix the crashes as well?

**Comment by Gheppio** [comment]
I still don't know, lately it gave me more time before crashing so i can't know immediatly if the problem is still persisting; I'll let you know if the situation gets better!

**Comment by Gheppio** [comment]
Good news!
Now I have completed different maps and played the game for many hours normally.
I feel I can say that the problem has been SOLVED!

**Comment by aleksijuvani** [comment]
In the next update, I've added an error message to startup if Shader Model 3 support isn't detected. The error message will tell you to disable Secure Boot if you're running on a system with Nvidia Optimus or the like.
