### ISSUE TITLE
If you open the pipe room flood door, go turn off the fuse, turn it back on, and wait until the flood door has slid down, the valve can't be used anymore

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#620]
As seen in [this playthrough](https://www.youtube.com/watch?v=7OykZgOfQmU). Steps to reproduce the issue:

1. Solve the door puzzle.

  ![20160625212027_1](https://cloud.githubusercontent.com/assets/3168386/16358415/f90008f2-3b1a-11e6-943e-34b5aa3053a0.jpg)

2. Turn off pipe A2.

  ![20160625212054_1](https://cloud.githubusercontent.com/assets/3168386/16358418/0798590a-3b1b-11e6-84e3-0db482b38752.jpg)

3. Open the pipe room flood door.

  ![20160625212108_1](https://cloud.githubusercontent.com/assets/3168386/16358419/090c5340-3b1b-11e6-8b66-bef2b980af3e.jpg)

4. Turn off the pipe room fuse.

  <img src="https://cloud.githubusercontent.com/assets/3168386/16358421/0ba1de7c-3b1b-11e6-93e7-a4ec0d2cc7a1.jpg" width=316> <img src="https://cloud.githubusercontent.com/assets/3168386/16358422/0df4441c-3b1b-11e6-8de2-5a99346b2275.jpg" width=316>

5. Turn on the pipe room fuse and the door begins to slide down.

  <img src="https://cloud.githubusercontent.com/assets/3168386/16358424/11587aec-3b1b-11e6-87b7-8ae036967196.jpg" width=316> <img src="https://cloud.githubusercontent.com/assets/3168386/16358425/1306132c-3b1b-11e6-9c9a-eba262b7ae8d.jpg" width=316>

6. The valve can no longer be used to open the door.

  <img src="https://cloud.githubusercontent.com/assets/3168386/16358427/16b94e30-3b1b-11e6-8fe2-0f402ffb0efa.jpg" width=316> <img src="https://cloud.githubusercontent.com/assets/3168386/16358428/18214f3e-3b1b-11e6-8cd0-d91e0cdb8997.jpg" width=316>

**Comment by Zuntti** [comment]
Fixed.
