### ISSUE TITLE
Signal box repair target never gets triggered

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#621]
As discussed [here](http://steamcommunity.com/app/251110/discussions/0/358415738182820617/). I'm pretty sure this is because it has the "starts disabled" flag.

![20160626121234_1](https://cloud.githubusercontent.com/assets/3168386/16361374/4d59880c-3b97-11e6-8f44-2c54ac28ee67.jpg)

**Comment by Yuccaa** [comment]
Fixed.
