### ISSUE TITLE
reserve2 ↔ reserve3 level transition loop

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#626]
It's possible to get stuck in a level transition loop for a short while if the player stands on the very edge of the trigger_changelevel in reserve2 or in reserve3. Afterwards, the player will be frozen in place and unable to move.

http://steamcommunity.com/app/251110/discussions/1/365172408531492518/

**Comment by Yuccaa** [comment]
Fixed.
