### ISSUE TITLE
These pipes in tunnel2 need player clips to make them easier to cross without getting stuck

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#629]
![20160715145929_1](https://cloud.githubusercontent.com/assets/3168386/16873603/01e3b61c-4a9d-11e6-9d21-fd9e42a53a00.jpg)
![20160715145804_1](https://cloud.githubusercontent.com/assets/3168386/16873605/048e1664-4a9d-11e6-9b38-bbd849cc1cd2.jpg)

Here are some spots that it's possible to get stuck on them:

![20160715145925_1](https://cloud.githubusercontent.com/assets/3168386/16873619/1b1a885e-4a9d-11e6-8152-f42955a94553.jpg)
![20160715145816_1](https://cloud.githubusercontent.com/assets/3168386/16873620/1b1ea16e-4a9d-11e6-9390-ddbff4858a77.jpg)

These rocks also need to have their collisions disabled:

![20160715145826_1](https://cloud.githubusercontent.com/assets/3168386/16873623/22727904-4a9d-11e6-97f4-147e7d4d73f2.jpg)

**Comment by Yuccaa** [comment]
Fixed.
