### ISSUE TITLE
Possibly last part (?) of tunnel with pallet ride - no light.

### ISSUE THREAD

**Issue by mpeltomaa** [loiste-interactive/infra-issues#63]
After loading, game gives 3 "switch"-sounds and no light. Impossible to play.

**Comment by Oskutin** [comment]
With developer console and typing in "map infra_c4_m4_tunnel4" from menu you can skip the raft ride.

**Comment by aleksijuvani** [comment]
Duplicate of #36 and #39. Both are fixed in the next update.
