### ISSUE TITLE
Chlorine tank in tunnel2 needs to provide better feedback that it's turned on

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#631]
Original issue #588. There is no indicator that this is on when you press the button, maybe make the needle move and a sound?

![20160601165119_1](https://cloud.githubusercontent.com/assets/5573038/15727259/f9265c2c-281a-11e6-81d3-c6f4714ca938.jpg)

**Comment by Yuccaa** [comment]
Fixed.
