### ISSUE TITLE
Nonsensical wires in tunnel2

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#632]
Original issue #588. These wires don't make sense, because these are the manual valves:

![20160601164357_1](https://cloud.githubusercontent.com/assets/5573038/15727027/bb2ab4d2-2819-11e6-8052-d98f25f0bc56.jpg)

They should be moved to here, and have an electronic valve or some sort of indicator on whether it is open or not:

![20160601164418_1](https://cloud.githubusercontent.com/assets/5573038/15727046/d5d64be8-2819-11e6-95c8-4bf570b257a9.jpg)

**Comment by Zuntti** [comment]
Removed green wires.
