### ISSUE TITLE
Boxes around the red pipe in tunnel2 look out of place

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#633]
Original issue #588. The boxes around the red pipe look out of place:

![20160601164706_1](https://cloud.githubusercontent.com/assets/5573038/15727107/2c96360a-281a-11e6-8651-524070156f49.jpg)
![20160601164600_1](https://cloud.githubusercontent.com/assets/5573038/15727108/2c9666d4-281a-11e6-98cf-85b467298cb8.jpg)

**Comment by Zuntti** [comment]
Fixed.
