### ISSUE TITLE
These indicators in tunnel2 should be functional

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#634]
Original issue #588. There is no real reason for one light to be red and the other to be green, maybe make both green and have it go on/off with the flow of the pipe?

![20160601164735_1](https://cloud.githubusercontent.com/assets/5573038/15727171/7dedc82e-281a-11e6-972a-d3cb7f994b11.jpg)
![20160601164733_1](https://cloud.githubusercontent.com/assets/5573038/15727172/7defba30-281a-11e6-98d8-84bd521e2cd7.jpg)

**Comment by Zuntti** [comment]
Fixed.
