### ISSUE TITLE
Disappearing wires in tunnel2

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#635]
Original issue #588. These wires disappear:

![20160601164755_1](https://cloud.githubusercontent.com/assets/5573038/15727183/8c9a6ff8-281a-11e6-8c14-324a7fe98db8.jpg)
![20160601164803_1](https://cloud.githubusercontent.com/assets/5573038/15727182/8c99e86c-281a-11e6-975e-a09e57efe566.jpg)

**Comment by Zuntti** [comment]
Fixed.
