### ISSUE TITLE
Confusing piping in tunnel2

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#638]
Original issue #588. Some of the piping in this room is confusing and out of place:

![20160601164954_1](https://cloud.githubusercontent.com/assets/5573038/15727234/c99557a6-281a-11e6-96b0-c5cc7a466eea.jpg)

Also, it seems weird to have blue pipes going into the red pipes pool:

![20160601165013_1](https://cloud.githubusercontent.com/assets/5573038/15727233/c992d738-281a-11e6-90f7-86132bf4b237.jpg)

**Comment by Zuntti** [comment]
Changed pipe color.
