### ISSUE TITLE
Forklift ignition in sewer shouldn't be useable after the forklift is running

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#639]
![20160718212047_1](https://cloud.githubusercontent.com/assets/3168386/16925617/af18b26e-4d2d-11e6-8314-b59de7905ed2.jpg)

**Comment by Yuccaa** [comment]
Fixed.

**Comment by aleksijuvani** [comment]
Now when you turn on the forklift, it also immediately uses the lever with the same button press.

**Comment by Yuccaa** [comment]
Fixed that too.
