### ISSUE TITLE
Heavy Industry of the Past - stuck

### ISSUE THREAD

**Issue by mpeltomaa** [loiste-interactive/infra-issues#64]
Because i was unable to play previous part to end (due to black screen) i jumped to Heavy Industry of the Past. Maybe i am just blind, but I can't find way out / continue. Three buttons, none of those work (buttons are on wall but not highlighted and not possible to press). Two buttons are side by side and third one is with large door and green light. All buttons are disabled (no button sound, no animation, no highlight). If i go upstairs (ladders on wall), there is door with read light (locked), to the left seems to be door out (but closed) and to the right there is door which is also closed (but not highlighted). Do i miss something ?

**Comment by Oskutin** [comment]
There should be keys in the upper levels pallet jack on the heavy metal door on the right.

**Comment by Oskutin** [comment]
Keys are moved to more easier-to-notice location.
