### ISSUE TITLE
After unlocking a locked door, the padlock use highlights reappear if the door is closed

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#642]
Can be fixed with the new `infra_use_highlight_control` entity. Looks like the padlock model is only used in `reserve1`, `reserve2`, `tower` and `sewer`.

**Comment by Yuccaa** [comment]
Fixed reserve1.

**Comment by Yuccaa** [comment]
Fixed tower.

**Comment by Yuccaa** [comment]
Fixed reserve2.

**Comment by Yuccaa** [comment]
Fixed sewer.
