### ISSUE TITLE
It shouldn't be possible to get on top of this red pipe in tunnel2

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#646]
It's pointless and it makes the instant death trigger way too noticeable.

![20160725232741_1](https://cloud.githubusercontent.com/assets/3168386/17116246/8d499d46-52bf-11e6-88ff-c010e21ad5cd.jpg)
![20160725232747_1](https://cloud.githubusercontent.com/assets/3168386/17116248/903b0922-52bf-11e6-97b5-19806c573328.jpg)

Going on top of this rock will kill you:

![20160725232750_1](https://cloud.githubusercontent.com/assets/3168386/17116250/9166c1ce-52bf-11e6-9d90-a62e2b761e29.jpg)

Also, this cliff is accessible, but going there will kill you:

![20160725232805_1](https://cloud.githubusercontent.com/assets/3168386/17116258/9c4f7bee-52bf-11e6-87b0-66dd2526cf6f.jpg)

**Comment by Yuccaa** [comment]
Changed pipe elevation to make the drop from it higher.
