### ISSUE TITLE
office : Doors locked open

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#651]
I know the main entrance doors are supposed to be borked, but just in case, these doors can't be closed once open

Main entrance
![20160726002910_1](https://cloud.githubusercontent.com/assets/15633807/17121059/1a37cb18-52d1-11e6-971e-1dc017d839bc.jpg)

Side entrance (near IT Dept.)
![20160726002939_1](https://cloud.githubusercontent.com/assets/15633807/17121066/20a8a5bc-52d1-11e6-952d-7f6a13785705.jpg)

**Comment by Yuccaa** [comment]
Fixed.
