### ISSUE TITLE
Some gates in tunnel2 are unuseable

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#657]
![20160726142353_1](https://cloud.githubusercontent.com/assets/3168386/17136188/a255a13a-533c-11e6-92f5-ad0e9b178181.jpg)
![20160726142401_1](https://cloud.githubusercontent.com/assets/3168386/17136189/a272d3a4-533c-11e6-8788-5883e5ad7b8c.jpg)

They should be useable but locked, to be consistent with other gates in the game. They might need some indication that they can never be unlocked though.

**Comment by Yuccaa** [comment]
Fixed.
