### ISSUE TITLE
reserve1 - Oddly slow movement / Getting stuck under the bridge by levelspawn

### ISSUE THREAD

**Issue by Dmck2b** [loiste-interactive/infra-issues#66]
Tried to crouch under the bridge accessible by turning left at reserve1's spawn, intermittently I was moving at a significantly reduced speed and in one case I was stuck in the level geometry and had to exit to the main menu. Unable to find a set of steps that will cause this to happen every time, thought it may be connected to the angle you approach it at.

https://www.youtube.com/watch?v=lNpakP8-p8A - Slow movement / some glitchy clipping

https://www.youtube.com/watch?v=0JhMBiIMgU0 - Recording of where I got stuck

**Comment by Zuntti** [comment]
Fixed in the next update.
