### ISSUE TITLE
reserve2 : Model cubemaps

### ISSUE THREAD

**Issue by Zuntti** [loiste-interactive/infra-issues#663]
![20160729101237_1](https://cloud.githubusercontent.com/assets/5405170/17243911/c0c7574c-5587-11e6-9739-2e846c0670a4.jpg)
![20160729101312_1](https://cloud.githubusercontent.com/assets/5405170/17243914/c2968a84-5587-11e6-96b9-a7c1c1ad4dcd.jpg)

**Comment by Yuccaa** [comment]
Fixed.
