### ISSUE TITLE
Fresh Water: Unable to pickup keycard

### ISSUE THREAD

**Issue by mpeltomaa** [loiste-interactive/infra-issues#67]
Keycard in drawer is not possible to pickup. It is very hard to get it highlighted, when it happens I can try to get it but it is not possible. Only drawer goes back to closed state.

![keycard](https://cloud.githubusercontent.com/assets/6035374/10871608/4df49558-80f4-11e5-9573-2f681dd0ae0d.jpg)

**Comment by Yuccaa** [comment]
Fixed.
