### ISSUE TITLE
reserve2 synchroscope functionality isn't very self-explainatory

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#673]
![20160729134056_1](https://cloud.githubusercontent.com/assets/3168386/17246872/8893e920-5597-11e6-98fa-bc568db7ca0c.jpg)

Probably needs some indicator lights? Or make this manually synchronizable? Needs an indication when it can't be used too.

**Comment by Zuntti** [comment]
Added lights.
