### ISSUE TITLE
office Unloaded level visible

### ISSUE THREAD

**Issue by Sidewinder53** [loiste-interactive/infra-issues#680]
![251110_20160730014252_1](https://cloud.githubusercontent.com/assets/19623985/17266400/1b36253a-55f8-11e6-89c8-46aacd39ea12.png)
The entrance to the unloaded level is replaced by a plain wall, is it possible to hide this mechanic like keeping a small chunk of the level loaded or something like this?

**Comment by Yuccaa** [comment]
I'm labeling this _wontfix_ as this is a minor issue, and I already tried various solutions to fix this in the past. The performance drop would be too much if that room was only partially visible.
