### ISSUE TITLE
office Minor graphical glitch

### ISSUE THREAD

**Issue by Sidewinder53** [loiste-interactive/infra-issues#684]
![251110_20160730020256_1](https://cloud.githubusercontent.com/assets/19623985/17266556/ebdfba42-55f9-11e6-8907-583145cf8756.png)
_It's a solid surface if you look on it from above, but if you crouch you can partly see trough it._

I hope you don't hate me for submitting such minor bugs, but if I can find them I'm sure someone else will do so as well.

**Comment by aleksijuvani** [comment]
> I hope you don't hate me for submitting such minor bugs, but if I can find them I'm sure someone else will do so as well.

Don't worry about it! All bug reports are appreciated. We can always mark issues as "wontfix" if we disagree on that they need fixing.

**Comment by Yuccaa** [comment]
Fixed.
