### ISSUE TITLE
Ventilation nozzles in Garage of Office floats in the air

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#685]
Just at the same position as the manhole cover, to the left of the green/black cars:
![20160730143933_1](https://cloud.githubusercontent.com/assets/1034930/17270482/dbbabe5e-5663-11e6-852e-e8274e761eee.jpg)

Near the red pipe:
![20160730144044_1](https://cloud.githubusercontent.com/assets/1034930/17270486/e9c0615c-5663-11e6-99f2-4d8f8de3b946.jpg)

**Comment by Yuccaa** [comment]
Fixed.
