### ISSUE TITLE
Option to disable Motion Blur

### ISSUE THREAD

**Issue by Dmck2b** [loiste-interactive/infra-issues#69]
Similar to the current option to disable Film Grain under "Game" options, could we see an option to disable motion blur?

I know it can be disabled via the console with "mat_motion_blur_enabled 0" but it would be handy to have an options menu toggle to quickly toggle it.

**Comment by shadowsun28** [comment]
Was just going to suggest this.

**Comment by aleksijuvani** [comment]
Added in the next update. This was previously enabled automatically on the "high" and "very high" shader detail levels.
