### ISSUE TITLE
reserve1 : boltcutters missing sound

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#697]
When cutting open the chain at the powerplant, the action is missing sound.
![20160804025945_1](https://cloud.githubusercontent.com/assets/15633807/17388542/2bdaa4f2-59fd-11e6-862e-16753a0fe593.jpg)

**Comment by aleksijuvani** [comment]
Can't reproduce the issue. Is this happening in the playtest branch? There was an issue with some sounds not being played, but it has been fixed in the next update.

**Comment by N-G-Neer** [comment]
Yep, this happened on the playtest branch.

**Comment by aleksijuvani** [comment]
Alright, good to know. Then this is indeed fixed.
