### ISSUE TITLE
The player can flush himself down the toilet

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#698]
![20160804162938_1](https://cloud.githubusercontent.com/assets/3168386/17403497/b9aec2c8-5a60-11e6-8bfd-3a91f4101f71.jpg)

The player can use the toilet lid to force himself down the toilet. Happened in `watertreatment`, but I'm pretty sure this happens in all maps with toilets in them. The toilet lid shouldn't collide with the player and the trigger shouldn't be able to remove players.

**Comment by aleksijuvani** [comment]
Doesn't look like this happens in `tunnel2`.

**Comment by Oskutin** [comment]
Fixed watertreatment
