### ISSUE TITLE
Top of map gets cut off

### ISSUE THREAD

**Issue by CorruptComputer** [loiste-interactive/infra-issues#70]
https://www.youtube.com/watch?v=Xyx4aHrCH9M

**Comment by Oskutin** [comment]
Propably due areaportals not triggering and opening properly.

**Comment by Oskutin** [comment]
Which way did you enter that hall?

**Comment by CorruptComputer** [comment]
From the catwalk that is at the top of the stairs, coming from the gas room.

**Comment by Oskutin** [comment]
Can't reproduce this bug.

**Comment by Oskutin** [comment]
added some extra triggers to open that areaportal.
