### ISSUE TITLE
Game crash when trying to play over RDP

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#700]
I think this needs to be filed upstream to the valve source engine issue tracker.

![screenshot_20160811-120823](https://cloud.githubusercontent.com/assets/1034930/17585606/1f9fcb20-5fbd-11e6-9e17-821e21c83219.png)

**Comment by aleksijuvani** [comment]
Does this happen with Portal 2 or Counter-Strike: Global Offensive as well?

**Comment by sebastiannielsen** [comment]
yes

**Comment by sebastiannielsen** [comment]
Could you atleast file this upstream to Valve's closed dev tracker?

**Comment by aleksijuvani** [comment]
We have no access to Valve's issue tracker. The closest thing to an issue tracker is [this](https://github.com/ValveSoftware/Source-1-Games/issues) and it looks pretty neglected. This issue is very much of an edge case anyway, so I doubt they're interested in fixing it.
