### ISSUE TITLE
These crates should be removed from sewer

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#703]
![20160831175833_1](https://cloud.githubusercontent.com/assets/3168386/18135743/995547c6-6fab-11e6-91b0-836f57ed2cab.jpg)
![20160831175841_1](https://cloud.githubusercontent.com/assets/3168386/18135744/9956477a-6fab-11e6-9ccc-363afa15417a.jpg)
![20160831175838_1](https://cloud.githubusercontent.com/assets/3168386/18135746/997a1308-6fab-11e6-8e1d-f9934056aa48.jpg)

These crates can be used to glitch across the electrified grate, which is what a lot of players seem to do:

![20160831180238_1](https://cloud.githubusercontent.com/assets/3168386/18135761/a530bae4-6fab-11e6-84ce-8e0529bb075b.jpg)

Using the crates to get across the electrified grate is very finicky, as there isn't enough overhead space and it's very difficult to get the boxes stay upright. Also, the lamp models collide with the player.

I assume that the intention was so that the player can use these boxes to climb to the alternative route, but you can climb there just fine even without the boxes.

![20160831185359_1](https://cloud.githubusercontent.com/assets/3168386/18135939/4d257c44-6fac-11e6-95ca-7041562084cf.jpg)

**Comment by Yuccaa** [comment]
Removed.

**Comment by BigJim123** [comment]
Does this really need to be removed?  I understand wanting players to solve puzzles the intentional way, but if they decide to do it in a way that's clearly unintentional, then isn't that fine too?  In all honesty it also severely limits the speedrun possibilities when things like this are removed, which takes away a fun way to play the game for some people.

**Comment by CorruptComputer** [comment]
@BigJim123 The electrified grate is optional, there's another way through the level (which is actually faster and easier).

**Comment by Yuccaa** [comment]
The problem with the crates was people using them in the wrong place where using them created a lot of problems.

**Comment by Sichelgaita** [comment]
You mean we weren't supposed to use the boxes to get across that electrified floor thing? That's what I always did, I thought that's what they were there for
How were we meant to do the electrified floor route then?
