### ISSUE TITLE
watertreatment : door stuck open

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#717]
![20160907175208_1](https://cloud.githubusercontent.com/assets/15633807/18318955/fd3ed720-7523-11e6-97f3-fb973096b579.jpg)

**Comment by aleksijuvani** [comment]
I can't reproduce this issue on our development branch. Is something special needed to get it stuck? We've done a few bugfixes to doors, so it could be that this is already fixed.

**Comment by N-G-Neer** [comment]
You have to go through tower before. Only way I could reproduce it.

**Comment by aleksijuvani** [comment]
Yeah, I'm able to reproduce it that way as well. Looks like there's something invisible blocking the door. Might be an issue with the transition volume.

![20160908184606_1](https://cloud.githubusercontent.com/assets/3168386/18356260/b1764edc-75f4-11e6-89c4-18770a848d37.jpg)

**Comment by Zuntti** [comment]
Fixed.
