### ISSUE TITLE
tower : elevator button issue

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#718]
If the player faces the elevator button and press it while the elevator is going down, the player will be pushed back. Doing this repeatedly (or at the right time ?) can even block the elevator a few seconds when entering the building on ground level, where the conveyor belt is very close to the player's head. There's also a weird cool-down effect on this button, as it can't be pressed again right away.
![20160908173320_1](https://cloud.githubusercontent.com/assets/15633807/18355837/b7f9167c-75ea-11e6-858c-6e12f2a81e26.jpg)
![20160908173346_1](https://cloud.githubusercontent.com/assets/15633807/18355840/ba18b9d0-75ea-11e6-926e-1e2c32d79356.jpg)

**Comment by Yuccaa** [comment]
Fixed.
