### ISSUE TITLE
tower : missing checkpoint

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#719]
If you die in the collapsed stairs inside the office building, right after the long catwalk, the player will be sent back to the tower, before the fuse puzzle is solved.

![20160908174014_1](https://cloud.githubusercontent.com/assets/15633807/18355986/51a7bcd8-75eb-11e6-8972-44ed79106fa4.jpg)
![20160908173142_1](https://cloud.githubusercontent.com/assets/15633807/18355906/04be1610-75eb-11e6-97fe-98c9be0e44e8.jpg)

**Comment by aleksijuvani** [comment]
I remember encountering this before, but I'm pretty sure it was only because I was noclipping. Were you noclipping around? It's possible that you might have missed a trigger.

**Comment by N-G-Neer** [comment]
Nope, I was very much clipping around :P

**Comment by Yuccaa** [comment]
Fixed.
