### ISSUE TITLE
Gameplay Bugs-Reserve 1-3

### ISSUE THREAD

**Issue by moebeer2** [loiste-interactive/infra-issues#72]
reserve1:
Under the bridge by the river, I took a picture of the missing material on the pillar. No "Successful Photo" was shown. Walking up hill, had to jump walk to get up. Happens every time. 
By the trailer-wagon outside the first plant, got stuck in the world, was unable to move and get out of area. Had to quit to menu.
Feedback: Was unsure about what to use to cut lock on the door, took a while to find lock cutter.

No noticeable bugs.
Feedback: I liked the design of the level, especially the multiple ways to get to the plant area. The train part was interesting, however I was unsure what I am suppose to do at that point.

reserve2: 
In the plant when turning on the turbines, the switch can be touchy and hard to control. The gauges are slightly hard to read, had to crouch to read them. On the final puzzle, the jumping/climbing mechanics made it difficult to do the puzzle adequately. Boxes kept moving while climbing, causing me to die.
Flashlight-Was unable to reload with batteries even though I had batteries available. In all areas, would not allow to reload past first time. Happens frequently.
Feedback: I like this area, however the puzzle did make it tiresome when dying happened frequently. Music was not playing during Alex's speech, felt that there was space that could be filled with setting music. The lag/lead device was very interesting, will replay to figure out how to do!

**Comment by Yuccaa** [comment]
Note to devs: Reserve1 parts fixed.

**Comment by Oskutin** [comment]
The gauges are now much more easier to read.
