### ISSUE TITLE
reserve1 : weird TV lighting issue

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#721]
![20160915202144_1](https://cloud.githubusercontent.com/assets/15633807/18562515/46952792-7b84-11e6-8b92-5be939ab1fc7.jpg)
![20160915202145_1](https://cloud.githubusercontent.com/assets/15633807/18562516/46cdf900-7b84-11e6-85e5-061d4d40f890.jpg)

From a distance, the abandoned TV goes dark while other nearby objects don't.

**Comment by Zuntti** [comment]
Fixed.
