### ISSUE TITLE
office : Building pathway issue

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#722]
From ground level it looks fine, when you take a bit of altitude not so much :P (Seen from the staircase in floor 7-8)

![20160915200034_1](https://cloud.githubusercontent.com/assets/15633807/18568665/9ab9e4ec-7b9e-11e6-9890-ffd6dc20b9a7.jpg)

**Comment by Oskutin** [comment]
Fixed
