### ISSUE TITLE
watertreatment: picking up the kebab highlights one of the cabinet doors for a split second

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#723]

**Comment by Zuntti** [comment]
Added infra_use_highlight_hint.

**Comment by N-G-Neer** [comment]
Still an issue
![20161024212936_1](https://cloud.githubusercontent.com/assets/15633807/19660659/fd3de144-9a30-11e6-9afa-945de1d78ba9.jpg)

**Comment by Zuntti** [comment]
Fixed.
