### ISSUE TITLE
central : untextured banner

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#728]
![20160925013003_1](https://cloud.githubusercontent.com/assets/15633807/18812091/9b933946-82c8-11e6-83ca-0f8de3cc720a.jpg)
![20160925013006_1](https://cloud.githubusercontent.com/assets/15633807/18812092/9c1fd766-82c8-11e6-9577-7683967dccc6.jpg)

**Comment by Yuccaa** [comment]
Fixed.
