### ISSUE TITLE
metro : use highlight through shelf

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#731]
![20160925001943_1](https://cloud.githubusercontent.com/assets/15633807/18812143/d0694f64-82ca-11e6-9029-628ba5da858e.jpg)
![20160925001942_1](https://cloud.githubusercontent.com/assets/15633807/18812144/d0eb8c72-82ca-11e6-8942-3fc3e9b1788f.jpg)

**Comment by Zuntti** [comment]
Fixed.
