### ISSUE TITLE
stormdrain : possible to dodge incoming trains

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#732]
By hugging the fence on the right, it is possible to dodge the incoming mini trains.

**Comment by aleksijuvani** [comment]
I think this is intended? I've always managed to get away to the other track before they even show up.

**Comment by N-G-Neer** [comment]
I don't know, I always used the recesses on the left.

**Comment by Yuccaa** [comment]
Definitely shouldn't be this way. The player is supposed to take refuge on the recesses.

**Comment by Zuntti** [comment]
Fixed.
