### ISSUE TITLE
bunker : weird blastdoor death

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#733]
![20160924140249_1](https://cloud.githubusercontent.com/assets/15633807/18812161/2d2d7f4a-82cb-11e6-8ff6-655c39515d5e.jpg)
If you try to squeeze inside too early, you will hear a bone-crushed sound, the doors will be blocked but the player won't die immediately. If the player takes a few steps back, the screen fades to black before the player respawns.

**Comment by Yuccaa** [comment]
Fixed.
