### ISSUE TITLE
tower : purpose of keys in office ?

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#734]
![20160924010539_1](https://cloud.githubusercontent.com/assets/15633807/18812171/80021992-82cb-11e6-9a0c-d2c940b07d93.jpg)
![20160924010545_1](https://cloud.githubusercontent.com/assets/15633807/18812172/807939aa-82cb-11e6-8bca-b8d3deafe46b.jpg)

I can't quite remember the purpose of the keys found in this office after getting down from the tower.

**Comment by Yuccaa** [comment]
They are used to open the locked ladder on the side of the gravel collector you're standing on in the last screenshot. Just another way to solve the climbing "puzzle" on the area.
