### ISSUE TITLE
furnace : door button missing own use highlight

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#735]
![20160924002250_1](https://cloud.githubusercontent.com/assets/15633807/18812177/b2afc54c-82cb-11e6-8462-a9615804222f.jpg)
![20160924002254_1](https://cloud.githubusercontent.com/assets/15633807/18812178/b3c875f0-82cb-11e6-8d00-bd0a4278ad40.jpg)

Pressing the use key on the door has no effect, you have to aim at the button to unlock the door.

**Comment by Yuccaa** [comment]
This already been fixed at some point it seems.
