### ISSUE TITLE
tunnel3 : missing photo spot ?

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#736]
I always wondered if this spot was supposed to be a photo spot or not. At least for the broken ladder but I think there are bigger problems here :P 
![20160923233145_1](https://cloud.githubusercontent.com/assets/15633807/18812185/e0a1b35c-82cb-11e6-9075-50d108277a13.jpg)

**Comment by Yuccaa** [comment]
Added.
