### ISSUE TITLE
tunnel2 : Need to crouch for photo target

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#737]
The paper can be read while standing up but the player needs to crouch in order to take a picture.

![20160923231139_1](https://cloud.githubusercontent.com/assets/15633807/18812193/13395388-82cc-11e6-858c-fc7b2ec618a5.jpg)
![20160923231145_1](https://cloud.githubusercontent.com/assets/15633807/18812194/13dfd99c-82cc-11e6-9324-e975af3e76fe.jpg)

**Comment by Yuccaa** [comment]
Fixed.
