### ISSUE TITLE
Can't use PC after restarting -> loading manual save

### ISSUE THREAD

**Issue by NielsGade** [loiste-interactive/infra-issues#741]
infra_c5_m1_watertreatment
Cursor is visible, but I can't interact with the screen
Can press esc and hear the menu button, but can't see them
Can't open console either

**Comment by NielsGade** [comment]
Savegame
[76561197973683528.zip](https://github.com/loiste-interactive/infra-issues/files/491671/76561197973683528.zip)

**Comment by aleksijuvani** [comment]
Same issue as #758.
