### ISSUE TITLE
pressing S on ladder in watertreatment

### ISSUE THREAD

**Issue by NielsGade** [loiste-interactive/infra-issues#742]
http://imgur.com/a/3ko3u

**Comment by sebastiannielsen** [comment]
I think this are fixed ( commit 3753172cf4ff69ada0588ee54bc138bec1b8976b#diff-8b1c3fd0d4a6765c16dfd18509182f9d )

**Comment by aleksijuvani** [comment]
> I think this are fixed ( commit 3753172cf4ff69ada0588ee54bc138bec1b8976b#diff-8b1c3fd0d4a6765c16dfd18509182f9d )

This is a different issue.

**Comment by Zuntti** [comment]
Fixed.
