### ISSUE TITLE
stormdrain : broken transition to cistern

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#743]
[Stormdrain Cistern Transition.txt](https://github.com/loiste-interactive/infra-issues/files/491630/Stormdrain.Cistern.Transition.txt)

When finishing the level, the loading bar completes a few cycles and the the game goes back to the main menu. (Console dump attached)

**Comment by aleksijuvani** [comment]
Looks like the transition is broken. It will occasionally work, but probably not most of the time.

```
Level transition ERROR
Can't find connection to INFRA_c7_m3_stormdrain from INFRA_c7_m4_cistern
Falling back to 'map' command...
```

**Comment by aleksijuvani** [comment]
Fixed.
