### ISSUE TITLE
stormdrain : missing photo spot

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#744]
![20160925133420_1](https://cloud.githubusercontent.com/assets/15633807/18815155/55e5d68c-8328-11e6-95ff-22e8021a1373.jpg)

There should still be a harmless amount of steam coming out of the pipe. The photo spot does not work after closing the pipe, even though the leak is technically still there.
![20160925133803_1](https://cloud.githubusercontent.com/assets/15633807/18815156/577835ee-8328-11e6-9be6-568b20ad285d.jpg)

**Comment by Zuntti** [comment]
Fixed.
