### ISSUE TITLE
metro: the switch control panel can open inside the box

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#746]
![20160925160510_1](https://cloud.githubusercontent.com/assets/3168386/18815430/e4bb367a-8339-11e6-9451-82c0fd5e55ac.jpg)
![20160925160509_1](https://cloud.githubusercontent.com/assets/3168386/18815431/e4bf279e-8339-11e6-90f9-d3fb23ab2e35.jpg)

**Comment by Zuntti** [comment]
Fixed.
