### ISSUE TITLE
Part 2: Random fade to black in second map 

### ISSUE THREAD

**Issue by madattak** [loiste-interactive/infra-issues#749]
After entering the second map in Infa Part 2, going through the small tunnels with the mushrooms in them, my game is randomly fading to black. The screen fades, and sounds stop, then after a few seconds the sound comes back again, and I can hear my character walking around and interacting with stuff. From the sounds I can hear my character has stayed in exactly the same spot, but I cannot see or open the menu. Reloading  does not fix it. Was first triggered by trying to crouch and climb into the side tunnel on the left near the very start of the level.

**Comment by aleksijuvani** [comment]
Do you have a saved game where the screen is black? If you do, could you send that to me?

**Comment by madattak** [comment]
I started a new game and it was fine, I'm pretty sure it's got something to do with trying to walk into that partially blocked tunnel on the left. 

[slot_4.zip](https://github.com/loiste-interactive/infra-issues/files/491777/slot_4.zip)

**Comment by aleksijuvani** [comment]
Did you go back to the previous level at any point in that save?

**Comment by aleksijuvani** [comment]
Fixed. Looks like this was caused by the maintenance tram moving on its own. There was an edge case that wasn't covered by the previous hotfix.
