### ISSUE TITLE
Alt-tabbing while in fullscreen mode results in a black screen on some systems

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#75]

**Comment by Oskutin** [comment]
For me it just takes some time in black screen after alt+tab until the game actually shows up.

**Comment by aleksijuvani** [comment]
According to @paavohuhtala, it might take up to 20 seconds before the game shows up. It looks like this might be only happening when the game is installed on a HDD instead of an SSD.

**Comment by aleksijuvani** [comment]
This was the level transition issue where the levels were missing transitions back to the old level. Not caused by alt-tabbing after all.
