### ISSUE TITLE
bunker : Hammer Valley involvement in powering the bunker could be more clearly informed to the player

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#751]
I can't figure out how to enter the train/crane section of the bunker anymore.

The note in the breakers room says to fix the electrical room outside the bunker but I can only ever get the left switch to work there. I've tried every combination of breaker position too.

Am I missing something ?

**Comment by Oskutin** [comment]
Hammer Valley dam needs to be connected to be operational for enabling the crane section.

**Comment by Yuccaa** [comment]
Maybe this needs to be more clearcly informed to the player?

**Comment by aleksijuvani** [comment]
Yeah, the note in the breaker room isn't exactly clear. It could say something like "the Hammer Valley dam is having problems again so I had to blah blah".

**Comment by aleksijuvani** [comment]
Oh, so there actually is a good note, but it's in the power room just before entering the bunker. The note in the breaker room inside the bunker is referring to that. I thought it meant some separate power station on the surface.

**Comment by N-G-Neer** [comment]
In the electrical room before the bunker, maybe the left switch should be labeled "Onsite Generators" and the right one should be labeled "Hammer Valley Dam (City Grid)" or something similar ?

**Comment by aleksijuvani** [comment]
I think the electrical room before the bunker is fine. The note clearly explains that the other breaker is connected to the Hammer Valley Dam.

What makes this confusing I think is that there's another set of breakers inside the bunker, and those are not labeled at all.

**Comment by aleksijuvani** [comment]
I feel like this is fine now in 2.1.0.
