### ISSUE TITLE
Audio range of radio

### ISSUE THREAD

**Issue by Sidewinder53** [loiste-interactive/infra-issues#753]
_This is a minor gameplay suggestion which is probably subject to personal opinion, so if you think that this is not an issue please just close it, I won't be resentful :)_

![20160925185905_1](https://cloud.githubusercontent.com/assets/19623985/18817825/f3adc478-836a-11e6-8f4b-b6a3243b4cbf.jpg)
This radio here has some weird audio range. I think it would be much more realistic if you would be able to hear the audio in the whole room at medium volume, and as soon as you leave the room the volume drops, depending on the range, pretty quickly.

**Comment by Zuntti** [comment]
Fixed.

**Comment by aleksijuvani** [comment]
This is kind of weird now. Needs a better fix.

**Comment by Yuccaa** [comment]
Still needs work. Has several issues:
a) It shouldn't be audible in the stairway
b) Doesn't turn on again unless the player leaves the room
c) Shouldn't restart when turned off an on again
d) Needs a low quality version to sound more like a radio

**Comment by Zuntti** [comment]
Fixed.
