### ISSUE TITLE
general: Add new levels to README.md

### ISSUE THREAD

**Issue by Sidewinder53** [loiste-interactive/infra-issues#754]
This would make it much easier to report bugs and give them a meaningful title.
Mentioned file: [https://github.com/loiste-interactive/infra-issues/blob/master/README.md](url)

_I would also like to take the opportunity and thank you for the amazing Part II of Infra, it's a joy playing this game and it gave me a few good laughs - whoever designed this billboard deserves a prize ;)_

![20160925194915_1](https://cloud.githubusercontent.com/assets/19623985/18817902/5794f578-836c-11e6-8e4d-2dadb7cd86ae.jpg)
_I really appreciate what you guys and gals (?) are doing!_

**Comment by Yuccaa** [comment]
Added.
