### ISSUE TITLE
Ivy clipping trough door when opening

### ISSUE THREAD

**Issue by Sidewinder53** [loiste-interactive/infra-issues#755]
_This is a minor graphical glitch which is probably subject to personal opinion, so if you think that this is not an issue please just close it, I won't be resentful :)_

![20160925190037_1](https://cloud.githubusercontent.com/assets/19623985/18817931/e65f84e4-836c-11e6-90cb-c98bd54b1bbc.jpg)

**Comment by Yuccaa** [comment]
Fixed.
