### ISSUE TITLE
Gamebreaking: Caught in monitor view

### ISSUE THREAD

**Issue by Sidewinder53** [loiste-interactive/infra-issues#758]
![20160925223516_1](https://cloud.githubusercontent.com/assets/19623985/18818076/7f664134-8370-11e6-88d2-c5e846813fcc.jpg)
I picked up the yellow keys right next to the keyboard, pressed E to view the monitor and now I am trapped in this "view-monitor" mode. Neither ESC nor any other button is doing anything at all and the game somehow made an autosave and overwrote my Savegame 4, which I used to save manually, right at that point, so I would need to replay the whole "Public transport" chapter to continue. Is there any console command to get away from this monitor?

**Comment by aleksijuvani** [comment]
I'm looking into the issue. As a workaround, you should be able to rename `autosave.sav` to `autosave_old.sav` and then `autosave01.sav` to `autosave.sav` in your save game folder. This will replace your current autosave with your previous one.

You can find your saved games by right-clicking INFRA on Steam, selecting "Properties", "Local Files", and "Browse Local Files...". They are in the `infra/save` folder.

**Comment by aleksijuvani** [comment]
Also, if you can get the console up, I think the console command to exit that specific screen is `ent_fire computer_disable_viewcontrol trigger`. I think you need `sv_cheats 1` for that.

**Comment by Sidewinder53** [comment]
I will try that and keep you posted with the results. If you need any additional information do not hesitate to ask me!

**Comment by Sidewinder53** [comment]
With your workaround I was able to restore an older savegame, however this bug occurs again inconsistently each time I view the monitor.

**Comment by sebastiannielsen** [comment]
Have you tried to click the EXIT button with the mouse pointer?

**Comment by Sidewinder53** [comment]
The mouse pointer is disabled/not visible.

**Comment by sebastiannielsen** [comment]
I suspect the issue is then that the monitor view has toggled into "non viewing mode" but your view has toggled into "monitor viewing mode".

It could happen if you spam "use" on the monitor what I know.

**Comment by Sidewinder53** [comment]
Actually, that's what I suspected as well. So when I used the monitor for the second time I made sure to only press the 'E' button once and not for too long, so it could get interpreted as two inputs. The view mode hang nevertheless.

**Comment by Oskutin** [comment]
I managed to reproduce this by pressing 'e' on the computer and 'esc' at the same time.
Do you heard a sound when pressing up and down arrow buttons?

**Comment by aleksijuvani** [comment]
I think that's a separate issue. Does this happen with any other monitors or just this one?

**Comment by Sidewinder53** [comment]
I could reproduce this issue only with this monitor, others seem to be just fine. Pressing ESC + UP/DOWN worked and played the menu sounds the first time I got locked into this view-mode, however the second time I couldn't get any of this to work. Seems to be a weird and inconsistent problem.

**Comment by aleksijuvani** [comment]
I'm having a hard time reproducing the issue (well, without pressing ESC and E at the same time that is). Would you happen to have a saved game where this happens?

**Comment by Sidewinder53** [comment]
The save in which I got trapped in that bugged state was somehow overwritten by some other autosave, so right now I can't send you that file. However, I will try to reproduce that issue when I have completed chapter II and then I'm gonna send you that save file.

**Comment by aleksijuvani** [comment]
Fixed.
