### ISSUE TITLE
Boxes in the final climbing puzzle in cistern need to be relocated.

### ISSUE THREAD

**Issue by Yuccaa** [loiste-interactive/infra-issues#762]
Currently they're in a strange place behind the control room and are hard to move out.

**Comment by aleksijuvani** [comment]
![20160927135044_1](https://cloud.githubusercontent.com/assets/3168386/18870815/1f1026b4-84bb-11e6-8a1f-984788ea33c3.jpg)

**Comment by Zuntti** [comment]
Changed location and added two crates.
