### ISSUE TITLE
cistern: needs lots and lots of clip brushes

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#763]
The ladders in the climbing section are difficult to get to. Needs clip brushes for near the wall so that the player doesn't get stuck on the scaffolding. Could also use clip brushes behind the ladders. Maybe on the sides as well?

![20160927134948_1](https://cloud.githubusercontent.com/assets/3168386/18870480/7aad7258-84b9-11e6-895c-22bbecff1cf2.jpg)
![20160927135014_1](https://cloud.githubusercontent.com/assets/3168386/18870479/7aa8c0dc-84b9-11e6-9315-69bc2c381130.jpg)

The pipes need clip brushes:

![20160927135029_1](https://cloud.githubusercontent.com/assets/3168386/18870481/7e677e8e-84b9-11e6-9ee6-4089c0e18946.jpg)

This pipe needs a rectangular clip brush. It's impossible to stack the crates and climb on it right now:

![20160927135058_1](https://cloud.githubusercontent.com/assets/3168386/18870499/8ec1dfea-84b9-11e6-8e0c-fc1474a9bd5b.jpg)

**Comment by Zuntti** [comment]
Fixed.
