### ISSUE TITLE
furnace: stuck on the pipe

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#77]
It was the second time I went on this pipe but this time the player got stuck in the position of the screenshot and started taking damage repeatly 
![2015-11-02_00025](https://cloud.githubusercontent.com/assets/15571788/10885413/617416ce-817d-11e5-8cfb-f5ae37612d18.jpg)

PS I also had not enough time to try to get unstuck because after a minute the game crashed because of issue #62 (The two problems are not connected)

**Comment by Oskutin** [comment]
Fixed in next update
