### ISSUE TITLE
Mirror shows bathroom in waterplant office

### ISSUE THREAD

**Issue by wirion** [loiste-interactive/infra-issues#774]
In the office building of the water plant, in the central area (not an office room or the staircase) on one of the 3 levels there is a mirror which reflects a bathroom rather than the area it's hung in.

Sorry for the lack of specificity, I didn't have a save from that level.

**Comment by aleksijuvani** [comment]
Is this the same issue as #776?

**Comment by aleksijuvani** [comment]
Alright, closing this one since it's the same issue.
