### ISSUE TITLE
metro: nodraw spotted

### ISSUE THREAD

**Issue by demonz312** [loiste-interactive/infra-issues#778]
![20160927205734_1](https://cloud.githubusercontent.com/assets/4908029/18885610/0e10cfdc-84f5-11e6-9606-40fe6eca27f8.jpg)
![20160926220123_1](https://cloud.githubusercontent.com/assets/4908029/18885428/421ef034-84f4-11e6-8b2c-cc3ac8936eba.jpg)

**Comment by Yuccaa** [comment]
Fixed.
