### ISSUE TITLE
Tunnel 4 graphical issues

### ISSUE THREAD

**Issue by DevinShadowV** [loiste-interactive/infra-issues#779]
I left the notes in the screencaps...

![1](https://cloud.githubusercontent.com/assets/15645339/18901085/abe6a5a4-84fc-11e6-890a-8df662645663.jpg)
![2](https://cloud.githubusercontent.com/assets/15645339/18901087/abeab84c-84fc-11e6-8b25-0667daa3432d.jpg)
![3](https://cloud.githubusercontent.com/assets/15645339/18901086/abeaa168-84fc-11e6-93b0-31aa52e1193c.jpg)

**Comment by Yuccaa** [comment]
Created a separate issue for the camera.

**Comment by Zuntti** [comment]
Fixed rock.

**Comment by Zuntti** [comment]
Fixed.
