### ISSUE TITLE
metroride: missing camera targets after collapse

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#782]
![20160929174215_1](https://cloud.githubusercontent.com/assets/3168386/18958841/b9144954-866c-11e6-8e72-96d9fa16fc15.jpg)
![20160929174220_1](https://cloud.githubusercontent.com/assets/3168386/18958840/b912c2b4-866c-11e6-932b-255c7d684761.jpg)

**Comment by Yuccaa** [comment]
Fixed.
