### ISSUE TITLE
stormdrain: unlockable door missing latch model

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#785]
![20160930191625_1](https://cloud.githubusercontent.com/assets/3168386/18998754/a126545a-8742-11e6-8944-61f987a8df2e.jpg)

**Comment by sebastiannielsen** [comment]
Personally, I think the latch model should not be overused. It becomes kinda unrealistic then. The open thumbthurn without a emergency cover is enough visible cue that the door can be opened from this side.

However, locked doors should never have visible thumbthurn, then it should be with a emergency cover (like the door at the office exit to sewer1 in watertreatment). I think theres a few doors with a visible thumbturn that is locked.

**Comment by Zuntti** [comment]
Added.
