### ISSUE TITLE
stormdrain: emergency outflow gate puzzle makes no sense

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#787]
![20160930192245_1](https://cloud.githubusercontent.com/assets/3168386/18998911/4e360c44-8743-11e6-9b1c-cca6bc36389c.jpg)

**Comment by madattak** [comment]
I didn't understand it, I just hit buttons until the lights came on.

**Comment by Zuntti** [comment]
Fixed.
