### ISSUE TITLE
stormdrain: batteries can be picked up through the box

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#789]
Needs toggleable brushes to prevent the player from using things inside the box. I think there was a similar box somewhere else that has the same issue, but I can't remember where.

![20161002151438_1](https://cloud.githubusercontent.com/assets/3168386/19020497/1c7118b8-88b3-11e6-99fe-a95a2e233a04.jpg)

**Comment by sebastiannielsen** [comment]
yeah, it was the keys inside the box at the overgrown building in tunnel4.

**Comment by Zuntti** [comment]
Stormdrain fixed.

**Comment by aleksijuvani** [comment]
Now you can't pick up the batteries unless you look at them in a weird angle.

**Comment by Zuntti** [comment]
Fixed servicetunnel and stormdrain.
