### ISSUE TITLE
stormdrain: player can push himself inside this wall with the minitrain

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#790]
![20161002151627_1](https://cloud.githubusercontent.com/assets/3168386/19020520/912b56e6-88b3-11e6-880d-caf92fbd7121.jpg)
![20161002151628_1](https://cloud.githubusercontent.com/assets/3168386/19020521/9220adc6-88b3-11e6-8443-e12e6c255ef7.jpg)

**Comment by Zuntti** [comment]
Fixed.
