### ISSUE TITLE
bunker: "gas sensors" sign grammar

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#793]
![20161003141101_1](https://cloud.githubusercontent.com/assets/3168386/19035636/571ce86e-8973-11e6-8041-1a411c81e791.jpg)

Right now it says "fan closes automatically when all sensors **detects** toxic gases", but it needs to say "fan closes automatically when all sensors **detect** toxic gases".

**Comment by Zuntti** [comment]
Fixed.
