### ISSUE TITLE
bunker: relay and sound spam

### ISSUE THREAD

**Issue by sebastiannielsen** [loiste-interactive/infra-issues#795]
seems that logic_relay blast_door_fully_open isn't healthy. Its spams all the time causing it to not be fired when it should (may be related to the sound issue).
Also the blast door sounds can't find its entities. And also its spamming even when the doors are fully open:

(49.97) output: (prop_dynamic,blast_doors1) -> (blast_doors1_snd2,PlaySound)()
(49.97) output: (prop_dynamic,blast_doors1) -> (blast_doors1_snd,Volume)(0)
(49.97) output: (prop_dynamic,blast_doors1) -> (blast_doors1_snd,StopSound)()
unhandled input: (PlaySound) -> (blast_doors1_snd2), from (prop_dynamic,blast_doors1); target entity not found
unhandled input: (Volume) -> (blast_doors1_snd), from (prop_dynamic,blast_doors1); target entity not found
unhandled input: (StopSound) -> (blast_doors1_snd), from (prop_dynamic,blast_doors1); target entity not found

Note that no incorrect sound is playing, so this isn't a audio bug.
Such spam can also cause performance issues in the game.

**Comment by Yuccaa** [comment]
I don't seem to have these errors in the console. Is this still happening?

**Comment by sebastiannielsen** [comment]
Yes. Type developer 2. The problem is that these entities keep retriggering, which might cause heavy performance issues.

**Comment by Zuntti** [comment]
Fixed.
