### ISSUE TITLE
metroride: it should be more obvious that you need to crouch here

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#797]
![20161006183802_1](https://cloud.githubusercontent.com/assets/3168386/19160004/009ee678-8bf7-11e6-8d08-a6c9246dc71c.jpg)

The top part of this opening should be more well blocked. Right now it looks like you could just walk there, but you can't.

**Comment by Yuccaa** [comment]
Actually the player is able to walk through, but the metal bar on the floor is blocking the movement.

**Comment by Yuccaa** [comment]
Fixed.
