### ISSUE TITLE
reserve2: dam generators puzzle may be broken

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#80]
The sign says that 01+02 rpm must be OVER 6000 bu I managed to turn them on with 5500
![2015-11-02_00027](https://cloud.githubusercontent.com/assets/15571788/10889565/0be13e1a-8193-11e5-9ae4-b4cbd5f7597e.jpg)
I set both generators like this
![2015-11-02_00028](https://cloud.githubusercontent.com/assets/15571788/10889583/241cd836-8193-11e5-843d-ca4d028ee6ec.jpg)
FEEDBACK: it's quite difficult to read the values on the single generators

**Comment by Zuntti** [comment]
Fixed.
