### ISSUE TITLE
stormdrain: the potentially dangerous autosaves at the minitrain dodging part need to be marked as "dangerous"

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#803]

**Comment by aleksijuvani** [comment]
Here's an autosave where the player is stuck in a death loop because they're about to get hit by a minitrain.

[autosave.zip](https://github.com/loiste-interactive/infra-issues/files/519610/autosave.zip)

**Comment by Zuntti** [comment]
Fixed.
