### ISSUE TITLE
[Gameplay] No indication of one-way traps

### ISSUE THREAD

**Issue by milesrotaru** [loiste-interactive/infra-issues#807]
I'm only on the first level and was trying to explore the area as thoroughly as possible. I entered an elevator not knowing that it was going to break and cut me off from some places that I intended to go back to. I assumed the order I explored paths in wouldn't matter. I had to start over completely and now must save constantly in case something like that happens again. Please implement something like asking the player if they're really ready to leave the current area behind before loading a new map, or autosaving before the transition instead of after.

**Comment by sebastiannielsen** [comment]
Autosave before sounds legit, as the elevator is not a "difficult" or "dangerous" scene the player would want a save after.
But having a prompt would take away the realism.

**Comment by aleksijuvani** [comment]
The game keeps track of two autosaves at all times. In the next update I've made the previous autosave accessible from the load game menu. Hopefully that will alleviate the problem a bit.
