### ISSUE TITLE
Control binding menu truncates certain names

### ISSUE THREAD

**Issue by milesrotaru** [loiste-interactive/infra-issues#808]
![251110_20161012230343_1](https://cloud.githubusercontent.com/assets/1683975/19335326/62bc1992-90d0-11e6-8eac-fc7d541403c0.png)

See screenshot. "Mouse 4" and "Mouse 5" are both shortened to "Mo", potentially leading to mild inconvenience or confusion if one forgets their custom bindings and comes back to check them.

**Comment by aleksijuvani** [comment]
Fixed in the next update.
