### ISSUE TITLE
tunnel4: door doesn't show the other room 

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#81]
It's the door with the stairs to go to the bottom of the room with the two falls
![2015-11-02_00040](https://cloud.githubusercontent.com/assets/15571788/10892307/f5480994-81a2-11e5-8400-fcade8b9e518.jpg)
![2015-11-02_00039](https://cloud.githubusercontent.com/assets/15571788/10892306/f31485e4-81a2-11e5-921c-61332e8f0c99.jpg)

**Comment by Zuntti** [comment]
Fixed.
