### ISSUE TITLE
watertreatment: bad collision model on secondary clarifier

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#818]
![20161023140721_1](https://cloud.githubusercontent.com/assets/3168386/19625774/227bc7da-992a-11e6-913f-095d15040a9e.jpg)

You can walk right through these horizontal beams.

![20161023140928_1](https://cloud.githubusercontent.com/assets/3168386/19625785/52054742-992a-11e6-83c4-54f661e762cd.jpg)

**Comment by Yuccaa** [comment]
Fixed.
