### ISSUE TITLE
stormdrain: mistake valve is problematic

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#819]
![20160915142441_1](https://cloud.githubusercontent.com/assets/3168386/18548172/306abc54-7b50-11e6-9fd8-2471953b2d1d.jpg)

Every single player will close it just to see what happens because the pH sensor warning won't lit up until afterwards. At that point it's impossible to undo the mistake without reloading a saved game, which is kind of dumb.

But if we're going to keep that, maybe add a note somewhere that says to keep this valve always open? Right now you can't know that you're about to make a mistake until you have already made it.

**Comment by Yuccaa** [comment]
Added a note.
