### ISSUE TITLE
watertreatment : lab door with inverted behavior

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#829]
After opening the door, you won't be able to close it until you use the card reader. Then once closed, you'll be able to open it without using the card reader.
![20161024212354_1](https://cloud.githubusercontent.com/assets/15633807/19660517/765df3c6-9a30-11e6-929f-c73ad0d3cba4.jpg)

**Comment by aleksijuvani** [comment]
Does this happen with all doors or just this one?

**Comment by N-G-Neer** [comment]
I think just this one.

**Comment by Zuntti** [comment]
Fixed.
