### ISSUE TITLE
bunker : Achievements locked

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#834]
I cannot get the "Demon Core Experiment" despite putting the deflector on the core in the labs. I did not enable sv_cheats for this session, I only have -console as a launch attribute in the Steam client.

Same thing for the "State Accommodation" one.

**Comment by aleksijuvani** [comment]
I tested this and the achievement triggers should be working. Did you use the map or changelevel commands? That's enough to disable achievements for the session.

**Comment by N-G-Neer** [comment]
Oh, well that must be it then. I used changelevel from the main menu to get there. (I thought only stuff that required sv_cheats 1 disabled the achievements)
