### ISSUE TITLE
stormdrain : new puzzle, still confused

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#835]
So you're supposed to : 
- Wire 2 gates per switch.
- Wire G1 and G3 to B2.
- (Implicitly) Wire G2 and G4 to B1.

We know that the switches have one to several inputs and only two outputs (marked red and blue).

Problem : If we look at all possible solutions for G1 (which is supposed to be wired to B2), all wires go to B1 and none go to B2.

Am I supposed to think from the buttons to the gates instead ? Also some judiciously placed light sources would be greatly appreciated, or maybe make the back wall of the cabinet the same color as its door ? (this image has been brightened for your viewing comfort) :P 

![holy-mother-of-watt](https://cloud.githubusercontent.com/assets/15633807/19668507/9d187ee6-9a58-11e6-8cc4-d9197d9629e5.png)

**Comment by aleksijuvani** [comment]
That's part of the puzzle. You have to wire G1 to B1. You also obviously have to wire G4 to B1 since that's the only working button. Then wire the remaining G2 and G3 to the broken B2 button.

**Comment by N-G-Neer** [comment]
So what about the notice on the door then ? Is it misleading you on purpose ? Unless it's meaning to say Button 2 -> Broken gates 1 to 3 ?

**Comment by Zuntti** [comment]
Changed text to Broken Gates 1-3 and Button 2.

**Comment by Zuntti** [comment]
Changed back wall white.
