### ISSUE TITLE
error GetTickCount64 on Windows XP sp3 32bits

### ISSUE THREAD

**Issue by rocknard** [loiste-interactive/infra-issues#836]
I get this error when i try to play the game:

he procedure entry point GetTickCount64 could not be located in the dynamic link library KERNEL32.dll

Info about this problem:

https://blog.inventic.eu/2013/08/gettickcount64-problem-on-windowsxp/

Thanks you.

**Comment by aleksijuvani** [comment]
Thanks for reporting the issue. I don't have a Windows XP machine to test this on right now, so it'll take me some time to setup a virtual machine. I'm going to do that now and I'll try to get this fixed as soon as possible.

**Comment by aleksijuvani** [comment]
I'm having trouble reproducing the issue. I installed Windows XP on a spare machine that I had lying around and the game seems to run fine.

![screen2](https://cloud.githubusercontent.com/assets/3168386/19734947/444bea72-9bb2-11e6-9b65-5fa3880b1b75.png)

Could you open the Start Menu, click "Run...", type in `winver`, press Enter and take a picture of the window that pops up?

**Comment by aleksijuvani** [comment]
I just checked and INFRA doesn't use `GetTickCount64` anywhere. This error message must be caused by something else.

Do you have an anti-virus installed? What happens if you temporarily disable it prior to launching INFRA?

**Comment by rocknard** [comment]
¡Ops! Now works. I reinstalled the game (disabling the anti-virus). Odd.

Sorry for the inconvenience.

**Comment by aleksijuvani** [comment]
Good that it's working. At least I know that the game runs fine on Windows XP now.
