### ISSUE TITLE
This broken catwalk should work like a ladder or be moved/removed

### ISSUE THREAD

**Issue by Yuccaa** [loiste-interactive/infra-issues#837]
![infra_c7_m3_stormdrain0001](https://cloud.githubusercontent.com/assets/5402153/19689204/437bbc9a-9ad5-11e6-9aad-b14a578123d6.jpg)

At the moment it looks like player should be able to climb it. It could be allowed too, that concrete path is in no way out of bounds as there already is the gate blocking movement.

**Comment by Zuntti** [comment]
Added ladder.
