### ISSUE TITLE
Load times

### ISSUE THREAD

**Issue by mpeltomaa** [loiste-interactive/infra-issues#84]
Sometimes it takes quite long time to load levels. I don't have any heavy background processes or AV working behind. 30s - 60s is long time in my opinion.

Specs:
128 GB SSD, Intel i5, 8 GB RAM, Win 10

**Comment by Suhov** [comment]
Yeah, level loading (both main menu and Reserve1) taking too much time. And the loading logo in the bottom right part of the screen do not move most of the time making me believe game just hanged.

**Comment by aleksijuvani** [comment]
Sound cache now ships with the game.
