### ISSUE TITLE
stormdrain: branching minitrain tracks have collisions

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#846]
![20161026211815_1](https://cloud.githubusercontent.com/assets/3168386/19738932/d62ed4e0-9bc1-11e6-86d8-ea7757d584ce.jpg)
![20161026211831_1](https://cloud.githubusercontent.com/assets/3168386/19738931/d62d258c-9bc1-11e6-81e9-065b57e04176.jpg)

**Comment by Zuntti** [comment]
Fixed.
