### ISSUE TITLE
minitrain: branching tracks have collisions

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#847]
![20161026212031_1](https://cloud.githubusercontent.com/assets/3168386/19739086/55a0e6aa-9bc2-11e6-9aa1-458aa9bb5317.jpg)
![20161026212150_1](https://cloud.githubusercontent.com/assets/3168386/19739087/55b9ae2e-9bc2-11e6-81ac-998696177035.jpg)
![20161026212146_1](https://cloud.githubusercontent.com/assets/3168386/19739090/55cef45a-9bc2-11e6-81fe-f0f5c06946d3.jpg)
![20161026212120_1](https://cloud.githubusercontent.com/assets/3168386/19739088/55cc0510-9bc2-11e6-9dc2-28505473b47a.jpg)
![20161026212116_1](https://cloud.githubusercontent.com/assets/3168386/19739089/55ce3290-9bc2-11e6-8903-152cd3c2bb54.jpg)
![20161026212113_1](https://cloud.githubusercontent.com/assets/3168386/19739091/55d471fa-9bc2-11e6-85f8-e2a59c8f92ea.jpg)

**Comment by Yuccaa** [comment]
Fixed.

**Comment by Yuccaa** [comment]
Actually not. They are prop_door_rotating which doesn't have collision parameter. Collision needs to be removed from the models themselves.

**Comment by Zuntti** [comment]
Fixed.
