### ISSUE TITLE
metro: untextured papers?

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#850]
![20161027013459_1](https://cloud.githubusercontent.com/assets/3168386/19747662/b2454c52-9be5-11e6-837c-cb695b99ac69.jpg)

What are these supposed to be?

**Comment by Yuccaa** [comment]
They're just plain empty papers.

**Comment by aleksijuvani** [comment]
This doesn't make much sense. Why would they gift them a bunch of paper?

**Comment by Oskutin** [comment]
The gift is in O-shelf.

**Comment by aleksijuvani** [comment]
That's dumb. The note doesn't specify where the gift is so it's implied that the gift would be next to the note.

When watching videos of INFRA, players are having trouble understanding the note as well.

**Comment by Zuntti** [comment]
Changed the location of the paper.
