### ISSUE TITLE
metro: locked bathroom doors are useable if aiming directly at the handle

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#852]
![20161027014208_1](https://cloud.githubusercontent.com/assets/3168386/19747819/a354aebc-9be6-11e6-8654-b6d027e227dd.jpg)
![20161027014214_1](https://cloud.githubusercontent.com/assets/3168386/19747820/a36ceef0-9be6-11e6-837f-341c906f9eb2.jpg)

**Comment by Yuccaa** [comment]
Fixed.
