### ISSUE TITLE
cistern: control room needs a player clip

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#861]
![20161030120608_1](https://cloud.githubusercontent.com/assets/3168386/19835815/4f2e015c-9e99-11e6-9a03-8495e5be8066.jpg)

It's possible to climb on top of the railing and get stuck between the railing and the window. You can crouch to get unstuck, but still, there should be a player clip that prevents from climbing on the railing.

**Comment by Yuccaa** [comment]
Fixed.
