### ISSUE TITLE
cistern: finicky ladders

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#862]
![20161030123609_1](https://cloud.githubusercontent.com/assets/3168386/19836015/bca2e4f6-9e9d-11e6-8ee1-2631febe9665.jpg)
![20161030123752_1](https://cloud.githubusercontent.com/assets/3168386/19836016/bcbc0cb0-9e9d-11e6-839a-89c9664dde77.jpg)
![20161030123658_1](https://cloud.githubusercontent.com/assets/3168386/19836018/bcd2921e-9e9d-11e6-9e17-494440adf255.jpg)
![20161030123626_1](https://cloud.githubusercontent.com/assets/3168386/19836017/bcd15ae8-9e9d-11e6-8e1d-2282ae71ae50.jpg)

**Comment by aleksijuvani** [comment]
Also this one. It's difficult to climb up because you collide with the model:

![20161030205512_1](https://cloud.githubusercontent.com/assets/3168386/19839007/36bc34b4-9ee3-11e6-833e-c5e96b5a75a7.jpg)

**Comment by Yuccaa** [comment]
Fixed all.
