### ISSUE TITLE
cistern: optimization issue

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#867]
This area is drawn even when you're on the other side of the closed gates:

![20161030204533_1](https://cloud.githubusercontent.com/assets/3168386/19838945/0750ccae-9ee2-11e6-95cd-bdd1aae49d8d.jpg)

It's not just limited to the immediate vicinity of the gates. It's drawn all the way from the other side of the map if you're looking in that general direction.

![20161030204819_1](https://cloud.githubusercontent.com/assets/3168386/19838952/3f75ad0c-9ee2-11e6-9f4a-e5204f20a4df.jpg)

**Comment by Yuccaa** [comment]
Fixed.
