### ISSUE TITLE
metroride : possible to get stuck in train doors

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#872]
![20161102135427_1](https://cloud.githubusercontent.com/assets/15633807/19931300/42704efa-a10c-11e6-8bce-6598c557fc82.jpg)
If you stand between the doors and press E to close them, you will be unable to move or re-open the doors again.

**Comment by Yuccaa** [comment]
@aleksijuvani is this the issue you already fixed?

**Comment by aleksijuvani** [comment]
might be a different issue

**Comment by aleksijuvani** [comment]
It wasn't. Looks like this is fixed as well.
