### ISSUE TITLE
stormdrain: player clip needed

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#880]
![20161110155510_1](https://cloud.githubusercontent.com/assets/3168386/20179286/1304f582-a75e-11e6-87d2-8d9ceccd581c.jpg)
![20161110155350_1](https://cloud.githubusercontent.com/assets/3168386/20179273/f293de94-a75d-11e6-98c9-f0c127e69549.jpg)

The player will automatically stand up when crouching here because of the empty space between the pipes, which probably isn't what they want to do.

**Comment by Zuntti** [comment]
Fixed.
