### ISSUE TITLE
Part of the metro closed line could be removed

### ISSUE THREAD

**Issue by Yuccaa** [loiste-interactive/infra-issues#887]
![infra_c6_m2_metro0000](https://cloud.githubusercontent.com/assets/5402153/20448308/fb53c2bc-adeb-11e6-9f64-f34be181b21b.jpg)

Maybe the leftmost part on this side. Many players don't seem to realize at first the player is able to bypass the line. It would also work as an incentive for the players.

**Comment by aleksijuvani** [comment]
I don't think that's a good idea. Right now it seems to keep the players in the upper area until the phone call is done, which I feel is a good thing. They seem to figure out pretty quickly that they can bypass the line.

I feel like we could try adding an auto-crouch trigger there, though. Climbing over the line looks and feels pretty bad.

**Comment by Yuccaa** [comment]
Added playerclips and auto-crouch triggers.
