### ISSUE TITLE
Water sensor puzzle makes no sense whatsoever

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#89]
![251110_2015-11-02_00001](https://cloud.githubusercontent.com/assets/3168386/10910680/7136e36c-8249-11e5-9829-ad066ee47eb7.png)

**Comment by Suhov** [comment]
Yeah, got stuck here too. A2 switch is not working, the pipe is broken and were closed manually before that room.
![2015-11-04_00021](https://cloud.githubusercontent.com/assets/15650861/10941831/37205b56-831e-11e5-85f7-3e755fb34a0c.jpg)

**Comment by Zuntti** [comment]
Fixed.
