### ISSUE TITLE
Newspaper : Same article for two different years

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#894]
When translating newspaper.idml, I noticed that there were two identical articles about Stalburg FC's victory in the National Football League. The two newspapers were published two years apart though (1979-1981). I took the liberty while translating to modify the most recent one to say they somehow managed to make history repeat itself.

**Comment by Yuccaa** [comment]
If I remember correctly, one of them is under so much dirt in the game it's hard to read.
