### ISSUE TITLE
tunnel: misleading beams should be removed

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#895]
These beams should be removed completely since the player is not supposed to be able to walk on them. Right now they trick the player into thinking that they can walk on them, but the game will just always push them off.

![20161202132005_1_edit](https://cloud.githubusercontent.com/assets/3168386/20832339/83f901a8-b892-11e6-9cec-0fe2f8e1e0e7.jpg)

The water flow meter also needs player clips to prevent the player from climbing on top of it:

![20161202132420_1_edit](https://cloud.githubusercontent.com/assets/3168386/20833445/659ed84e-b898-11e6-9c8a-da8217df1db8.jpg)

**Comment by Yuccaa** [comment]
Removed. Added.
