### ISSUE TITLE
metro: boiler should heat up and cool down instantly

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#899]
This is causing lots of unnecessary grief for players. It's not obvious that you should wait for the pipe to cool down before going across. The pipe isn't indicating its current state too well either. It looks like it would kill you when it can in fact be safe to go across (although receiving some damage), and vice versa.

**Comment by sebastiannielsen** [comment]
Best would be to add a thermometer. Then it would be very visible that it cools down.

**Comment by Yuccaa** [comment]
Changed it to cool down much faster.
