### ISSUE TITLE
reserve2: out of bounds by climbing on top of the sawmill roof with crates

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#901]
![251110_screenshots_20161222005645_1](https://cloud.githubusercontent.com/assets/3168386/21425638/199422ea-c853-11e6-8698-54e25c46986f.jpg)
![251110_screenshots_20161222005404_1](https://cloud.githubusercontent.com/assets/3168386/21425642/1aba2534-c853-11e6-9bd0-48013f512e05.jpg)

Can we make it so that you can't bring the crates outside the sawmill?

**Comment by Zuntti** [comment]
Fixed.
