### ISSUE TITLE
tunnel2: out of bounds

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#902]
http://steamcommunity.com/app/251110/discussions/1/154644519324241371/

> A door on the intersection in the facility has a handle with a collision box. Because of this, it can be escalated, leading the player onto the roof which allows them to bypass player clips and go over fences or behind the map or even down the hill.

![251110_screenshots_20161222192324_1](https://cloud.githubusercontent.com/assets/3168386/21452728/a08220cc-c911-11e6-8ba4-3fe459ef02cb.jpg)
![251110_screenshots_20161222192341_1](https://cloud.githubusercontent.com/assets/3168386/21452735/a09de9b0-c911-11e6-92b6-dd6b10fa9470.jpg)
![251110_screenshots_20161222192346_1](https://cloud.githubusercontent.com/assets/3168386/21452734/a09a1506-c911-11e6-99e0-511cad29dbc2.jpg)
![251110_screenshots_20161222192352_1](https://cloud.githubusercontent.com/assets/3168386/21452729/a0846792-c911-11e6-8b06-6a4d45a429d2.jpg)
![251110_screenshots_20161222192409_1](https://cloud.githubusercontent.com/assets/3168386/21452733/a085734e-c911-11e6-9fd2-5a82e6bd419a.jpg)
![251110_screenshots_20161222191243_1](https://cloud.githubusercontent.com/assets/3168386/21452731/a084c6ce-c911-11e6-82ab-c85ed6617417.jpg)
![251110_screenshots_20161222191447_1](https://cloud.githubusercontent.com/assets/3168386/21452730/a0848650-c911-11e6-8cbb-8e5b3bb80e93.jpg)
![251110_screenshots_20161222191803_1](https://cloud.githubusercontent.com/assets/3168386/21452732/a0854284-c911-11e6-9ecf-44b3d7a7cd03.jpg)

**Comment by Zuntti** [comment]
Fixed.
