### ISSUE TITLE
Invisible barrier when walking down these stairs in tower

### ISSUE THREAD

**Issue by paavohuhtala** [loiste-interactive/infra-issues#91]
Very similar to #53.
`setpos 352.096985 -188.214951 -1593.180054;setang 48.205738 -136.448502 -0.000003`
![2015-11-03_00002](https://cloud.githubusercontent.com/assets/803180/10913251/c87b75fa-8255-11e5-9e27-b842944c6cd6.jpg)

**Comment by Oskutin** [comment]
Fixed in next update.
