### ISSUE TITLE
Weird white surfaces (decals?) in tunnel3

### ISSUE THREAD

**Issue by paavohuhtala** [loiste-interactive/infra-issues#92]
`setpos 12684.555664 11871.779297 77.160484;setang 17.985678 70.875481 0.000001`
![2015-11-03_00003](https://cloud.githubusercontent.com/assets/803180/10913690/c24e83aa-8257-11e5-866d-247a246cfd3d.jpg)

**Comment by Zuntti** [comment]
Fixed in the next update.
