### ISSUE TITLE
Game crashes when I try to take a picture of this tree in Chapter 2

### ISSUE THREAD

**Issue by Sockman1** [loiste-interactive/infra-issues#923]
Here's an image: http://steamcommunity.com/id/sockman101/screenshot/83716007340674512
I tried to take a picture twice, and the game froze, while a second of audio kept repeating over and over again. No other things have done this so far, only this one tree.

**Comment by aleksijuvani** [comment]
This was fixed in version 2.3.3 back in February. Same issue as #924.
