### ISSUE TITLE
Game freezes when taking a photograph

### ISSUE THREAD

**Issue by ddog3887** [loiste-interactive/infra-issues#924]
Anytime i take a picture in the beginning of part 2 the game crashes.

**Comment by aleksijuvani** [comment]
Hello,

Have you tried verifying the integrity of the game files? You can do so by right-clicking INFRA on Steam and selecting "Properties", "Local Files" and "Verify Integrity of Game Files...".

**Comment by ddog3887** [comment]
Yes and it didn't work.

**Comment by aleksijuvani** [comment]
Could you [send me a full system report by following these instructions](https://support.steampowered.com/kb_article.php?ref=1376-WTZN-9132)? Instead of sending it to Steam Support, send it to my email at aleksi@loisteinteractive.com.

**Comment by aleksijuvani** [comment]
If there are any `.mdmp` crash dump files in the game folder, please send those to me as well. You can get to the game folder by right-clicking INFRA on Steam, selecting "Properties", "Local Files" and "Browse Local Files...".

**Comment by madattak** [comment]
I am having the same issue. Attempting to take a photo of a valid damage causes the game to immediately freeze until the application is forced close.  Taking a photo with no target will not crash the game. I couldn't find any crash dump files. Will send system report.

**Comment by aleksijuvani** [comment]
If you right-click INFRA on Steam, select "Betas" and opt into the "2.2.0" beta, does this issue still happen?

**Comment by madattak** [comment]
Seems to have fixed the issue, although it's worth noting the game had auto saved the instant before the last game and so it has started from the corridor outside the start room of Part 2 instead of starting from the very beginning.

**Comment by aleksijuvani** [comment]
If you now opt-out of the beta, does the issue come back?

**Comment by madattak** [comment]
I'd continued on to the metal union, so I:
Started a new game at the start of part 2 (V 2.2.0)
Took a photo of the broken wall directly opposite
Saved
Opted out of all betas
Reloaded the save
Took a photo of the rubble through the broken window
Same crash as before

**Comment by madattak** [comment]
I then reloaded my save that I'd played up to entering the MWU building, (Having to restart the level) and took a photo of the first structural damage I found, and no crash!  :)

**Comment by madattak** [comment]
Tried to take a photo of something (not sure what, the camera box will focus when pointed at the right hang wall in the kitchen behind the counter) in the burger restaurant in the metro station, the game froze and crashed.

**Comment by aleksijuvani** [comment]
Still no crash dumps?

Could you start the game with the launch options `-dev -condebug +rr_debugresponses 3`, try to get it to freeze/crash, and then send me the resulting `console.log` file from the game folder?

You can set launch options by right-clicking INFRA on Steam, and selecting "Set Launch Options...".

**Comment by madattak** [comment]
Loaded my autosave and took a picture in the burger restaurant like before, the game froze. I think I've been using the word 'crash' wrong, as the game won't actually close, it will just completely freeze and the audio loop until I use the task manager to shut it down. It also prevents my mouse from responding until it's shutdown. (Using the keyboard to navigate the task manager) Sorry if this has caused any confusion.
console.txt file in attached zip file.
[console.zip](https://github.com/loiste-interactive/infra-issues/files/774661/console.zip)

**Comment by aleksijuvani** [comment]
Thanks for the help so far. You should remove the launch options now, since I think they prevent any achievement progress while they're set.

I had to try a couple of different machines, but I finally managed to reproduce the issue on a laptop. Looks like it has something to do with the lines that Mark says when taking a successful photo. I'm going to look into it a bit more.

**Comment by aleksijuvani** [comment]
I've created a new beta branch called "2.3.3". Could you try if that solves the issue? If it's not visible in the list, you might need to restart Steam.

**Comment by madattak** [comment]
Immediately crashes upon clicking continue
https://snag.gy/qFCNJO.jpg

**Comment by aleksijuvani** [comment]
Good catch. I've pushed out an update for the beta branch which fixes the error. It should be visible on Steam shortly.

**Comment by aleksijuvani** [comment]
Looks like this wasn't as straightforward as I had hoped. There seem to be a number of other problems with the beta branch as well. Some materials are showing up incorrectly, batteries can't be picked up, and several levels crash on load.

**Comment by aleksijuvani** [comment]
I've pushed out an another update which fixes the above issues. I'm going to keep this in beta for a while to see if any new problems show up.

**Comment by madattak** [comment]
I've played from entering the metro station to crashing maintenance tram without issue. Thank you for the quick update!

**Comment by aleksijuvani** [comment]
2.3.3 is now out of beta and live on Steam.
