### ISSUE TITLE
Water flow monitor sound issues

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#930]
## reserve1

![20170303135757_1](https://cloud.githubusercontent.com/assets/3168386/23550471/b912f10e-0019-11e7-8844-f85aa7763cf7.jpg)

Fuses are missing sounds.

## tunnel

![20170303135207_1](https://cloud.githubusercontent.com/assets/3168386/23550473/ba829cd8-0019-11e7-8462-17cb776b38ef.jpg)

Fuses are missing sounds.

## tunnel3

![20170303135823_1](https://cloud.githubusercontent.com/assets/3168386/23550476/bc8f080e-0019-11e7-93b6-50919f7c21cd.jpg)

Fuses and the power switch are missing sounds.

## tunnel4

![20170303135850_1](https://cloud.githubusercontent.com/assets/3168386/23550478/bde52706-0019-11e7-9eb9-ded239cec44d.jpg)

Fuses are missing sounds. The power switch uses `lightswitch_001.wav` instead of `switch_001.wav` like the rest.

**Comment by Zuntti** [comment]
Changed tunnel4 sound and added sounds to fuses. (OnIn = Lightswitch_001.wav and OnOut = Lightswitch_002.wav)

**Comment by Zuntti** [comment]
Fixed.
