### ISSUE TITLE
Reserve1: The clutter here looks too clean and new

### ISSUE THREAD

**Issue by CorruptComputer** [loiste-interactive/infra-issues#938]
For a basically abandoned place this stuff looks like its brand new and doesn't fit with the surroundings: the boat, chair, and umbrella.

![20170304214108_1](https://cloud.githubusercontent.com/assets/5573038/23585486/2d1b21b6-0146-11e7-9752-e1ab51622cc7.jpg)

**Comment by Zuntti** [comment]
Removed.
