### ISSUE TITLE
tunnel1: Areaportal issue in room before entrance to morko tunnel

### ISSUE THREAD

**Issue by CitadelCore** [loiste-interactive/infra-issues#946]
When closing the door that you come through, and leaving the inner door open, an areaportal closes in the inner door frame without the door closing.
![20170321190622_1](https://cloud.githubusercontent.com/assets/5567402/24167743/c8e0577a-0e6f-11e7-97e4-f6d33021aa43.jpg)

**Comment by Oskutin** [comment]
Fixed
