### ISSUE TITLE
Reserve2: Stuck on initial switch puzzle

### ISSUE THREAD

**Issue by rlee287** [loiste-interactive/infra-issues#947]
I have turned all the knobs with the dashed lines, but there is still a locked door. In addition, the gateway to the fuse area is locked.

Is this a bug, or is there something I am missing with this puzzle?

Screenshots:
![20170412225436_1](https://cloud.githubusercontent.com/assets/14067959/24991950/5030842e-1fd3-11e7-964d-22b5c62c6eaf.jpg)

![20170412225121_1](https://cloud.githubusercontent.com/assets/14067959/24991883/efdfc4e0-1fd2-11e7-9f6d-52ed2c4eb0a0.jpg)
![20170412225457_1](https://cloud.githubusercontent.com/assets/14067959/24991933/323ccbf8-1fd3-11e7-9741-3181b3ddf2a8.jpg)

![20170412225005_1](https://cloud.githubusercontent.com/assets/14067959/24991941/478e76fa-1fd3-11e7-9de0-141d3e6ccf0d.jpg)

**Comment by CorruptComputer** [comment]
See that vent in your last screenshot? Try to look for a way to get in to that room from there. This puzzle isn't bugged, try to look for a door you haven't opened yet.
