### ISSUE TITLE
furnace : possible to skip a bunch of puzzles

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#953]
https://youtu.be/9-i-zmv1TIY?t=707

Maybe a death from fall event should be added here ? (Or removing the metal roof tile thingie as to not tempt players to jump there.)

**Comment by CorruptComputer** [comment]
I had always thought of this one as intentional. The only thing you really skip is the crane, and that wasn't a huge puzzle anyways.

**Comment by N-G-Neer** [comment]
That and the toxic basement. Although getting the key to the control room is optional if you go through the hidden hatch.

**Comment by CorruptComputer** [comment]
I see how it could lead to confusion with the control room?

**Comment by Yuccaa** [comment]
Actually now that I watched the video, yeah this is indeed another legit way to complete the area.
