### ISSUE TITLE
bunker : Duplicate blastdoors seen re-opening at start of level

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#954]
As soon as the level loads, turn around and you will see duplicate blastdoors opening through the closed ones you just came from.

![20170512153508_1](https://cloud.githubusercontent.com/assets/15633807/26000515/905d3692-3729-11e7-855e-0d64a5d3f3ea.jpg)

**Comment by aleksijuvani** [comment]
Just to note; this only happens when transitioning from `infra_c7_m1_servicetunnel`.

**Comment by Zuntti** [comment]
Fixed.
