### ISSUE TITLE
tunnel4: Stuck when trying to jump on molden steel bucket

### ISSUE THREAD

**Issue by stohrendorf** [loiste-interactive/infra-issues#955]
I'm stuck here, and the game doesn't even lower the bucket down. I can look around, use the camera and flashlight, but can't crouch, jump or walk. Reloading the save (or even restarting the game) doesn't help.

![grafik](https://cloud.githubusercontent.com/assets/7853507/26025718/ee9e198c-37ed-11e7-8799-1208bec68040.png)

**Comment by aleksijuvani** [comment]
Could you send me your saved game so I can get you unstuck?

You can find your save files by right-clicking INFRA on Steam and selecting "Properties", "Local Files" and "Browse Local Files...". The saved games are located in the `infra/save` folder. There are a lot of files there, but I only need the relevant `.sav` file.

You can send it to my email at aleksi@loisteinteractive.com or zip it up and then attach it to this issue by drag and dropping it to the comment field.

**Comment by stohrendorf** [comment]
There you are: [slot_2.zip](https://github.com/loiste-interactive/infra-issues/files/998736/slot_2.zip)

No need to send a patched save back, it's just that it is the second time that I got stuck there, this time after a bunch of patches from you. The thing is, it's pretty easy to get stuck there, and I think it is of interest for you to get that fixed.

**Comment by aleksijuvani** [comment]
Ah, that's cool. I've fixed the issue and it should be out in the next patch.

**Comment by stohrendorf** [comment]
Thanks!
