### ISSUE TITLE
Tower: when loading alt- tabbing causes the game to crash

### ISSUE THREAD

**Issue by kaream123** [loiste-interactive/infra-issues#96]
If you alt tab while the game is loading the tower level the loading indicator stops and the game crashes

**Comment by aleksijuvani** [comment]
Is this happening for anyone else? I can't seem to reproduce the issue on my end.

If there are crash dumps (`mdmp` files) in the game folder, could you send them to me? To find them, right-click INFRA on Steam, select "Properties", "Local Files", and "Browse Local Files". They should be in the same folder that contains `infra.exe`.

Please also [send me a full system report by following these instructions](https://support.steampowered.com/kb_article.php?ref=1376-WTZN-9132) (except that don't send it to Steam Support, send it to my email instead!). My email is aleksi@loisteinteractive.com.

**Comment by aleksijuvani** [comment]
This has been fixed. This was the level transition issue where the levels were missing transitions back to the old level. Not caused by alt-tabbing after all.
