### ISSUE TITLE
Stuck after matro crash - can't turn of steam 

### ISSUE THREAD

**Issue by Thauron573** [loiste-interactive/infra-issues#961]
Hello, 

I am stuck shortly after the metro crash in chapter 6 because of what seems to be a bug. 

I entered the locked room, placed the valve in the proper (rather hidden) place but no matter how much I turn the valve, I can't stop the steam at the bottom of the ladder. 

Am i forgetting something or is this a bug?

Thank you.

**Comment by Yuccaa** [comment]
There's a second valve in the area you also need to turn off.
