### ISSUE TITLE
func_precipitation crash to desktop

### ISSUE THREAD

**Issue by CitadelCore** [loiste-interactive/infra-issues#967]
When I add a func_precipitation brush entity in my map, the game will CTD immediately after it finishes loading. This isn't a major problem because it isn't encountered in any map, just an engine bug.

The minidump is attached.
[infra_6819_crash_2017_7_18T15_40_50C0.zip](https://github.com/loiste-interactive/infra-issues/files/1158127/infra_6819_crash_2017_7_18T15_40_50C0.zip)

**Comment by Zuntti** [comment]
This is now fixed.
