### ISSUE TITLE
Game loading slow 

### ISSUE THREAD

**Issue by kaream123** [loiste-interactive/infra-issues#97]
Game varies in the time it takes to load up some levels for example first time i started the game it took over 5 minutes to start while on my second go it instantly started . Tower level loads very slowly compared to reserve 1

**Comment by aleksijuvani** [comment]
The reason for the slow startup when the game is first started is because the game needs to build a soundcache. We might be able to ship the soundcache with the game, but I'm not entirely sure. I'll look into it.

Sort of duplicate of #84, will use that one to track these problems.
