### ISSUE TITLE
tunnel4 : pipe darkness transition issue

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#971]
In the stairs leading to the 4 generators room.
![20170926031958_1](https://user-images.githubusercontent.com/15633807/30861200-47fdeb50-a2ca-11e7-9cac-a16f82fbd22f.jpg)
![20170926032000_1](https://user-images.githubusercontent.com/15633807/30861199-47fbe8aa-a2ca-11e7-8e60-86f6e5586fb0.jpg)

**Comment by Zuntti** [comment]
Fixed.
