### ISSUE TITLE
business: shadows under self-driving car remain after it changes parking spot

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#974]
![20170927232044_1](https://user-images.githubusercontent.com/3168386/30935836-99cbda12-a3da-11e7-93be-45a3459ee719.jpg)

**Comment by Kumasasa** [comment]
![image](https://user-images.githubusercontent.com/12480900/31058976-54454eda-a6fd-11e7-8408-71bd0977f455.png)

Isn't that the shadow of the wheeled table to the left of the shawdow ?

**Comment by Yuccaa** [comment]
It is. The shadow could be made more defined though.

**Comment by Yuccaa** [comment]
Fixed.
