### ISSUE TITLE
ingame television screens broken

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#978]
![](https://cdn.discordapp.com/attachments/291497857725366272/362719449167560706/20170927164711_1.jpg)

**Comment by Yuccaa** [comment]
Also in skyscraper

![image](https://user-images.githubusercontent.com/5402153/30943901-ff451c60-a3fc-11e7-9bb4-7e0501d0a9eb.png)

**Comment by aleksijuvani** [comment]
Fixed.

**Comment by KohGeek** [comment]
Note: Would actually appreciate the second one with Jeff Walter. Gives it an 'aged' feeling.
