### ISSUE TITLE
isle2: Leak on the floor is non-photographable

### ISSUE THREAD

**Issue by hawkiee552** [loiste-interactive/infra-issues#989]
![20170928173111_1](https://user-images.githubusercontent.com/18194426/30976937-610d55f6-a476-11e7-80e2-ea6a05930db3.jpg)

Probably should be? This is in the fuel tank room by the generators.

**Comment by KohGeek** [comment]
It was photographable after starting the generator, but so was the one near the entrance.
Perhaps should be photographable only once? Right now the first target near the generator room entrance can be photographed, then photographed again once starting the gens.

**Comment by Yuccaa** [comment]
Fixed.
