### ISSUE TITLE
powerstation2: the exterior lighting is too bright compared to the sky

### ISSUE THREAD

**Issue by Yuccaa** [loiste-interactive/infra-issues#991]
![infra_c8_m1_powerstation20000](https://user-images.githubusercontent.com/5402153/30979689-0d2a9a64-a487-11e7-86cc-57d1d588b0a7.jpg)

**Comment by Yuccaa** [comment]
The problem is actually that the skybox texture is too dark, rather than the lighting being too bright

**Comment by Zuntti** [comment]
Fixed.
